In [3]:
pip freeze > requirements.txt

**0) PREPROCESSING**:
- Convert placeholders like '?' to NaN
- Cast all columns to numeric
- Binarize target: 0 -> 0, 1-4 -> 1
- Impute missing feature values with column-wise median

In [ ]:
import pandas as pd
import numpy as np

def preprocess_heart_csv(input_csv_path: str, output_csv_path: str = "heart_clean.csv") -> pd.DataFrame:
    # 1) Oku: '?' vb. eksik değerleri NaN yap
    df = pd.read_csv(
        input_csv_path,
        na_values=["?", "??", "???", "????", " ?"],
        skipinitialspace=True,
        engine="python"
    )

    # 2) Clean column names (strip leading/trailing spaces)
    df.columns = [c.strip() for c in df.columns]

    # 3) Validate expected columns (optional but recommended)
    expected = ["age","sex","cp","trestbps","chol","fbs","restecg","thalach","exang","oldpeak","slope","ca","thal","target"]
    missing_cols = [c for c in expected if c not in df.columns]
    if missing_cols:
        raise ValueError(f"Missing expected column(s) in CSV: {missing_cols}\nAvailable columns: {list(df.columns)}")


    # 4) Convert all expected columns to numeric (non-numeric -> NaN)
    for c in expected:
        df[c] = pd.to_numeric(df[c], errors="coerce")

    # 5) Binarize target: 0 -> 0, 1-4 -> 1
    # Drop rows with missing target (instead of imputing target)
    df = df[df["target"].notna()].copy()
    df["target"] = (df["target"] > 0).astype(int)

    # 6) Impute missing feature values with column median
    feature_cols = [c for c in expected if c != "target"]
    medians = df[feature_cols].median(numeric_only=True)
    df[feature_cols] = df[feature_cols].fillna(medians)

    # (Optional) Warn if NaNs remain (e.g., entirely empty column)
    remaining_nan = df[feature_cols].isna().sum().sum()
    if remaining_nan > 0:
        print(f"Warning: {remaining_nan} NaN values remain after imputation (possibly an entirely empty column).")

    # 7) Save cleaned dataset
    df.to_csv(output_csv_path, index=False)
    print(f"Saved: {output_csv_path} | Shape: {df.shape}")

    return df

# Usage:
df_clean = preprocess_heart_csv(
    "cleveland_hungarian_long-beach-va_switzerland.csv",
    "heart_merged_clean.csv"
)

Saved: heart_merged_clean.csv | Shape: (920, 14)

**Dataset characteristics before preprocessing**

In [ ]:
# ============================================================
# 900x900 figures for the PRE-PROCESSING stage (raw CSV)
# - File: cleveland_hungarian_long-beach-va_switzerland.csv
# - Converts values like '?' to NaN and strips column names
# - NO TRANSFORMATION / NO IMPUTATION (no median fill)
# - 900x900 px (dpi=150 -> 6x6 inches)
# - Outputs are saved under ./figures_raw_900/ (PNG)
# ============================================================

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


def load_raw_heart_csv(raw_csv_path: str) -> pd.DataFrame:
    """Loads the raw file without preprocessing (only NaN parsing + column trimming)."""
    df = pd.read_csv(
        raw_csv_path,
        na_values=["?", "??", "???", "????", " ?"],
        skipinitialspace=True,
        engine="python"
    )
    df.columns = [c.strip() for c in df.columns]
    return df


def _save_900(fig, out_path: str, dpi: int = 150):
    # 900px = 6 inches * 150 dpi
    fig.set_size_inches(6, 6, forward=True)
    fig.tight_layout()
    fig.savefig(out_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)


def make_peerj_figures_raw_900(
    raw_csv_path: str = "cleveland_hungarian_long-beach-va_switzerland.csv",
    target_col: str = "target",
    out_dir: str = "figures_raw_900"
):
    os.makedirs(out_dir, exist_ok=True)
    df_raw = load_raw_heart_csv(raw_csv_path)

    # Expected columns (use these if present; otherwise continue with existing columns)
    expected = ["age","sex","cp","trestbps","chol","fbs","restecg","thalach","exang","oldpeak","slope","ca","thal","target"]
    cols = [c for c in expected if c in df_raw.columns]
    if not cols:
        cols = list(df_raw.columns)

    # For numeric plots (raw data -> cast to numeric only; NO IMPUTATION)
    df_num = df_raw.copy()
    for c in cols:
        df_num[c] = pd.to_numeric(df_num[c], errors="coerce")

    feature_cols = [c for c in cols if c != target_col and c in df_num.columns]

    # ========================================================
    # FIG-R1: Missing value counts per column (raw data)
    # ========================================================
    fig, ax = plt.subplots()
    nan_counts = df_num[cols].isna().sum().sort_values(ascending=False)
    ax.bar(nan_counts.index.astype(str), nan_counts.values)
    ax.set_title("Raw Data: Missing Values per Column")
    ax.set_xlabel("Column")
    ax.set_ylabel("Missing count")
    ax.tick_params(axis="x", rotation=90)
    _save_900(fig, os.path.join(out_dir, "FigR1_raw_missing_values_900.png"))

    # ========================================================
    # FIG-R2: Data type summary (numeric/object) + non-null counts
    # (Treat this as a reporting figure since raw data may contain strings)
    # ========================================================
    fig, ax = plt.subplots()
    non_null = df_raw[cols].notna().sum().sort_values(ascending=False)
    ax.bar(non_null.index.astype(str), non_null.values)
    ax.set_title("Raw Data: Non-null Counts per Column")
    ax.set_xlabel("Column")
    ax.set_ylabel("Non-null count")
    ax.tick_params(axis="x", rotation=90)
    _save_900(fig, os.path.join(out_dir, "FigR2_raw_nonnull_counts_900.png"))

    # ========================================================
    # FIG-R3: Raw target distribution (after numeric casting)
    # Note: raw target can be 0-4; NaNs remain as a separate group
    # ========================================================
    if target_col in df_num.columns:
        fig, ax = plt.subplots()
        t = df_num[target_col]
        # Show NaNs separately
        counts = t.value_counts(dropna=False).sort_index()
        labels = []
        values = []
        for idx, v in counts.items():
            if pd.isna(idx):
                labels.append("NaN")
            else:
                # If it's an integer, print it more cleanly
                labels.append(str(int(idx)) if float(idx).is_integer() else str(idx))
            values.append(int(v))

        ax.bar(labels, values)
        ax.set_title("Raw Data: Target Distribution (Original)")
        ax.set_xlabel("Target value")
        ax.set_ylabel("Count")
        for i, v in enumerate(values):
            ax.text(i, v, str(v), ha="center", va="bottom")
        _save_900(fig, os.path.join(out_dir, "FigR3_raw_target_distribution_900.png"))

    # ========================================================
    # FIG-R4: Feature completeness heatmap (row-wise completeness)
    # - No seaborn; uses matplotlib imshow
    # - Show only the first 200 rows (to avoid oversized figures)
    # ========================================================
    max_rows = 200
    show_cols = feature_cols[:13]  # 13 features is typical; if more, use the first 13
    if show_cols:
        mat = df_num[show_cols].notna().astype(int).head(max_rows).values  # 1=present, 0=missing
        fig, ax = plt.subplots()
        im = ax.imshow(mat, aspect="auto")
        ax.set_title(f"Raw Data: Feature Completeness (first {min(len(df_num), max_rows)} rows)")
        ax.set_xlabel("Feature")
        ax.set_ylabel("Row index")
        ax.set_xticks(range(len(show_cols)))
        ax.set_xticklabels([str(c) for c in show_cols], rotation=90)
        fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
        _save_900(fig, os.path.join(out_dir, "FigR4_raw_completeness_heatmap_900.png"))

    # ========================================================
    # FIG-R5: Raw numeric distributions (boxplot) - NaNs are dropped automatically
    # - Still provides intuition even if many NaNs exist
    # ========================================================
    if feature_cols:
        # If there are too many features, boxplot becomes cluttered: limit to the first 13
        fcols = feature_cols[:13]
        plot_data = [df_num[c].dropna().values for c in fcols]

        fig, ax = plt.subplots()
        ax.boxplot(plot_data, showfliers=False)
        ax.set_title("Raw Data: Feature Distributions (Boxplot)")
        ax.set_xlabel("Feature")
        ax.set_ylabel("Value")
        ax.set_xticks(range(1, len(fcols) + 1))
        ax.set_xticklabels([str(c) for c in fcols], rotation=90)
        _save_900(fig, os.path.join(out_dir, "FigR5_raw_boxplot_900.png"))

    # ========================================================
    # FIG-R6: Correlation (raw numeric)
    # - pandas corr computes pairwise correlations and handles NaNs pairwise
    # ========================================================
    if feature_cols and target_col in df_num.columns:
        corr = df_num[feature_cols + [target_col]].corr(numeric_only=True)

        fig, ax = plt.subplots()
        im = ax.imshow(corr.values, aspect="auto")
        ax.set_title("Raw Data: Correlation Matrix (Numeric Only)")

        ax.set_xticks(range(corr.shape[1]))
        ax.set_yticks(range(corr.shape[0]))
        ax.set_xticklabels(corr.columns.astype(str), rotation=90)
        ax.set_yticklabels(corr.index.astype(str))
        fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
        _save_900(fig, os.path.join(out_dir, "FigR6_raw_correlation_matrix_900.png"))

    print(f"\nDone. Raw 900x900 figures saved to: ./{out_dir}/")
    print("Generated files:")
    for fn in sorted(os.listdir(out_dir)):
        if fn.lower().endswith(".png"):
            print(" -", fn)


# ----------------- Run -----------------
make_peerj_figures_raw_900(
    raw_csv_path="cleveland_hungarian_long-beach-va_switzerland.csv",
    target_col="target",
    out_dir="figures_raw_900"
)

Done. Raw 900x900 figures saved to: ./figures_raw_900/
Generated files:
 - FigR1_raw_missing_values_900.png
 - FigR2_raw_nonnull_counts_900.png
 - FigR3_raw_target_distribution_900.png
 - FigR4_raw_completeness_heatmap_900.png
 - FigR5_raw_boxplot_900.png
 - FigR6_raw_correlation_matrix_900.png

**Characteristics of the preprocessed dataset**

In [ ]:
# ============================================================
# 900x900 figures (based on dataset characteristics)
# - 900x900 px (dpi=150 -> 6x6 inches)
# - Matplotlib (default)
# - Outputs saved under ./figures_900/ (PNG)
# ============================================================

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# ---------- 900x900 figure saver ----------
def _save_900(fig, out_path: str, dpi: int = 150):
    # 900px = 6 inches * 150 dpi
    fig.set_size_inches(6, 6, forward=True)
    fig.tight_layout()
    fig.savefig(out_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)


def make_peerj_figures_900(
    clean_csv_path: str = "heart_merged_clean.csv",
    target_col: str = "target",
    out_dir: str = "figures_900"
):
    os.makedirs(out_dir, exist_ok=True)
    df = pd.read_csv(clean_csv_path)

    # safety: ensure target column is integer
    df[target_col] = df[target_col].astype(int)

    feature_cols = [c for c in df.columns if c != target_col]

    # ========================================================
    # FIG-1: Target distribution (class balance)
    # ========================================================
    fig, ax = plt.subplots()
    counts = df[target_col].value_counts().sort_index()
    ax.bar([str(i) for i in counts.index], counts.values)
    ax.set_title("Target Class Distribution")
    ax.set_xlabel("Class (target)")
    ax.set_ylabel("Count")
    for i, v in enumerate(counts.values):
        ax.text(i, v, str(v), ha="center", va="bottom")
    _save_900(fig, os.path.join(out_dir, "Fig1_target_distribution_900.png"))

    # ========================================================
    # FIG-2: Missing value counts per feature
    # (useful for comparison with preprocessed data)
    # Note: clean_csv may already be imputed, but still informative
    # ========================================================
    fig, ax = plt.subplots()
    nan_counts = df[feature_cols].isna().sum().sort_values(ascending=False)
    ax.bar(nan_counts.index.astype(str), nan_counts.values)
    ax.set_title("Missing Values per Feature")
    ax.set_xlabel("Feature")
    ax.set_ylabel("Missing count")
    ax.tick_params(axis="x", rotation=90)
    _save_900(fig, os.path.join(out_dir, "Fig2_missing_values_900.png"))

    # ========================================================
    # FIG-3: Feature distributions (boxplot by target class)
    # ========================================================
    fig, ax = plt.subplots()

    # separate boxplots for target=0 and target=1
    data0 = df[df[target_col] == 0][feature_cols]
    data1 = df[df[target_col] == 1][feature_cols]

    # boxplot layout: [feat0_class0, feat0_class1, feat1_class0, feat1_class1, ...]
    plot_data = []
    positions = []
    labels = []
    pos = 1

    for f in feature_cols:
        plot_data.append(data0[f].values)
        plot_data.append(data1[f].values)
        positions.extend([pos, pos + 0.35])
        labels.append(f)
        pos += 1

    ax.boxplot(plot_data, positions=positions, widths=0.25, showfliers=False)
    ax.set_title("Feature Distributions by Target (Boxplot)")
    ax.set_xlabel("Feature (pairs: 0 then 1)")
    ax.set_ylabel("Value")
    ax.set_xticks([i + 0.175 for i in range(1, len(feature_cols) + 1)])
    ax.set_xticklabels([str(f) for f in feature_cols], rotation=90)

    # explanatory note
    ax.text(
        0.02, 0.98,
        "Each feature has two boxes: target=0 (left), target=1 (right)",
        transform=ax.transAxes,
        ha="left",
        va="top"
    )

    _save_900(fig, os.path.join(out_dir, "Fig3_boxplot_by_target_900.png"))

    # ========================================================
    # FIG-4: Correlation heatmap (Pearson)
    # - Uses matplotlib imshow (no seaborn)
    # ========================================================
    corr = df[feature_cols + [target_col]].corr(numeric_only=True)

    fig, ax = plt.subplots()
    im = ax.imshow(corr.values, aspect="auto")
    ax.set_title("Correlation Matrix (Pearson)")

    ax.set_xticks(range(corr.shape[1]))
    ax.set_yticks(range(corr.shape[0]))
    ax.set_xticklabels(corr.columns.astype(str), rotation=90)
    ax.set_yticklabels(corr.index.astype(str))

    # colorbar
    fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)

    # optionally annotate correlation values (can be cluttered)
    # for i in range(corr.shape[0]):
    #     for j in range(corr.shape[1]):
    #         ax.text(j, i, f"{corr.values[i,j]:.2f}", ha="center", va="center", fontsize=6)

    _save_900(fig, os.path.join(out_dir, "Fig4_correlation_matrix_900.png"))

    # ========================================================
    # FIG-5: Two clinically informative features: age vs thalach
    # - Often illustrative; can be replaced if desired
    # ========================================================
    x_col, y_col = "age", "thalach"

    if x_col in df.columns and y_col in df.columns:
        fig, ax = plt.subplots()

        df0 = df[df[target_col] == 0]
        df1 = df[df[target_col] == 1]

        ax.scatter(df0[x_col], df0[y_col], label="target=0", alpha=0.8)
        ax.scatter(df1[x_col], df1[y_col], label="target=1", alpha=0.8)

        ax.set_title(f"{x_col} vs {y_col} by Target")
        ax.set_xlabel(x_col)
        ax.set_ylabel(y_col)
        ax.legend()

        _save_900(fig, os.path.join(out_dir, "Fig5_scatter_age_thalach_900.png"))

    print(f"\nDone. 900x900 figures saved to: ./{out_dir}/")
    print("Generated files:")

    for fn in sorted(os.listdir(out_dir)):
        if fn.lower().endswith(".png"):
            print(" -", fn)


# ----------------- Run -----------------
# 1) Preprocess (generate cleaned CSV from raw file)
df_clean = preprocess_heart_csv(
    "cleveland_hungarian_long-beach-va_switzerland.csv",
    "heart_merged_clean.csv"
)

# 2) Generate 900x900 figures
make_peerj_figures_900(
    clean_csv_path="heart_merged_clean.csv",
    target_col="target",
    out_dir="figures_900"
)

Saved: heart_merged_clean.csv | Shape: (920, 14)

Done. 900x900 figures saved to: ./figures_900/
Generated files:
 - Fig1_target_distribution_900.png
 - Fig2_missing_values_900.png
 - Fig3_boxplot_by_target_900.png
 - Fig4_correlation_matrix_900.png
 - Fig5_scatter_age_thalach_900.png

In [4]:
pip freeze | egrep "scikit|xgboost|lightgbm|catboost|mljar|flaml|numpy|pandas"

geopandas==1.1.3
lightgbm==4.6.0
numpy==2.0.2
pandas==2.2.2
pandas-datareader==0.10.0
pandas-gbq==0.30.0
pandas-stubs==2.2.2.240909
scikit-image==0.25.2
scikit-learn==1.6.1
sklearn-pandas==2.2.0
xgboost==3.2.0

In [ ]:
# ============================================================
# Figure 3: End-to-end experimental workflow (900x900 px)
# - PeerJ-friendly: 900x900 (dpi=150 -> 6x6 inch)
# - Uses matplotlib patches (no seaborn)
# - Output: ./figures_900/Fig3_workflow_900.png
# ============================================================

import os
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch

def _save_900(fig, out_path: str, dpi: int = 150):
    fig.set_size_inches(6, 6, forward=True)  # 6*150=900 px
    fig.tight_layout()
    fig.savefig(out_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)

def _box(ax, xy, w, h, text, fontsize=9):
    x, y = xy
    patch = FancyBboxPatch(
        (x, y), w, h,
        boxstyle="round,pad=0.02,rounding_size=0.02",
        linewidth=1.2,
        facecolor="white"
    )
    ax.add_patch(patch)
    ax.text(x + w/2, y + h/2, text, ha="center", va="center", fontsize=fontsize)
    return patch

def _arrow(ax, p1, p2):
    ax.add_patch(FancyArrowPatch(
        p1, p2, arrowstyle="->", mutation_scale=12, linewidth=1.2
    ))

def make_fig3_workflow(out_dir="figures_900"):
    os.makedirs(out_dir, exist_ok=True)

    fig, ax = plt.subplots()
    ax.set_axis_off()
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)

    # Layout (normalized coordinates)
    W, H = 0.82, 0.10
    X = 0.09

    b1 = _box(ax, (X, 0.86), W, H, "Raw merged CSV\n(Cleveland + Hungary + Switzerland + VA Long Beach)")
    b2 = _box(ax, (X, 0.72), W, H, "Unified preprocessing\n(“?”→NaN, numeric casting, target binarization,\nmedian imputation for features)")
    b3 = _box(ax, (X, 0.58), W, H, "Stratified split\nOuter: Train/Test\nInner: Train/Val (early stopping / selection)")
    b4 = _box(ax, (X, 0.44), W, H, "Train (two comparable regimes)\nML: Light vs Full\nDL: Light vs Full\nAutoML: Light vs Full")
    b5 = _box(ax, (X, 0.30), W, H, "Evaluate on held-out test set\nAccuracy, AUC, F1, Precision, Recall, LogLoss,\nConfusion Matrix")
    b6 = _box(ax, (X, 0.16), W, H, "Resource logging\nRuntime (wall-clock), RAM (process RSS & system delta),\nModel size (serialized file MB)")
    b7 = _box(ax, (X, 0.02), W, H, "Report results\nTables/Figures + exact configs for reproducibility")

    # Arrows (center-bottom to center-top)
    def mid_bottom(box):  # (x,y,w,h) from patch
        x, y = box.get_x(), box.get_y()
        w, h = box.get_width(), box.get_height()
        return (x + w/2, y)
    def mid_top(box):
        x, y = box.get_x(), box.get_y()
        w, h = box.get_width(), box.get_height()
        return (x + w/2, y + h)

    for a, b in [(b1, b2), (b2, b3), (b3, b4), (b4, b5), (b5, b6), (b6, b7)]:
        _arrow(ax, mid_bottom(a), mid_top(b))

    ax.set_title("Figure 3. End-to-end experimental workflow", fontsize=11)

    out_path = os.path.join(out_dir, "Fig3_workflow_900.png")
    _save_900(fig, out_path)
    print("Saved:", out_path)

# Run
make_fig3_workflow(out_dir="figures_900")

Saved: figures_900/Fig3_workflow_900.png

In [ ]:
# ============================================================
# Figure 3: End-to-end experimental workflow (900x900 px)
# - PeerJ-friendly: 900x900 (dpi=150 -> 6x6 inch)
# - Uses matplotlib patches (no seaborn)
# - Output: ./figures_900/Fig3_workflow_900.png
# ============================================================

import os
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch

def _save_900(fig, out_path: str, dpi: int = 150):
    fig.set_size_inches(6, 6, forward=True)  # 6*150=900 px
    fig.tight_layout()
    fig.savefig(out_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)

def _box(ax, xy, w, h, text, fontsize=9):
    x, y = xy
    patch = FancyBboxPatch(
        (x, y), w, h,
        boxstyle="round,pad=0.02,rounding_size=0.02",
        linewidth=1.2,
        facecolor="white"
    )
    ax.add_patch(patch)
    ax.text(x + w/2, y + h/2, text, ha="center", va="center", fontsize=fontsize)
    return patch

def _arrow(ax, p1, p2):
    ax.add_patch(FancyArrowPatch(
        p1, p2, arrowstyle="->", mutation_scale=12, linewidth=1.2
    ))

def make_fig3_workflow(out_dir="figures_900"):
    os.makedirs(out_dir, exist_ok=True)

    fig, ax = plt.subplots()
    ax.set_axis_off()
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)

    # Layout (normalized coordinates)
    W, H = 0.82, 0.10
    X = 0.09

    b1 = _box(ax, (X, 0.86), W, H, "Raw merged CSV\n(Cleveland + Hungary + Switzerland + VA Long Beach)")
    b2 = _box(ax, (X, 0.72), W, H, "Unified preprocessing\n(“?”→NaN, numeric casting, target binarization,\nmedian imputation for features)")
    b3 = _box(ax, (X, 0.58), W, H, "Stratified split\nOuter: Train/Test\nInner: Train/Val (early stopping / selection)")
    b4 = _box(ax, (X, 0.44), W, H, "Train (two comparable regimes)\nML: Light vs Full\nDL: Light vs Full\nAutoML: Light vs Full")
    b5 = _box(ax, (X, 0.30), W, H, "Evaluate on held-out test set\nAccuracy, AUC, F1, Precision, Recall, LogLoss,\nConfusion Matrix")
    b6 = _box(ax, (X, 0.16), W, H, "Resource logging\nRuntime (wall-clock), RAM (process RSS & system delta),\nModel size (serialized file MB)")
    b7 = _box(ax, (X, 0.02), W, H, "Report results\nTables/Figures + exact configs for reproducibility")

    # Arrows (center-bottom to center-top)
    def mid_bottom(box):  # (x,y,w,h) from patch
        x, y = box.get_x(), box.get_y()
        w, h = box.get_width(), box.get_height()
        return (x + w/2, y)
    def mid_top(box):
        x, y = box.get_x(), box.get_y()
        w, h = box.get_width(), box.get_height()
        return (x + w/2, y + h)

    for a, b in [(b1, b2), (b2, b3), (b3, b4), (b4, b5), (b5, b6), (b6, b7)]:
        _arrow(ax, mid_bottom(a), mid_top(b))

    ax.set_title("Figure 3. End-to-end experimental workflow", fontsize=11)

    out_path = os.path.join(out_dir, "Fig3_workflow_900.png")
    _save_900(fig, out_path)
    print("Saved:", out_path)

# Run
make_fig3_workflow(out_dir="figures_900")

Saved: figures_900/Fig3_workflow_900.png

In [2]:
%pip install mljar-supervised

Collecting mljar-supervised
  Downloading mljar_supervised-1.2.2-py3-none-any.whl.metadata (27 kB)
Requirement already satisfied: numpy<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from mljar-supervised) (2.0.2)
Requirement already satisfied: pandas>=2.2.2 in /usr/local/lib/python3.12/dist-packages (from mljar-supervised) (2.2.2)
Requirement already satisfied: scipy>=1.13.1 in /usr/local/lib/python3.12/dist-packages (from mljar-supervised) (1.16.3)
Requirement already satisfied: scikit-learn>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from mljar-supervised) (1.6.1)
Requirement already satisfied: xgboost>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from mljar-supervised) (3.2.0)
Requirement already satisfied: lightgbm>=4.3.0 in /usr/local/lib/python3.12/dist-packages (from mljar-supervised) (4.6.0)
Collecting catboost>=1.2.8 (from mljar-supervised)
  Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: joblib>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from mljar-supervised) (1.5.3)
Requirement already satisfied: tabulate>=0.8.7 in /usr/local/lib/python3.12/dist-packages (from mljar-supervised) (0.9.0)
Requirement already satisfied: matplotlib>=3.8.4 in /usr/local/lib/python3.12/dist-packages (from mljar-supervised) (3.10.0)
Collecting dtreeviz>=2.2.2 (from mljar-supervised)
  Downloading dtreeviz-2.3.2-py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: shap>=0.46.0 in /usr/local/lib/python3.12/dist-packages (from mljar-supervised) (0.51.0)
Requirement already satisfied: seaborn>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from mljar-supervised) (0.13.2)
Collecting optuna-integration>=3.6.0 (from mljar-supervised)
  Downloading optuna_integration-4.8.0-py3-none-any.whl.metadata (13 kB)
Collecting mljar-scikit-plot>=0.3.11 (from mljar-supervised)
  Downloading mljar-scikit-plot-0.3.12.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: markdown in /usr/local/lib/python3.12/dist-packages (from mljar-supervised) (3.10.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from mljar-supervised) (4.15.0)
Requirement already satisfied: ipython in /usr/local/lib/python3.12/dist-packages (from mljar-supervised) (7.34.0)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost>=1.2.8->mljar-supervised) (0.21)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost>=1.2.8->mljar-supervised) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost>=1.2.8->mljar-supervised) (1.17.0)
Collecting colour (from dtreeviz>=2.2.2->mljar-supervised)
  Downloading colour-0.1.5-py2.py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8.4->mljar-supervised) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8.4->mljar-supervised) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8.4->mljar-supervised) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8.4->mljar-supervised) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8.4->mljar-supervised) (26.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8.4->mljar-supervised) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8.4->mljar-supervised) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8.4->mljar-supervised) (2.9.0.post0)
Collecting optuna (from optuna-integration>=3.6.0->mljar-supervised)
  Downloading optuna-4.8.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.2->mljar-supervised) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.2->mljar-supervised) (2026.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.5.0->mljar-supervised) (3.6.0)
Requirement already satisfied: tqdm>=4.27.0 in /usr/local/lib/python3.12/dist-packages (from shap>=0.46.0->mljar-supervised) (4.67.3)
Requirement already satisfied: slicer==0.0.8 in /usr/local/lib/python3.12/dist-packages (from shap>=0.46.0->mljar-supervised) (0.0.8)
Requirement already satisfied: numba in /usr/local/lib/python3.12/dist-packages (from shap>=0.46.0->mljar-supervised) (0.60.0)
Requirement already satisfied: llvmlite in /usr/local/lib/python3.12/dist-packages (from shap>=0.46.0->mljar-supervised) (0.43.0)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from shap>=0.46.0->mljar-supervised) (3.1.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost>=2.1.0->mljar-supervised) (2.30.4)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from ipython->mljar-supervised) (75.2.0)
Collecting jedi>=0.16 (from ipython->mljar-supervised)
  Downloading jedi-0.20.0-py2.py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython->mljar-supervised) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython->mljar-supervised) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.12/dist-packages (from ipython->mljar-supervised) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython->mljar-supervised) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython->mljar-supervised) (2.20.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython->mljar-supervised) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.12/dist-packages (from ipython->mljar-supervised) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython->mljar-supervised) (4.9.0)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython->mljar-supervised) (0.8.6)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->ipython->mljar-supervised) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->mljar-supervised) (0.6.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration>=3.6.0->mljar-supervised) (1.18.4)
Collecting colorlog (from optuna->optuna-integration>=3.6.0->mljar-supervised)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration>=3.6.0->mljar-supervised) (2.0.49)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration>=3.6.0->mljar-supervised) (6.0.3)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost>=1.2.8->mljar-supervised) (9.1.4)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->optuna-integration>=3.6.0->mljar-supervised) (1.3.11)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna->optuna-integration>=3.6.0->mljar-supervised) (3.4.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna->optuna-integration>=3.6.0->mljar-supervised) (3.0.3)
Downloading mljar_supervised-1.2.2-py3-none-any.whl (169 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 169.6/169.6 kB 2.2 MB/s eta 0:00:00
Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 8.7 MB/s eta 0:00:00
Downloading dtreeviz-2.3.2-py3-none-any.whl (102 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.3/102.3 kB 9.0 MB/s eta 0:00:00
Downloading optuna_integration-4.8.0-py3-none-any.whl (103 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.2/103.2 kB 7.7 MB/s eta 0:00:00
Downloading jedi-0.20.0-py2.py3-none-any.whl (4.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 70.6 MB/s eta 0:00:00
Downloading colour-0.1.5-py2.py3-none-any.whl (23 kB)
Downloading optuna-4.8.0-py3-none-any.whl (419 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 419.5/419.5 kB 32.9 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Building wheels for collected packages: mljar-scikit-plot
  Building wheel for mljar-scikit-plot (setup.py) ... done
  Created wheel for mljar-scikit-plot: filename=mljar_scikit_plot-0.3.12-py3-none-any.whl size=32014 sha256=e4bfaab37716f097a0d3a2440eba80b3fe3632d4d91d757b5eac2c2415c2946c
  Stored in directory: /root/.cache/pip/wheels/24/e5/1e/3b952f43ebd4bd0a6983c835daa4e226f2eeee4080e5b1ceb9
Successfully built mljar-scikit-plot
Installing collected packages: colour, jedi, colorlog, optuna, mljar-scikit-plot, dtreeviz, catboost, optuna-integration, mljar-supervised
Successfully installed catboost-1.2.10 colorlog-6.10.1 colour-0.1.5 dtreeviz-2.3.2 jedi-0.20.0 mljar-scikit-plot-0.3.12 mljar-supervised-1.2.2 optuna-4.8.0 optuna-integration-4.8.0

**MLJAR FULL**

In [ ]:
# -*- coding: utf-8 -*-
"""mljar_heart_full.py"""

import logging
logging.getLogger("matplotlib.font_manager").setLevel(logging.ERROR)

import os
import time
import psutil
import joblib
import pandas as pd
from supervised.automl import AutoML
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score, roc_auc_score, f1_score,
    precision_score, recall_score, log_loss, confusion_matrix
)

# import matplotlib.pyplot as plt
# plt.rcParams['font.family'] = 'sans-serif']
import numpy as np  # Import numpy for np.unique

# === System RAM measurement function ===
def get_system_ram():
    mem = psutil.virtual_memory()
    total = mem.total / (1024**3)
    used = mem.used / (1024**3)
    free = mem.available / (1024**3)
    percent = mem.percent
    return total, used, free, percent

# === Initial measurements ===
process = psutil.Process(os.getpid())
start_proc_mem = process.memory_info().rss / (1024 * 1024)  # MB
start_sys_total, start_sys_used, start_sys_free, start_sys_percent = get_system_ram()
start_time = time.time()

# 1. Load dataset
data = pd.read_csv("heart_merged_clean.csv")
target_col = "target"
X = data.drop(columns=[target_col])
y = data[target_col]

# 2. Train/Test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 3. MLJAR AutoML configuration (full/Compete mode)
automl = AutoML(
    mode="Compete",
    algorithms=[
        "LightGBM", "Xgboost", "CatBoost",
        "Random Forest", "Extra Trees", "Neural Network"
    ],
    total_time_limit=180,
    model_time_limit=100,
    start_random_models=5,
    hill_climbing_steps=3,
    stack_models=True,
    golden_features=True,
    features_selection=True,
    explain_level=2,
    random_state=42,
)

# 4. Train model
automl.fit(X_train, y_train)

# 5. Test predictions
y_pred = automl.predict(X_test)
y_pred_proba = automl.predict_proba(X_test)[:, 1]

# 6. Performance metrics
acc = accuracy_score(y_test, y_pred)
auc = roc_auc_score(y_test, y_pred_proba)
f1 = f1_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
ll = log_loss(y_test, y_pred_proba)
cm = confusion_matrix(y_test, y_pred)

# === Final measurements ===
end_time = time.time()
end_proc_mem = process.memory_info().rss / (1024 * 1024)
end_sys_total, end_sys_used, end_sys_free, end_sys_percent = get_system_ram()

runtime = end_time - start_time
proc_mem_usage = end_proc_mem - start_proc_mem
sys_used_diff = end_sys_used - start_sys_used

# === Best model file size (via joblib) ===
best_model = automl._best_model  # Best model object inside MLJAR
best_model_file = "mljar_heart_full_best_model.pkl"
joblib.dump(best_model, best_model_file)
model_size_mb = os.path.getsize(best_model_file) / (1024 * 1024)

# === Results ===
print("\n=== MLJAR Full (Compete) Model Performance (Test) ===")
print(f"Accuracy:  {acc*100:.2f}%")
print(f"AUC:       {auc*100:.2f}%")
print(f"F1 Score:  {f1*100:.2f}%")
print(f"Precision: {precision*100:.2f}%")
print(f"Recall:    {recall*100:.2f}%")
print(f"LogLoss:   {ll:.2f}")

print("\nConfusion Matrix:")
print(cm)

print("\n=== Summary ===")
print(f"Runtime: {runtime:.2f} seconds")
print(f"Python process RAM usage: {proc_mem_usage:.2f} MB")

print("\n=== System RAM Usage ===")
print(f"Total RAM:         {end_sys_total:.2f} GB")
print(f"Used RAM:          {end_sys_used:.2f} GB")
print(f"Available RAM:     {end_sys_free:.2f} GB")
print(f"RAM utilization:   {end_sys_percent:.1f}%")
print(f"RAM increase during run: {sys_used_diff:.2f} GB")

print("\n=== Best Model Information ===")
print(f"Best model type: {type(best_model).__name__}")
print(f"Model file: {best_model_file}")
print(f"Model size: {model_size_mb:.2f} MB")

# 9. Leaderboard
leaderboard = automl.get_leaderboard()
print("\n=== Leaderboard ===")
print(leaderboard.round(2))

import gc
del automl
gc.collect()
time.sleep(2)
end_proc_mem2 = process.memory_info().rss / (1024 * 1024)
print(f"\n[After GC] Python RSS: {end_proc_mem2:.2f} MB")

AutoML directory: AutoML_6
The task is binary_classification with evaluation metric logloss
AutoML will use algorithms: ['LightGBM', 'Xgboost', 'CatBoost', 'Random Forest', 'Extra Trees', 'Neural Network']
AutoML will stack models
AutoML will ensemble available models
AutoML steps: ['adjust_validation', 'simple_algorithms', 'default_algorithms', 'not_so_random', 'golden_features', 'kmeans_features', 'insert_random_feature', 'features_selection', 'hill_climbing_1', 'hill_climbing_2', 'hill_climbing_3', 'boost_on_errors', 'ensemble', 'stack', 'ensemble_stacked']
* Step adjust_validation will try to check up to 1 model
1_DecisionTree logloss 0.563773 trained in 30.32 seconds
Disable stacking for split validation
Skip simple_algorithms because no parameters were generated.
* Step default_algorithms will try to check up to 6 models
2_Default_LightGBM logloss 0.442757 trained in 10.68 seconds
3_Default_Xgboost logloss 0.448164 trained in 2.62 seconds
4_Default_CatBoost logloss 0.406628 trained in 3.35 seconds
5_Default_NeuralNetwork logloss 0.637231 trained in 2.76 seconds
6_Default_RandomForest logloss 0.463761 trained in 4.28 seconds
7_Default_ExtraTrees logloss 0.473989 trained in 5.64 seconds
* Step not_so_random will try to check up to 24 models
12_LightGBM logloss 0.397176 trained in 6.81 seconds
8_Xgboost logloss 0.411769 trained in 2.83 seconds
16_CatBoost logloss 0.38026 trained in 3.82 seconds
20_RandomForest logloss 0.465589 trained in 5.91 seconds
24_ExtraTrees logloss 0.448946 trained in 4.45 seconds
28_NeuralNetwork logloss 0.462431 trained in 2.82 seconds
13_LightGBM logloss 0.446692 trained in 6.13 seconds
9_Xgboost logloss 0.499219 trained in 4.38 seconds
17_CatBoost logloss 0.387589 trained in 2.82 seconds
21_RandomForest logloss 0.505295 trained in 5.01 seconds
25_ExtraTrees logloss 0.511873 trained in 4.85 seconds
29_NeuralNetwork logloss 2.182454 trained in 4.07 seconds
14_LightGBM logloss 0.43574 trained in 5.82 seconds
10_Xgboost logloss 0.41053 trained in 3.35 seconds
18_CatBoost logloss 0.394309 trained in 3.86 seconds
22_RandomForest logloss 0.461873 trained in 4.84 seconds
26_ExtraTrees logloss 0.496611 trained in 5.59 seconds
30_NeuralNetwork logloss 0.418571 trained in 3.08 seconds
15_LightGBM logloss 0.45727 trained in 7.01 seconds
11_Xgboost logloss 0.415598 trained in 3.06 seconds
19_CatBoost logloss 0.396517 trained in 3.74 seconds
23_RandomForest logloss 0.452506 trained in 4.49 seconds
27_ExtraTrees logloss 0.471519 trained in 6.26 seconds
31_NeuralNetwork logloss 0.46602 trained in 3.14 seconds
Skip golden_features because of the time limit.
Skip kmeans_features because of the time limit.
Not enough time to perform features selection. Skip
Time needed for features selection ~ 42.0 seconds
Please increase total_time_limit to at least (483 seconds) to have features selection
Skip insert_random_feature because no parameters were generated.
Skip features_selection because no parameters were generated.
Skip hill_climbing_1 because of the time limit.
Skip hill_climbing_2 because of the time limit.
Skip hill_climbing_3 because of the time limit.
* Step ensemble will try to check up to 1 model
Ensemble logloss 0.378081 trained in 9.81 seconds
AutoML fit time: 266.81 seconds
AutoML best model: Ensemble

=== MLJAR Normal (Compete) Model Performansı (Test) ===
Accuracy:  81.52%
AUC:       92.64%
F1 Score:  85.47%
Precision: 75.76%
Recall:    98.04%
LogLoss:   0.35

Confusion Matrix:
[[ 50  32]
 [  2 100]]

=== Özet Bilgiler ===
Koşum Süresi: 266.96 saniye
Python İşlemi RAM Kullanımı: 1007.46 MB

=== Sistem Genel RAM Kullanımı ===
Toplam RAM:         12.67 GB
Kullanılan RAM:     3.10 GB
Boş RAM:            9.26 GB
RAM Kullanım Oranı: 26.9%
Koşum sırasında artan RAM: 1.38 GB

=== En İyi Model Bilgileri ===
En iyi model tipi: Ensemble
Model dosyası: mljar_heart_full_best_model.pkl
Model boyutu: 43.76 MB

=== Leaderboard ===
                       name      model_type metric_type  metric_value  \
0            1_DecisionTree   Decision Tree     logloss          0.56
1        2_Default_LightGBM        LightGBM     logloss          0.44
2         3_Default_Xgboost         Xgboost     logloss          0.45
3        4_Default_CatBoost        CatBoost     logloss          0.41
4   5_Default_NeuralNetwork  Neural Network     logloss          0.64
5    6_Default_RandomForest   Random Forest     logloss          0.46
6      7_Default_ExtraTrees     Extra Trees     logloss          0.47
7               12_LightGBM        LightGBM     logloss          0.40
8                 8_Xgboost         Xgboost     logloss          0.41
9               16_CatBoost        CatBoost     logloss          0.38
10          20_RandomForest   Random Forest     logloss          0.47
11            24_ExtraTrees     Extra Trees     logloss          0.45
12         28_NeuralNetwork  Neural Network     logloss          0.46
13              13_LightGBM        LightGBM     logloss          0.45
14                9_Xgboost         Xgboost     logloss          0.50
15              17_CatBoost        CatBoost     logloss          0.39
16          21_RandomForest   Random Forest     logloss          0.51
17            25_ExtraTrees     Extra Trees     logloss          0.51
18         29_NeuralNetwork  Neural Network     logloss          2.18
19              14_LightGBM        LightGBM     logloss          0.44
20               10_Xgboost         Xgboost     logloss          0.41
21              18_CatBoost        CatBoost     logloss          0.39
22          22_RandomForest   Random Forest     logloss          0.46
23            26_ExtraTrees     Extra Trees     logloss          0.50
24         30_NeuralNetwork  Neural Network     logloss          0.42
25              15_LightGBM        LightGBM     logloss          0.46
26               11_Xgboost         Xgboost     logloss          0.42
27              19_CatBoost        CatBoost     logloss          0.40
28          23_RandomForest   Random Forest     logloss          0.45
29            27_ExtraTrees     Extra Trees     logloss          0.47
30         31_NeuralNetwork  Neural Network     logloss          0.47
31                 Ensemble        Ensemble     logloss          0.38

    train_time
0        33.36
1        12.68
2         4.34
3         5.26
4         4.51
5         6.56
6         7.41
7         8.79
8         4.57
9         5.56
10        8.33
11        6.23
12        5.10
13        8.12
14        6.28
15        4.51
16        7.45
17        6.58
18        5.78
19        8.48
20        5.07
21        5.93
22        6.56
23        7.89
24        4.83
25        8.97
26        4.81
27        5.48
28        6.24
29        8.01
30        4.91
31        9.81

[GC sonrası] Python RSS: 1676.44 MB

**HAFİF MLJAR**

In [ ]:
# -*- coding: utf-8 -*-
"""mljar_heart_light.py"""

import logging
logging.getLogger("matplotlib.font_manager").setLevel(logging.ERROR)

import os
import time
import psutil
import joblib
import pandas as pd
from supervised.automl import AutoML
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score, roc_auc_score, f1_score,
    precision_score, recall_score, log_loss, confusion_matrix, classification_report
)

# === System RAM measurement function ===
def get_system_ram():
    mem = psutil.virtual_memory()
    total = mem.total / (1024**3)
    used = mem.used / (1024**3)
    free = mem.available / (1024**3)
    percent = mem.percent
    return total, used, free, percent

# === Initial measurements ===
process = psutil.Process(os.getpid())
start_proc_mem = process.memory_info().rss / (1024 * 1024)  # MB
start_sys_total, start_sys_used, start_sys_free, start_sys_percent = get_system_ram()
start_time = time.time()

# 1. Load dataset
data = pd.read_csv("heart_merged_clean.csv")
y = "target"
X = data.drop(columns=[y])
y_data = data[y]

# 2. Train/Test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y_data, test_size=0.2, random_state=42, stratify=y_data
)

# 3. MLJAR AutoML (lightweight) configuration
automl = AutoML(
    mode="Explain",   # lightweight and fast mode
    algorithms=["LightGBM", "Xgboost", "CatBoost", "Random Forest"],
    total_time_limit=60,
    explain_level=1,
    random_state=42,
    start_random_models=2,
    hill_climbing_steps=0,
)

# 4. Training
automl.fit(X_train, y_train)

# 5. Prediction
y_pred = automl.predict(X_test)
y_pred_proba = automl.predict_proba(X_test)[:, 1]

# 6. Performance metrics
acc = accuracy_score(y_test, y_pred)
auc = roc_auc_score(y_test, y_pred_proba)
f1 = f1_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
ll = log_loss(y_test, y_pred_proba)
cm = confusion_matrix(y_test, y_pred)

# === Final measurements ===
end_time = time.time()
end_proc_mem = process.memory_info().rss / (1024 * 1024)
end_sys_total, end_sys_used, end_sys_free, end_sys_percent = get_system_ram()

runtime = end_time - start_time
proc_mem_usage = end_proc_mem - start_proc_mem
sys_ram_diff = end_sys_used - start_sys_used

# === Best model file size (via joblib) ===
best_model = automl._best_model
best_model_file = "mljar_heart_light_best_model.pkl"
joblib.dump(best_model, best_model_file)
model_size_mb = os.path.getsize(best_model_file) / (1024 * 1024)

# 7. Results
print("\n=== MLJAR Lightweight Model Performance (Test) ===")
print(f"Accuracy:  {acc*100:.2f}%")
print(f"AUC:       {auc*100:.2f}%")
print(f"F1 Score:  {f1*100:.2f}%")
print(f"Precision: {precision*100:.2f}%")
print(f"Recall:    {recall*100:.2f}%")
print(f"LogLoss:   {ll:.2f}")

print("\nConfusion Matrix:")
print(cm)

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\n=== Summary ===")
print(f"Runtime: {runtime:.2f} seconds")
print(f"Python RAM increase: {proc_mem_usage:.2f} MB")

print("\n=== System RAM Usage ===")
print(f"Total RAM:         {end_sys_total:.2f} GB")
print(f"Used RAM:          {end_sys_used:.2f} GB")
print(f"Available RAM:     {end_sys_free:.2f} GB")
print(f"RAM utilization:   {end_sys_percent:.1f}%")
print(f"RAM increase during run: {sys_ram_diff:.2f} GB")

print("\n=== Best Model File ===")
print(f"Best model type: {type(best_model).__name__}")
print(f"Model path: {best_model_file}")
print(f"Model size: {model_size_mb:.4f} MB")

# 8. Leaderboard
leaderboard = automl.get_leaderboard()
print("\n=== Leaderboard ===")
print(leaderboard.round(2))

import gc
del automl
gc.collect()
time.sleep(2)
end_proc_mem2 = process.memory_info().rss / (1024 * 1024)
print(f"\n[After GC] Python RSS: {end_proc_mem2:.2f} MB")

AutoML directory: AutoML_4
The task is binary_classification with evaluation metric logloss
AutoML will use algorithms: ['LightGBM', 'Xgboost', 'CatBoost', 'Random Forest']
AutoML will ensemble available models
AutoML steps: ['simple_algorithms', 'default_algorithms', 'not_so_random', 'ensemble']
Skip simple_algorithms because no parameters were generated.
* Step default_algorithms will try to check up to 4 models
1_Default_LightGBM logloss 0.437943 trained in 10.57 seconds
2_Default_Xgboost logloss 0.422242 trained in 3.44 seconds
3_Default_CatBoost logloss 0.379302 trained in 3.45 seconds
4_Default_RandomForest logloss 0.455071 trained in 5.31 seconds
* Step not_so_random will try to check up to 4 models
6_LightGBM logloss 0.448126 trained in 11.76 seconds
5_Xgboost logloss 0.425763 trained in 8.93 seconds
* Step ensemble will try to check up to 1 model
Ensemble logloss 0.379302 trained in 5.36 seconds
AutoML fit time: 70.86 seconds
AutoML best model: 3_Default_CatBoost

=== MLJAR Hafif Model Performansı (Test) ===
Accuracy:  83.15%
AUC:       92.04%
F1 Score:  86.34%
Precision: 78.40%
Recall:    96.08%
LogLoss:   0.36

Confusion Matrix:
[[55 27]
 [ 4 98]]

Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.67      0.78        82
           1       0.78      0.96      0.86       102

    accuracy                           0.83       184
   macro avg       0.86      0.82      0.82       184
weighted avg       0.85      0.83      0.83       184


=== Özet Bilgiler ===
Koşum Süresi: 70.91 saniye
Python RAM Artışı: 189.38 MB

=== Sistem Genel RAM Kullanımı ===
Toplam RAM:         12.67 GB
Kullanılan RAM:     2.66 GB
Boş RAM:            9.70 GB
RAM Kullanım Oranı: 23.5%
Koşum sırasında artan RAM: 0.61 GB

=== En İyi Model Dosyası ===
En iyi model tipi: ModelFramework
Model yolu: mljar_heart_light_best_model.pkl
Model boyutu: 1.4848 MB

=== Leaderboard ===
                     name     model_type metric_type  metric_value  train_time
0      1_Default_LightGBM       LightGBM     logloss          0.44       12.87
1       2_Default_Xgboost        Xgboost     logloss          0.42        5.18
2      3_Default_CatBoost       CatBoost     logloss          0.38        5.79
3  4_Default_RandomForest  Random Forest     logloss          0.46        7.04
4              6_LightGBM       LightGBM     logloss          0.45       14.98
5               5_Xgboost        Xgboost     logloss          0.43       11.34
6                Ensemble       Ensemble     logloss          0.38        5.36

[GC sonrası] Python RSS: 871.89 MB

**FULL AUTOGLUON**

In [3]:
!pip install autogluon

Collecting autogluon
  Downloading autogluon-1.5.0-py3-none-any.whl.metadata (12 kB)
Collecting autogluon.core==1.5.0 (from autogluon.core[all]==1.5.0->autogluon)
  Downloading autogluon_core-1.5.0-py3-none-any.whl.metadata (13 kB)
Collecting autogluon.features==1.5.0 (from autogluon)
  Downloading autogluon_features-1.5.0-py3-none-any.whl.metadata (12 kB)
Collecting autogluon.tabular==1.5.0 (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading autogluon_tabular-1.5.0-py3-none-any.whl.metadata (16 kB)
Collecting autogluon.multimodal==1.5.0 (from autogluon)
  Downloading autogluon_multimodal-1.5.0-py3-none-any.whl.metadata (13 kB)
Collecting autogluon.timeseries==1.5.0 (from autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading autogluon_timeseries-1.5.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: numpy<2.4.0,>=1.25.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (2.0.2)
Requirement already satisfied: scipy<1.17,>=1.5.4 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (1.16.3)
Requirement already satisfied: scikit-learn<1.8.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (1.6.1)
Requirement already satisfied: networkx<4,>=3.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (3.6.1)
Requirement already satisfied: pandas<2.4.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (2.2.2)
Requirement already satisfied: tqdm<5,>=4.38 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (4.67.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (2.32.4)
Requirement already satisfied: matplotlib<3.11,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (3.10.0)
Collecting boto3<2,>=1.10 (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon)
  Downloading boto3-1.43.2-py3-none-any.whl.metadata (6.5 kB)
Collecting autogluon.common==1.5.0 (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon)
  Downloading autogluon_common-1.5.0-py3-none-any.whl.metadata (12 kB)
Collecting ray<2.53,>=2.43.0 (from ray[default,tune]<2.53,>=2.43.0; (platform_system != "Windows" or python_version != "3.13") and extra == "all"->autogluon.core[all]==1.5.0->autogluon)
  Downloading ray-2.52.1-cp312-cp312-manylinux2014_x86_64.whl.metadata (21 kB)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core[all]==1.5.0->autogluon) (18.1.0)
Requirement already satisfied: hyperopt<0.2.8,>=0.2.7 in /usr/local/lib/python3.12/dist-packages (from autogluon.core[all]==1.5.0->autogluon) (0.2.7)
Collecting stevedore<5.5 (from autogluon.core[all]==1.5.0->autogluon)
  Downloading stevedore-5.4.1-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: Pillow<12,>=10.0.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (11.3.0)
Collecting torch<2.10,>=2.6 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading torch-2.9.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (30 kB)
Collecting lightning<2.6,>=2.5.1 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading lightning-2.5.6-py3-none-any.whl.metadata (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.4/42.4 kB 2.3 MB/s eta 0:00:00
Collecting transformers<4.58,>=4.51.0 (from transformers[sentencepiece]<4.58,>=4.51.0->autogluon.multimodal==1.5.0->autogluon)
  Downloading transformers-4.57.6-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 1.6 MB/s eta 0:00:00
Requirement already satisfied: accelerate<2.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (1.13.0)
Requirement already satisfied: fsspec<=2025.3 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3->autogluon.multimodal==1.5.0->autogluon) (2025.3.0)
Collecting jsonschema<4.24,>=4.18 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading jsonschema-4.23.0-py3-none-any.whl.metadata (7.9 kB)
Collecting seqeval<1.3.0,>=1.2.2 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading seqeval-1.2.2.tar.gz (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 1.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting evaluate<0.5.0,>=0.4.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Collecting timm<1.0.7,>=0.9.5 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading timm-1.0.3-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 1.3 MB/s eta 0:00:00
Collecting torchvision<0.25.0,>=0.21.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading torchvision-0.24.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.9 kB)
Requirement already satisfied: scikit-image<0.26.0,>=0.19.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (0.25.2)
Requirement already satisfied: text-unidecode<1.4,>=1.3 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (1.3)
Collecting torchmetrics<1.8,>=1.2.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading torchmetrics-1.7.4-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: omegaconf<2.4.0,>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (2.3.0)
Collecting pytorch-metric-learning<2.9,>=1.3.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading pytorch_metric_learning-2.8.1-py3-none-any.whl.metadata (18 kB)
Collecting nlpaug<1.2.0,>=1.1.10 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading nlpaug-1.1.11-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: nltk<3.10,>=3.4.5 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (3.9.1)
Collecting openmim<0.4.0,>=0.3.7 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading openmim-0.3.9-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: defusedxml<0.7.2,>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (0.7.1)
Requirement already satisfied: jinja2<3.2,>=3.0.3 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (3.1.6)
Requirement already satisfied: tensorboard<3,>=2.9 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (2.20.0)
Collecting pytesseract<0.4,>=0.3.9 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading pytesseract-0.3.13-py3-none-any.whl.metadata (11 kB)
Collecting nvidia-ml-py3<8.0,>=7.352.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading nvidia-ml-py3-7.352.0.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Collecting pdf2image<1.19,>=1.17.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading pdf2image-1.17.0-py3-none-any.whl.metadata (6.2 kB)
Collecting einx (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading einx-0.4.3-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: lightgbm<4.7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]==1.5.0->autogluon) (4.6.0)
Collecting huggingface_hub<1.0 (from huggingface_hub[torch]<1.0; extra == "all"->autogluon.tabular[all]==1.5.0->autogluon)
  Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Collecting xgboost<3.2,>=2.0 (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading xgboost-3.1.3-py3-none-manylinux_2_28_x86_64.whl.metadata (2.0 kB)
Requirement already satisfied: catboost<1.3,>=1.2 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]==1.5.0->autogluon) (1.2.10)
Requirement already satisfied: fastai<2.9,>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]==1.5.0->autogluon) (2.8.7)
Collecting loguru (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading loguru-0.7.3-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: einops<0.9,>=0.7 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]==1.5.0->autogluon) (0.8.2)
Requirement already satisfied: spacy<3.9 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]==1.5.0->autogluon) (3.8.14)
Requirement already satisfied: joblib<1.7,>=1.2 in /usr/local/lib/python3.12/dist-packages (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (1.5.3)
Collecting gluonts<0.17,>=0.15.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading gluonts-0.16.2-py3-none-any.whl.metadata (9.8 kB)
Collecting statsforecast<2.0.2,>=1.7.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading statsforecast-2.0.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (29 kB)
Collecting mlforecast<0.15.0,>=0.14.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading mlforecast-0.14.0-py3-none-any.whl.metadata (12 kB)
Collecting utilsforecast<0.2.12,>=0.2.3 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading utilsforecast-0.2.11-py3-none-any.whl.metadata (7.7 kB)
Collecting coreforecast<0.0.17,>=0.0.12 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading coreforecast-0.0.16-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.7 kB)
Collecting fugue>=0.9.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading fugue-0.9.7-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: orjson~=3.9 in /usr/local/lib/python3.12/dist-packages (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (3.11.8)
Collecting chronos-forecasting<2.4,>=2.2.2 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading chronos_forecasting-2.2.2-py3-none-any.whl.metadata (23 kB)
Collecting peft<0.18,>=0.13.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading peft-0.17.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: psutil<7.2.0,>=5.7.3 in /usr/local/lib/python3.12/dist-packages (from autogluon.common==1.5.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (5.9.5)
Requirement already satisfied: pyyaml>=5.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.common==1.5.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (6.0.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from accelerate<2.0,>=0.34.0->autogluon.multimodal==1.5.0->autogluon) (26.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate<2.0,>=0.34.0->autogluon.multimodal==1.5.0->autogluon) (0.7.0)
Collecting botocore<1.44.0,>=1.43.2 (from boto3<2,>=1.10->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon)
  Downloading botocore-1.43.2-py3-none-any.whl.metadata (5.5 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3<2,>=1.10->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon)
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.18.0,>=0.17.0 (from boto3<2,>=1.10->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon)
  Downloading s3transfer-0.17.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost<1.3,>=1.2->autogluon.tabular[all]==1.5.0->autogluon) (0.21)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost<1.3,>=1.2->autogluon.tabular[all]==1.5.0->autogluon) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost<1.3,>=1.2->autogluon.tabular[all]==1.5.0->autogluon) (1.17.0)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.5.0->autogluon) (4.0.0)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.5.0->autogluon) (0.3.8)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.5.0->autogluon) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.5.0->autogluon) (0.70.16)
Requirement already satisfied: fastdownload<2,>=0.0.5 in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon) (0.0.7)
Requirement already satisfied: fastcore>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon) (1.12.42)
Requirement already satisfied: fasttransform>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon) (0.0.2)
Requirement already satisfied: fastprogress>=0.2.4 in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon) (1.1.5)
Requirement already satisfied: plum-dispatch in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon) (2.8.0)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon) (3.1.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3->autogluon.multimodal==1.5.0->autogluon) (3.13.5)
Collecting triad>=1.0.1 (from fugue>=0.9.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading triad-1.0.2-py3-none-any.whl.metadata (6.6 kB)
Collecting adagio>=0.2.6 (from fugue>=0.9.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading adagio-0.2.6-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: pydantic<3,>=1.7 in /usr/local/lib/python3.12/dist-packages (from gluonts<0.17,>=0.15.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (2.12.3)
Requirement already satisfied: toolz~=0.10 in /usr/local/lib/python3.12/dist-packages (from gluonts<0.17,>=0.15.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (0.12.1)
Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.12/dist-packages (from gluonts<0.17,>=0.15.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (4.15.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface_hub<1.0->huggingface_hub[torch]<1.0; extra == "all"->autogluon.tabular[all]==1.5.0->autogluon) (3.29.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub<1.0->huggingface_hub[torch]<1.0; extra == "all"->autogluon.tabular[all]==1.5.0->autogluon) (1.4.3)
Requirement already satisfied: future in /usr/local/lib/python3.12/dist-packages (from hyperopt<0.2.8,>=0.2.7->autogluon.core[all]==1.5.0->autogluon) (1.0.0)
Requirement already satisfied: py4j in /usr/local/lib/python3.12/dist-packages (from hyperopt<0.2.8,>=0.2.7->autogluon.core[all]==1.5.0->autogluon) (0.10.9.9)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<3.2,>=3.0.3->autogluon.multimodal==1.5.0->autogluon) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema<4.24,>=4.18->autogluon.multimodal==1.5.0->autogluon) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema<4.24,>=4.18->autogluon.multimodal==1.5.0->autogluon) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema<4.24,>=4.18->autogluon.multimodal==1.5.0->autogluon) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from jsonschema<4.24,>=4.18->autogluon.multimodal==1.5.0->autogluon) (0.30.0)
Collecting lightning-utilities<2.0,>=0.10.0 (from lightning<2.6,>=2.5.1->autogluon.multimodal==1.5.0->autogluon)
  Downloading lightning_utilities-0.15.3-py3-none-any.whl.metadata (5.5 kB)
Collecting pytorch-lightning (from lightning<2.6,>=2.5.1->autogluon.multimodal==1.5.0->autogluon)
  Downloading pytorch_lightning-2.6.1-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (1.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (2.9.0.post0)
Requirement already satisfied: numba in /usr/local/lib/python3.12/dist-packages (from mlforecast<0.15.0,>=0.14.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (0.60.0)
Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (from mlforecast<0.15.0,>=0.14.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (4.8.0)
Collecting window-ops (from mlforecast<0.15.0,>=0.14.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading window_ops-0.0.15-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: gdown>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from nlpaug<1.2.0,>=1.1.10->autogluon.multimodal==1.5.0->autogluon) (5.2.2)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk<3.10,>=3.4.5->autogluon.multimodal==1.5.0->autogluon) (8.3.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk<3.10,>=3.4.5->autogluon.multimodal==1.5.0->autogluon) (2025.11.3)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /usr/local/lib/python3.12/dist-packages (from omegaconf<2.4.0,>=2.1.1->autogluon.multimodal==1.5.0->autogluon) (4.9.3)
Collecting colorama (from openmim<0.4.0,>=0.3.7->autogluon.multimodal==1.5.0->autogluon)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting model-index (from openmim<0.4.0,>=0.3.7->autogluon.multimodal==1.5.0->autogluon)
  Downloading model_index-0.1.11-py3-none-any.whl.metadata (3.9 kB)
Collecting opendatalab (from openmim<0.4.0,>=0.3.7->autogluon.multimodal==1.5.0->autogluon)

In [ ]:
# @title
# -*- coding: utf-8 -*-
"""autogluon_heart_full.py"""

import os
import time
import psutil
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score, roc_auc_score, f1_score,
    precision_score, recall_score, log_loss, confusion_matrix
)

from autogluon.tabular import TabularPredictor


def get_system_ram():
    mem = psutil.virtual_memory()
    total = mem.total / (1024**3)
    used = mem.used / (1024**3)
    free = mem.available / (1024**3)
    percent = mem.percent
    return total, used, free, percent


def get_dir_size_mb(path: str) -> float:
    total_bytes = 0
    for root, _, files in os.walk(path):
        for f in files:
            fp = os.path.join(root, f)
            if os.path.isfile(fp):
                total_bytes += os.path.getsize(fp)
    return total_bytes / (1024 * 1024)


def pick_positive_proba(proba_df: pd.DataFrame, y_train: pd.Series) -> np.ndarray:
    # AutoGluon predict_proba => columns are class labels
    labels = sorted(pd.unique(y_train))
    pos_label = labels[-1]  # usually 1
    if pos_label in proba_df.columns:
        return proba_df[pos_label].to_numpy()
    # fallback: take last column
    return proba_df.iloc[:, -1].to_numpy()


# === Initial measurements ===
process = psutil.Process(os.getpid())
start_proc_mem = process.memory_info().rss / (1024 * 1024)  # MB
start_sys_total, start_sys_used, start_sys_free, start_sys_percent = get_system_ram()
start_time = time.time()

# 1) Data
data = pd.read_csv("heart_merged_clean.csv")
target_col = "target"

X = data.drop(columns=[target_col])
y = data[target_col]

train_df, test_df = train_test_split(
    data, test_size=0.2, random_state=42, stratify=y
)

# 2) AutoGluon settings
# - time_limit: total time limit
# - presets: fast training focused preset
# - num_bag_folds=5, num_stack_levels=0: stacking disabled (fast)
# Source: AutoGluon TabularPredictor.fit parameters. :contentReference[oaicite:3]{index=3}
predictor_path = "autogluon_heart_full_predictor"

predictor = TabularPredictor(
    label=target_col,
    eval_metric="f1",
    path=predictor_path
)

hyperparameters = None

predictor.fit(
    train_data=train_df,
    presets="best_quality",
    time_limit=180,
    num_bag_folds=5,
    num_stack_levels=0,
    hyperparameters=hyperparameters,
)

#3) Prediction
y_pred = predictor.predict(test_df)
proba_df = predictor.predict_proba(test_df)
y_pred_proba = pick_positive_proba(proba_df, train_df[target_col])

# 4) Metrics
y_test = test_df[target_col].to_numpy()
y_pred_np = pd.Series(y_pred).astype(int).to_numpy()

acc = accuracy_score(y_test, y_pred_np)
auc = roc_auc_score(y_test, y_pred_proba)
f1 = f1_score(y_test, y_pred_np)
precision = precision_score(y_test, y_pred_np)
recall = recall_score(y_test, y_pred_np)
ll = log_loss(y_test, y_pred_proba)
cm = confusion_matrix(y_test, y_pred_np)

# === Final measurements ===
end_time = time.time()
end_proc_mem = process.memory_info().rss / (1024 * 1024)
end_sys_total, end_sys_used, end_sys_free, end_sys_percent = get_system_ram()

runtime = end_time - start_time
proc_mem_usage = end_proc_mem - start_proc_mem
sys_used_diff = end_sys_used - start_sys_used

# Predictor dimension
model_size_mb = get_dir_size_mb(predictor_path)

print("\n=== AutoGluon Full Model Performance (Test) ===")
print(f"Accuracy:  {acc*100:.2f}%")
print(f"AUC:       {auc*100:.2f}%")
print(f"F1 Score:  {f1*100:.2f}%")
print(f"Precision: {precision*100:.2f}%")
print(f"Recall:    {recall*100:.2f}%")
print(f"LogLoss:   {ll:.2f}")

print("\nConfusion Matrix:")
print(cm)

print("\n=== Summary ===")
print(f"Runtime: {runtime:.2f} seconds")
print(f"Python process RAM usage: {proc_mem_usage:.2f} MB")

print("\n=== System RAM Usage ===")
print(f"Total RAM:         {end_sys_total:.2f} GB")
print(f"Used RAM:          {end_sys_used:.2f} GB")
print(f"Available RAM:     {end_sys_free:.2f} GB")
print(f"RAM utilization:   {end_sys_percent:.1f}%")
print(f"RAM increase during run: {sys_used_diff:.2f} GB")

print("\n=== Model Information ===")
print(f"Predictor path: {predictor_path}")
print(f"Predictor size: {model_size_mb:.2f} MB")


# Leaderboard
lb = predictor.leaderboard(test_df, silent=True)
print("\n=== Leaderboard ===")
print(lb.round(4))

Warning: path already exists! This predictor may overwrite an existing predictor! path="autogluon_heart_full_predictor"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Thu Oct  2 10:42:05 UTC 2025
CPU Count:          2
Pytorch Version:    2.9.0+cpu
CUDA Version:       CUDA is not available
Memory Avail:       9.45 GB / 12.67 GB (74.6%)
Disk Space Avail:   85.00 GB / 107.72 GB (78.9%)
===================================================
Presets specified: ['best_quality']
Using hyperparameters preset: hyperparameters='default'
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=5, num_bag_sets=1
Beginning AutoGluon training ... Time limit = 180s
AutoGluon will save models to "/content/autogluon_heart_full_predictor"
Train Data Rows:    736
Train Data Columns: 13
Label Column:       target
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.int64(1), np.int64(0)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    9691.46 MB
	Train Data (Original)  Memory Usage: 0.07 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 3 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 13 | ['age', 'sex', 'cp', 'trestbps', 'chol', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', [])     : 10 | ['age', 'cp', 'trestbps', 'chol', 'restecg', ...]
		('int', ['bool']) :  3 | ['sex', 'fbs', 'exang']
	0.2s = Fit runtime
	13 features in original data used to generate 13 features in processed data.
	Train Data (Processed) Memory Usage: 0.06 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.23s ...
AutoGluon will gauge predictive performance using evaluation metric: 'f1'
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 179.77s of the 179.76s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.18%)
	0.8458	 = Validation score   (f1)
	24.18s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 143.70s of the 143.69s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.18%)
	0.853	 = Validation score   (f1)
	22.67s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: RandomForestGini_BAG_L1 ... Training model for up to 115.64s of the 115.62s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=2, gpus=0
	0.8291	 = Validation score   (f1)
	1.47s	 = Training   runtime
	0.18s	 = Validation runtime
Fitting model: RandomForestEntr_BAG_L1 ... Training model for up to 113.93s of the 113.91s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=2, gpus=0
	0.8305	 = Validation score   (f1)
	1.07s	 = Training   runtime
	0.15s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 112.67s of the 112.65s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=4.07%)
	0.842	 = Validation score   (f1)
	17.18s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesGini_BAG_L1 ... Training model for up to 90.64s of the 90.63s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=2, gpus=0
	0.8415	 = Validation score   (f1)
	1.32s	 = Training   runtime
	0.25s	 = Validation runtime
Fitting model: ExtraTreesEntr_BAG_L1 ... Training model for up to 88.99s of the 88.97s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=2, gpus=0
	0.8425	 = Validation score   (f1)
	1.49s	 = Training   runtime
	0.3s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 87.13s of the 87.11s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.01%)
	0.8575	 = Validation score   (f1)
	37.73s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 44.23s of the 44.22s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.12%)
	0.8475	 = Validation score   (f1)
	30.73s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 6.82s of the 6.80s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.00%)
	Time limit exceeded... Skipping NeuralNetTorch_BAG_L1.
Fitting model: WeightedEnsemble_L2 ... Training model for up to 179.77s of the -9.43s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/9.1 GB
	Ensemble Weights: {'NeuralNetFastAI_BAG_L1': 0.875, 'LightGBM_BAG_L1': 0.062, 'ExtraTreesEntr_BAG_L1': 0.062}
	0.8626	 = Validation score   (f1)
	0.62s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 190.1s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 851.1 rows/s (148 batch size)
Enabling decision threshold calibration (calibrate_decision_threshold='auto', metric is valid, problem_type is 'binary')
Calibrating decision threshold to optimize metric f1 | Checking 51 thresholds...
Calibrating decision threshold via fine-grained search | Checking 38 thresholds...
	Base Threshold: 0.500	| val: 0.8626
	Best Threshold: 0.500	| val: 0.8626
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/content/autogluon_heart_full_predictor")

=== AutoGluon Full Model Performansı (Test) ===
Accuracy:  84.24%
AUC:       90.94%
F1 Score:  86.51%
Precision: 82.30%
Recall:    91.18%
LogLoss:   0.38

Confusion Matrix:
[[62 20]
 [ 9 93]]

=== Özet Bilgiler ===
Koşum Süresi: 195.30 saniye
Python İşlemi RAM Kullanımı: 68.47 MB

=== Sistem Genel RAM Kullanımı ===
Toplam RAM:         12.67 GB
Kullanılan RAM:     2.93 GB
Boş RAM:            9.42 GB
RAM Kullanım Oranı: 25.6%
Koşum sırasında artan RAM: 0.03 GB

=== Model Bilgileri ===
Predictor path: autogluon_heart_full_predictor
Predictor boyutu: 68.18 MB

=== Leaderboard ===
                     model  score_test  score_val eval_metric  pred_time_test  \
0  RandomForestGini_BAG_L1      0.8792     0.8291          f1          0.1401
1          CatBoost_BAG_L1      0.8667     0.8420          f1          0.1225
2        LightGBMXT_BAG_L1      0.8654     0.8458          f1          0.0412
3    ExtraTreesEntr_BAG_L1      0.8654     0.8425          f1          0.2937
4   NeuralNetFastAI_BAG_L1      0.8651     0.8575          f1          0.1473
5      WeightedEnsemble_L2      0.8651     0.8626          f1          0.4773
6           XGBoost_BAG_L1      0.8626     0.8475          f1          0.1636
7          LightGBM_BAG_L1      0.8558     0.8530          f1          0.0253
8  RandomForestEntr_BAG_L1      0.8529     0.8305          f1          0.1634
9    ExtraTreesGini_BAG_L1      0.8502     0.8415          f1          0.1690

   pred_time_val  fit_time  pred_time_test_marginal  pred_time_val_marginal  \
0         0.1838    1.4714                   0.1401                  0.1838
1         0.0098   17.1768                   0.1225                  0.0098
2         0.0463   24.1788                   0.0412                  0.0463
3         0.2983    1.4922                   0.2937                  0.2983
4         0.0893   37.7298                   0.1473                  0.0893
5         0.4159   62.5069                   0.0110                  0.0046
6         0.0393   30.7298                   0.1636                  0.0393
7         0.0237   22.6689                   0.0253                  0.0237
8         0.1463    1.0651                   0.1634                  0.1463
9         0.2494    1.3203                   0.1690                  0.2494

   fit_time_marginal  stack_level  can_infer  fit_order
0             1.4714            1       True          3
1            17.1768            1       True          5
2            24.1788            1       True          1
3             1.4922            1       True          7
4            37.7298            1       True          8
5             0.6160            2       True         10
6            30.7298            1       True          9
7            22.6689            1       True          2
8             1.0651            1       True          4
9             1.3203            1       True          6

**LIGHT AUTOGLUON**

In [ ]:
# @title
# -*- coding: utf-8 -*-
"""autogluon_heart_light.py"""

import os
import time
import psutil
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score, roc_auc_score, f1_score,
    precision_score, recall_score, log_loss, confusion_matrix
)

from autogluon.tabular import TabularPredictor


def get_system_ram():
    mem = psutil.virtual_memory()
    total = mem.total / (1024**3)
    used = mem.used / (1024**3)
    free = mem.available / (1024**3)
    percent = mem.percent
    return total, used, free, percent


def get_dir_size_mb(path: str) -> float:
    total_bytes = 0
    for root, _, files in os.walk(path):
        for f in files:
            fp = os.path.join(root, f)
            if os.path.isfile(fp):
                total_bytes += os.path.getsize(fp)
    return total_bytes / (1024 * 1024)


def pick_positive_proba(proba_df: pd.DataFrame, y_train: pd.Series) -> np.ndarray:
    # AutoGluon predict_proba => columns are class labels
    labels = sorted(pd.unique(y_train))
    pos_label = labels[-1]  # usually 1
    if pos_label in proba_df.columns:
        return proba_df[pos_label].to_numpy()
    # fallback: take the last column
    return proba_df.iloc[:, -1].to_numpy()


# === Initial measurements ===
process = psutil.Process(os.getpid())
start_proc_mem = process.memory_info().rss / (1024 * 1024)  # MB
start_sys_total, start_sys_used, start_sys_free, start_sys_percent = get_system_ram()
start_time = time.time()

# 1) Data
data = pd.read_csv("heart_merged_clean.csv")
target_col = "target"

X = data.drop(columns=[target_col])
y = data[target_col]

train_df, test_df = train_test_split(
    data, test_size=0.2, random_state=42, stratify=y
)

# 2) AutoGluon (Light) configuration
# - time_limit: total time budget (seconds)
# - presets: fast-training oriented preset
# - num_bag_folds=0, num_stack_levels=0: disable bagging/stacking (lightweight)
# Source: AutoGluon TabularPredictor.fit parameters. :contentReference[oaicite:3]{index=3}
predictor_path = "autogluon_heart_light_predictor"

predictor = TabularPredictor(
    label=target_col,
    eval_metric="f1",
    path=predictor_path
)

# Limit the model pool to keep the setup lightweight.
# (If some optional dependencies are missing, AutoGluon may skip those models anyway.)
hyperparameters = {
    "GBM": {},   # LightGBM
    "RF": {},    # RandomForest
    "XT": {},    # ExtraTrees
    "LR": {},    # LogisticRegression
}

predictor.fit(
    train_data=train_df,
    presets="medium_quality_faster_train",
    time_limit=60,
    num_bag_folds=0,
    num_stack_levels=0,
    hyperparameters=hyperparameters,
)

# 3) Prediction
y_pred = predictor.predict(test_df)
proba_df = predictor.predict_proba(test_df)
y_pred_proba = pick_positive_proba(proba_df, train_df[target_col])

# 4) Metrics
y_test = test_df[target_col].to_numpy()
y_pred_np = pd.Series(y_pred).astype(int).to_numpy()

acc = accuracy_score(y_test, y_pred_np)
auc = roc_auc_score(y_test, y_pred_proba)
f1 = f1_score(y_test, y_pred_np)
precision = precision_score(y_test, y_pred_np)
recall = recall_score(y_test, y_pred_np)
ll = log_loss(y_test, y_pred_proba)
cm = confusion_matrix(y_test, y_pred_np)

# === Final measurements ===
end_time = time.time()
end_proc_mem = process.memory_info().rss / (1024 * 1024)
end_sys_total, end_sys_used, end_sys_free, end_sys_percent = get_system_ram()

runtime = end_time - start_time
proc_mem_usage = end_proc_mem - start_proc_mem
sys_used_diff = end_sys_used - start_sys_used

# Predictor size on disk
model_size_mb = get_dir_size_mb(predictor_path)

print("\n=== AutoGluon Light Model Performance (Test) ===")
print(f"Accuracy:  {acc*100:.2f}%")
print(f"AUC:       {auc*100:.2f}%")
print(f"F1 Score:  {f1*100:.2f}%")
print(f"Precision: {precision*100:.2f}%")
print(f"Recall:    {recall*100:.2f}%")
print(f"LogLoss:   {ll:.2f}")

print("\nConfusion Matrix:")
print(cm)

print("\n=== Summary ===")
print(f"Runtime: {runtime:.2f} seconds")
print(f"Python process RAM usage: {proc_mem_usage:.2f} MB")

print("\n=== System RAM Usage ===")
print(f"Total RAM:         {end_sys_total:.2f} GB")
print(f"Used RAM:          {end_sys_used:.2f} GB")
print(f"Available RAM:     {end_sys_free:.2f} GB")
print(f"RAM utilization:   {end_sys_percent:.1f}%")
print(f"RAM increase during run: {sys_used_diff:.2f} GB")

print("\n=== Model Information ===")
print(f"Predictor path: {predictor_path}")
print(f"Predictor size: {model_size_mb:.2f} MB")

# Leaderboard
lb = predictor.leaderboard(test_df, silent=True)
print("\n=== Leaderboard ===")
print(lb.round(4))

Warning: path already exists! This predictor may overwrite an existing predictor! path="autogluon_heart_light_predictor"
Preset alias specified: 'medium_quality_faster_train' maps to 'medium_quality'.
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Thu Oct  2 10:42:05 UTC 2025
CPU Count:          2
Pytorch Version:    2.9.0+cpu
CUDA Version:       CUDA is not available
Memory Avail:       9.36 GB / 12.67 GB (73.9%)
Disk Space Avail:   84.96 GB / 107.72 GB (78.9%)
===================================================
Presets specified: ['medium_quality_faster_train']
Beginning AutoGluon training ... Time limit = 60s
AutoGluon will save models to "/content/autogluon_heart_light_predictor"
Train Data Rows:    736
Train Data Columns: 13
Label Column:       target
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.int64(1), np.int64(0)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    9587.19 MB
	Train Data (Original)  Memory Usage: 0.07 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 3 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 13 | ['age', 'sex', 'cp', 'trestbps', 'chol', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', [])     : 10 | ['age', 'cp', 'trestbps', 'chol', 'restecg', ...]
		('int', ['bool']) :  3 | ['sex', 'fbs', 'exang']
	0.1s = Fit runtime
	13 features in original data used to generate 13 features in processed data.
	Train Data (Processed) Memory Usage: 0.06 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.12s ...
AutoGluon will gauge predictive performance using evaluation metric: 'f1'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 588, Val Rows: 148
User-specified model hyperparameters to be fit:
{
	'GBM': [{}],
	'RF': [{}],
	'XT': [{}],
	'LR': [{}],
}
Fitting 4 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM ... Training model for up to 59.88s of the 59.87s of remaining time.
	Fitting with cpus=1, gpus=0, mem=0.0/9.4 GB
	0.8914	 = Validation score   (f1)
	1.48s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForest ... Training model for up to 58.38s of the 58.37s of remaining time.
	Fitting with cpus=2, gpus=0
	0.8555	 = Validation score   (f1)
	0.99s	 = Training   runtime
	0.11s	 = Validation runtime
Fitting model: ExtraTrees ... Training model for up to 57.25s of the 57.24s of remaining time.
	Fitting with cpus=2, gpus=0
	0.8605	 = Validation score   (f1)
	0.97s	 = Training   runtime
	0.11s	 = Validation runtime
Fitting model: LinearModel ... Training model for up to 56.12s of the 56.12s of remaining time.
	Fitting with cpus=2, gpus=0, mem=0.0/9.4 GB
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_data.py:2829: UserWarning: n_quantiles (1000) is greater than the total number of samples (588). n_quantiles is set to n_samples.
  warnings.warn(
	0.8353	 = Validation score   (f1)
	3.23s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 59.88s of the 52.85s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/9.2 GB
	Ensemble Weights: {'LightGBM': 0.75, 'RandomForest': 0.25}
	0.8966	 = Validation score   (f1)
	0.29s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 7.5s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 1274.0 rows/s (148 batch size)
Enabling decision threshold calibration (calibrate_decision_threshold='auto', metric is valid, problem_type is 'binary')
Calibrating decision threshold to optimize metric f1 | Checking 51 thresholds...
Calibrating decision threshold via fine-grained search | Checking 38 thresholds...
	Base Threshold: 0.500	| val: 0.8966
	Best Threshold: 0.500	| val: 0.8966
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/content/autogluon_heart_light_predictor")

=== AutoGluon Light Model Performansı (Test) ===
Accuracy:  84.78%
AUC:       92.80%
F1 Score:  86.67%
Precision: 84.26%
Recall:    89.22%
LogLoss:   0.37

Confusion Matrix:
[[65 17]
 [11 91]]

=== Özet Bilgiler ===
Koşum Süresi: 9.87 saniye
Python İşlemi RAM Kullanımı: 9.74 MB

=== Sistem Genel RAM Kullanımı ===
Toplam RAM:         12.67 GB
Kullanılan RAM:     3.16 GB
Boş RAM:            9.19 GB
RAM Kullanım Oranı: 27.5%
Koşum sırasında artan RAM: 0.18 GB

=== Model Bilgileri ===
Predictor path: autogluon_heart_light_predictor
Predictor boyutu: 13.07 MB

=== Leaderboard ===
                 model  score_test  score_val eval_metric  pred_time_test  \
0         RandomForest      0.8804     0.8555          f1          0.1337
1           ExtraTrees      0.8679     0.8605          f1          0.1349
2  WeightedEnsemble_L2      0.8667     0.8966          f1          0.1408
3             LightGBM      0.8571     0.8914          f1          0.0044
4          LinearModel      0.8406     0.8353          f1          0.0128

   pred_time_val  fit_time  pred_time_test_marginal  pred_time_val_marginal  \
0         0.1117    0.9904                   0.1337                  0.1117
1         0.1087    0.9703                   0.1349                  0.1087
2         0.1162    2.7650                   0.0027                  0.0031
3         0.0014    1.4834                   0.0044                  0.0014
4         0.0148    3.2275                   0.0128                  0.0148

   fit_time_marginal  stack_level  can_infer  fit_order
0             0.9904            1       True          2
1             0.9703            1       True          3
2             0.2911            2       True          5
3             1.4834            1       True          1
4             3.2275            1       True          4

**H2O AutoML (Full)**

In [4]:
!pip install h2o

Collecting h2o
  Downloading h2o-3.46.0.10-py2.py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from h2o) (2.32.4)
Requirement already satisfied: tabulate in /usr/local/lib/python3.12/dist-packages (from h2o) (0.9.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->h2o) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->h2o) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->h2o) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->h2o) (2026.4.22)
Downloading h2o-3.46.0.10-py2.py3-none-any.whl (266.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 266.4/266.4 MB 4.5 MB/s eta 0:00:00
Installing collected packages: h2o
Successfully installed h2o-3.46.0.10

In [ ]:
# @title
# -*- coding: utf-8 -*-
"""h2o_heart_full.py"""

import os
import time
import psutil
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score, roc_auc_score, f1_score,
    precision_score, recall_score, log_loss, confusion_matrix
)

import h2o
from h2o.automl import H2OAutoML


def get_system_ram():
    mem = psutil.virtual_memory()
    total = mem.total / (1024**3)
    used = mem.used / (1024**3)
    free = mem.available / (1024**3)
    percent = mem.percent
    return total, used, free, percent


# === Initial measurements ===
process = psutil.Process(os.getpid())
start_proc_mem = process.memory_info().rss / (1024 * 1024)  # MB
start_sys_total, start_sys_used, start_sys_free, start_sys_percent = get_system_ram()
start_time = time.time()

# 1) Data
data = pd.read_csv("heart_merged_clean.csv")
target_col = "target"

train_df, test_df = train_test_split(
    data, test_size=0.2, random_state=42, stratify=data[target_col]
)

# 2) Initialize H2O
h2o.init(max_mem_size="4G")
h2o.no_progress()

train_h2o = h2o.H2OFrame(train_df)
test_h2o = h2o.H2OFrame(test_df)

# Convert target to categorical (factor) for classification
train_h2o[target_col] = train_h2o[target_col].asfactor()
test_h2o[target_col] = test_h2o[target_col].asfactor()

x_cols = [c for c in train_df.columns if c != target_col]
y_col = target_col

# 3) H2O full configuration
# - max_runtime_secs: total time limit
# - nfolds=5: cross-validation
# - exclude_algos=None: allow all algorithms
# Source: H2OAutoML parameters (max_runtime_secs, exclude_algos, StackedEnsemble). :contentReference[oaicite:4]{index=4}
aml = H2OAutoML(
    max_runtime_secs=180,
    nfolds=5,
    seed=42,
    sort_metric="f1",
    exclude_algos=None,
)

aml.train(x=x_cols, y=y_col, training_frame=train_h2o)

best_model = aml.leader

# 4) Prediction
preds = best_model.predict(test_h2o)  # columns: predict, p0, p1
preds_df = preds.as_data_frame()

y_pred = preds_df["predict"].astype(int).to_numpy()

# The p1 column (positive class probability) is usually named "p1".
# In some cases, class-based naming may differ; therefore we add a fallback.
proba_col = "p1" if "p1" in preds_df.columns else preds_df.columns[-1]
y_pred_proba = preds_df[proba_col].to_numpy()

y_test = test_df[target_col].astype(int).to_numpy()

# 5) Metrics
acc = accuracy_score(y_test, y_pred)
auc = roc_auc_score(y_test, y_pred_proba)
f1 = f1_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
ll = log_loss(y_test, y_pred_proba)
cm = confusion_matrix(y_test, y_pred)

# 6) Save model
best_model_file = h2o.save_model(best_model, path=".", force=True)
model_size_mb = os.path.getsize(best_model_file) / (1024 * 1024)

# === Final measurements ===
end_time = time.time()
end_proc_mem = process.memory_info().rss / (1024 * 1024)
end_sys_total, end_sys_used, end_sys_free, end_sys_percent = get_system_ram()

runtime = end_time - start_time
proc_mem_usage = end_proc_mem - start_proc_mem
sys_used_diff = end_sys_used - start_sys_used

print("\n=== H2O AutoML Full Model Performance (Test) ===")
print(f"Accuracy:  {acc*100:.2f}%")
print(f"AUC:       {auc*100:.2f}%")
print(f"F1 Score:  {f1*100:.2f}%")
print(f"Precision: {precision*100:.2f}%")
print(f"Recall:    {recall*100:.2f}%")
print(f"LogLoss:   {ll:.2f}")

print("\nConfusion Matrix:")
print(cm)

print("\n=== Summary ===")
print(f"Runtime: {runtime:.2f} seconds")
print(f"Python process RAM usage: {proc_mem_usage:.2f} MB")

print("\n=== System RAM Usage ===")
print(f"Total RAM:         {end_sys_total:.2f} GB")
print(f"Used RAM:          {end_sys_used:.2f} GB")
print(f"Available RAM:     {end_sys_free:.2f} GB")
print(f"RAM utilization:   {end_sys_percent:.1f}%")
print(f"RAM increase during run: {sys_used_diff:.2f} GB")

print("\n=== Best Model Information ===")
print(f"Best model type: {type(best_model).__name__}")
print(f"Model file: {best_model_file}")
print(f"Model size: {model_size_mb:.2f} MB")

print("\n=== Leaderboard ===")
print(aml.leaderboard.as_data_frame().round(4))

# Shutdown H2O (free memory)
h2o.shutdown(prompt=False)

Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "17.0.17" 2025-10-21; OpenJDK Runtime Environment (build 17.0.17+10-Ubuntu-122.04); OpenJDK 64-Bit Server VM (build 17.0.17+10-Ubuntu-122.04, mixed mode, sharing)
  Starting server from /usr/local/lib/python3.12/dist-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmploc63oie
  JVM stdout: /tmp/tmploc63oie/h2o_unknownUser_started_from_python.out
  JVM stderr: /tmp/tmploc63oie/h2o_unknownUser_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  -----------------------------------------------------------------------------------------
H2O_cluster_uptime:         04 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.9
H2O_cluster_version_age:    1 month and 13 days
H2O_cluster_name:           H2O_from_python_unknownUser_crh5ht
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    3.979 Gb
H2O_cluster_total_cores:    2
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null, "colab_language_server": "/usr/colab/bin/language_service"}
H2O_internal_security:      False
Python_version:             3.12.12 final
--------------------------  -----------------------------------------------------------------------------------------

=== H2O AutoML Full Model Performansı (Test) ===
Accuracy:  82.07%
AUC:       90.32%
F1 Score:  84.79%
Precision: 80.00%
Recall:    90.20%
LogLoss:   0.46

Confusion Matrix:
[[59 23]
 [10 92]]

=== Özet Bilgiler ===
Koşum Süresi: 198.33 saniye
Python İşlemi RAM Kullanımı: 0.66 MB

=== Sistem Genel RAM Kullanımı ===
Toplam RAM:         12.67 GB
Kullanılan RAM:     3.88 GB
Boş RAM:            8.47 GB
RAM Kullanım Oranı: 33.1%
Koşum sırasında artan RAM: 0.76 GB

=== En İyi Model Bilgileri ===
En iyi model tipi: H2OXGBoostEstimator
Model dosyası: /content/XGBoost_grid_1_AutoML_1_20260106_190345_model_9
Model boyutu: 0.10 MB

=== Leaderboard ===
                                                   model_id      f1     auc  \
0           XGBoost_grid_1_AutoML_1_20260106_190345_model_9  0.8194  0.8445
1           XGBoost_grid_1_AutoML_1_20260106_190345_model_6  0.8201  0.8597
2                   DeepLearning_1_AutoML_1_20260106_190345  0.8213  0.8527
3               GBM_grid_1_AutoML_1_20260106_190345_model_8  0.8234  0.8555
4           XGBoost_grid_1_AutoML_1_20260106_190345_model_8  0.8239  0.8578
5               GBM_grid_1_AutoML_1_20260106_190345_model_6  0.8267  0.8750
6      DeepLearning_grid_3_AutoML_1_20260106_190345_model_1  0.8273  0.8690
7      DeepLearning_grid_2_AutoML_1_20260106_190345_model_1  0.8285  0.8631
8                            GBM_1_AutoML_1_20260106_190345  0.8292  0.8740
9      DeepLearning_grid_1_AutoML_1_20260106_190345_model_1  0.8293  0.8588
10                       XGBoost_1_AutoML_1_20260106_190345  0.8302  0.8680
11                           XRT_1_AutoML_1_20260106_190345  0.8304  0.8665
12             GBM_grid_1_AutoML_1_20260106_190345_model_11  0.8326  0.8728
13          XGBoost_grid_1_AutoML_1_20260106_190345_model_2  0.8330  0.8539
14                       XGBoost_2_AutoML_1_20260106_190345  0.8335  0.8627
15              GBM_grid_1_AutoML_1_20260106_190345_model_3  0.8341  0.8717
16              GBM_grid_1_AutoML_1_20260106_190345_model_2  0.8345  0.8708
17              GBM_grid_1_AutoML_1_20260106_190345_model_7  0.8348  0.8758
18     DeepLearning_grid_1_AutoML_1_20260106_190345_model_2  0.8348  0.8764
19          XGBoost_grid_1_AutoML_1_20260106_190345_model_1  0.8360  0.8624
20          XGBoost_grid_1_AutoML_1_20260106_190345_model_3  0.8364  0.8661
21              GBM_grid_1_AutoML_1_20260106_190345_model_5  0.8368  0.8743
22              GBM_grid_1_AutoML_1_20260106_190345_model_1  0.8372  0.8693
23                       XGBoost_3_AutoML_1_20260106_190345  0.8376  0.8669
24          XGBoost_grid_1_AutoML_1_20260106_190345_model_5  0.8380  0.8545
25          XGBoost_grid_1_AutoML_1_20260106_190345_model_4  0.8381  0.8790
26                           GLM_1_AutoML_1_20260106_190345  0.8383  0.8786
27                           GBM_2_AutoML_1_20260106_190345  0.8391  0.8730
28                           GBM_4_AutoML_1_20260106_190345  0.8397  0.8718
29                           GBM_3_AutoML_1_20260106_190345  0.8403  0.8716
30             GBM_grid_1_AutoML_1_20260106_190345_model_10  0.8419  0.8780
31  StackedEnsemble_BestOfFamily_3_AutoML_1_20260106_190345  0.8421  0.8810
32              GBM_grid_1_AutoML_1_20260106_190345_model_9  0.8427  0.8801
33     StackedEnsemble_AllModels_3_AutoML_1_20260106_190345  0.8439  0.8833
34  StackedEnsemble_BestOfFamily_1_AutoML_1_20260106_190345  0.8440  0.8808
35                           DRF_1_AutoML_1_20260106_190345  0.8440  0.8711
36          XGBoost_grid_1_AutoML_1_20260106_190345_model_7  0.8441  0.8682
37     StackedEnsemble_AllModels_4_AutoML_1_20260106_190345  0.8445  0.8831
38  StackedEnsemble_BestOfFamily_4_AutoML_1_20260106_190345  0.8452  0.8806
39              GBM_grid_1_AutoML_1_20260106_190345_model_4  0.8453  0.8776
40     StackedEnsemble_AllModels_1_AutoML_1_20260106_190345  0.8459  0.8805
41                           GBM_5_AutoML_1_20260106_190345  0.8471  0.8770
42     StackedEnsemble_AllModels_2_AutoML_1_20260106_190345  0.8474  0.8838
43  StackedEnsemble_BestOfFamily_2_AutoML_1_20260106_190345  0.8485  0.8807

    logloss   aucpr  mean_per_class_error    rmse     mse
0    0.5184  0.8516                0.2216  0.4128  0.1704
1    0.4691  0.8587                0.2417  0.3881  0.1506
2    0.5031  0.8559                0.2120  0.3949  0.1560
3    0.4741  0.8380                0.2135  0.3885  0.1509
4    0.4955  0.8464                0.2183  0.3893  0.1516
5    0.4428  0.8676                0.1981  0.3742  0.1400
6    0.4745  0.8761                0.2074  0.3827  0.1464
7    0.4911  0.8707                0.2083  0.3868  0.1496
8    0.4433  0.8638                0.2355  0.3747  0.1404
9    0.5284  0.8642                0.2244  0.3986  0.1589
10   0.4507  0.8552                0.2073  0.3771  0.1422
11   0.4670  0.8489                0.2097  0.3838  0.1473
12   0.4411  0.8613                0.2226  0.3731  0.1392
13   0.5436  0.8316                0.2094  0.3913  0.1531
14   0.4672  0.8409                0.1896  0.3799  0.1443
15   0.4465  0.8795                0.1967  0.3785  0.1433
16   0.4444  0.8577                0.2150  0.3749  0.1406
17   0.4441  0.8689                0.1859  0.3743  0.1401
18   0.5002  0.8897                0.2108  0.3802  0.1446
19   0.5277  0.8493                0.2117  0.3950  0.1560
20   0.4688  0.8535                0.2075  0.3783  0.1431
21   0.4361  0.8715                0.2033  0.3703  0.1371
22   0.4467  0.8649                0.1991  0.3753  0.1409
23   0.4631  0.8478                0.1949  0.3759  0.1413
24   0.5178  0.8337                0.1952  0.3903  0.1523
25   0.4346  0.8723                0.2021  0.3701  0.1370
26   0.4354  0.8896                0.1886  0.3712  0.1378
27   0.4401  0.8736                0.2005  0.3729  0.1391
28   0.4407  0.8674                0.1987  0.3725  0.1388
29   0.4407  0.8638                0.1855  0.3725  0.1388
30   0.4336  0.8718                0.1867  0.3696  0.1366
31   0.4360  0.8677                0.1777  0.3670  0.1347
32   0.4283  0.8747                0.1966  0.3677  0.1352
33   0.4243  0.8790                0.1837  0.3637  0.1323
34   0.4319  0.8836                0.1860  0.3687  0.1359
35   0.4872  0.8543                0.1953  0.3739  0.1398
36   0.4610  0.8528                0.1884  0.3753  0.1408
37   0.4240  0.8789                0.1980  0.3643  0.1327
38   0.4334  0.8717                0.1824  0.3669  0.1346
39   0.4307  0.8737                0.1848  0.3682  0.1356
40   0.4341  0.8716                0.1806  0.3663  0.1341
41   0.4330  0.8715                0.1956  0.3681  0.1355
42   0.4240  0.8723                0.1935  0.3626  0.1315
43   0.4358  0.8684                0.1734  0.3668  0.1345

/usr/local/lib/python3.12/dist-packages/h2o/frame.py:1983: H2ODependencyWarning: Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using multi-thread, install polars and pyarrow and use it as pandas_df = h2o_df.as_data_frame(use_multi_thread=True)

  warnings.warn("Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using"
/usr/local/lib/python3.12/dist-packages/h2o/frame.py:1983: H2ODependencyWarning: Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using multi-thread, install polars and pyarrow and use it as pandas_df = h2o_df.as_data_frame(use_multi_thread=True)

  warnings.warn("Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using"
/tmp/ipython-input-418148198.py:140: H2ODeprecationWarning: Deprecated, use ``h2o.cluster().shutdown()``.
  h2o.shutdown(prompt=False)

H2O session _sid_8683 closed.

**LIGHT H2O**

In [ ]:
# @title
# -*- coding: utf-8 -*-
"""h2o_heart_light.py"""

import os
import time
import psutil
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score, roc_auc_score, f1_score,
    precision_score, recall_score, log_loss, confusion_matrix
)

import h2o
from h2o.automl import H2OAutoML


def get_system_ram():
    mem = psutil.virtual_memory()
    total = mem.total / (1024**3)
    used = mem.used / (1024**3)
    free = mem.available / (1024**3)
    percent = mem.percent
    return total, used, free, percent


# === Initial measurements ===
process = psutil.Process(os.getpid())
start_proc_mem = process.memory_info().rss / (1024 * 1024)  # MB
start_sys_total, start_sys_used, start_sys_free, start_sys_percent = get_system_ram()
start_time = time.time()

# 1) Data
data = pd.read_csv("heart_merged_clean.csv")
target_col = "target"

train_df, test_df = train_test_split(
    data, test_size=0.2, random_state=42, stratify=data[target_col]
)

# 2) Initialize H2O
h2o.init(max_mem_size="4G")
h2o.no_progress()

train_h2o = h2o.H2OFrame(train_df)
test_h2o = h2o.H2OFrame(test_df)

# Convert target to categorical (factor) for classification
train_h2o[target_col] = train_h2o[target_col].asfactor()
test_h2o[target_col] = test_h2o[target_col].asfactor()

x_cols = [c for c in train_df.columns if c != target_col]
y_col = target_col

# 3) H2O Light configuration
# - max_runtime_secs: total runtime limit
# - nfolds=0: no cross-validation (lightweight)
# - exclude_algos disables StackedEnsemble and DeepLearning
# Source: H2OAutoML parameters (max_runtime_secs, exclude_algos, StackedEnsemble).
aml = H2OAutoML(
    max_runtime_secs=60,
    nfolds=0,
    seed=42,
    sort_metric="F1",
    exclude_algos=["StackedEnsemble", "DeepLearning"],
)

aml.train(x=x_cols, y=y_col, training_frame=train_h2o)

best_model = aml.leader

# 4) Prediction
preds = best_model.predict(test_h2o)  # columns: predict, p0, p1
preds_df = preds.as_data_frame()

y_pred = preds_df["predict"].astype(int).to_numpy()

# The p1 column (positive class probability) is usually named "p1".
# In some cases class-based naming may differ, so we include a fallback.
proba_col = "p1" if "p1" in preds_df.columns else preds_df.columns[-1]
y_pred_proba = preds_df[proba_col].to_numpy()

y_test = test_df[target_col].astype(int).to_numpy()

# 5) Metrics
acc = accuracy_score(y_test, y_pred)
auc = roc_auc_score(y_test, y_pred_proba)
f1 = f1_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
ll = log_loss(y_test, y_pred_proba)
cm = confusion_matrix(y_test, y_pred)

# 6) Save model
best_model_file = h2o.save_model(best_model, path=".", force=True)
model_size_mb = os.path.getsize(best_model_file) / (1024 * 1024)

# === Final measurements ===
end_time = time.time()
end_proc_mem = process.memory_info().rss / (1024 * 1024)
end_sys_total, end_sys_used, end_sys_free, end_sys_percent = get_system_ram()

runtime = end_time - start_time
proc_mem_usage = end_proc_mem - start_proc_mem
sys_used_diff = end_sys_used - start_sys_used

print("\n=== H2O AutoML Light Model Performance (Test) ===")
print(f"Accuracy:  {acc*100:.2f}%")
print(f"AUC:       {auc*100:.2f}%")
print(f"F1 Score:  {f1*100:.2f}%")
print(f"Precision: {precision*100:.2f}%")
print(f"Recall:    {recall*100:.2f}%")
print(f"LogLoss:   {ll:.2f}")

print("\nConfusion Matrix:")
print(cm)

print("\n=== Summary ===")
print(f"Runtime: {runtime:.2f} seconds")
print(f"Python process RAM usage: {proc_mem_usage:.2f} MB")

print("\n=== System RAM Usage ===")
print(f"Total RAM:         {end_sys_total:.2f} GB")
print(f"Used RAM:          {end_sys_used:.2f} GB")
print(f"Available RAM:     {end_sys_free:.2f} GB")
print(f"RAM utilization:   {end_sys_percent:.1f}%")
print(f"RAM increase during run: {sys_used_diff:.2f} GB")

print("\n=== Best Model Information ===")
print(f"Best model type: {type(best_model).__name__}")
print(f"Model file: {best_model_file}")
print(f"Model size: {model_size_mb:.2f} MB")

print("\n=== Leaderboard ===")
print(aml.leaderboard.as_data_frame().round(4))

# Shutdown H2O (free memory)
h2o.shutdown(prompt=False)

Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "17.0.17" 2025-10-21; OpenJDK Runtime Environment (build 17.0.17+10-Ubuntu-122.04); OpenJDK 64-Bit Server VM (build 17.0.17+10-Ubuntu-122.04, mixed mode, sharing)
  Starting server from /usr/local/lib/python3.12/dist-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmp8r90veac
  JVM stdout: /tmp/tmp8r90veac/h2o_unknownUser_started_from_python.out
  JVM stderr: /tmp/tmp8r90veac/h2o_unknownUser_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  -----------------------------------------------------------------------------------------
H2O_cluster_uptime:         03 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.9
H2O_cluster_version_age:    1 month and 13 days
H2O_cluster_name:           H2O_from_python_unknownUser_oefrir
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    4 Gb
H2O_cluster_total_cores:    2
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null, "colab_language_server": "/usr/colab/bin/language_service"}
H2O_internal_security:      False
Python_version:             3.12.12 final
--------------------------  -----------------------------------------------------------------------------------------

=== H2O AutoML Light Model Performansı (Test) ===
Accuracy:  80.98%
AUC:       89.07%
F1 Score:  84.58%
Precision: 76.80%
Recall:    94.12%
LogLoss:   0.41

Confusion Matrix:
[[53 29]
 [ 6 96]]

=== Özet Bilgiler ===
Koşum Süresi: 76.53 saniye
Python İşlemi RAM Kullanımı: 0.97 MB

=== Sistem Genel RAM Kullanımı ===
Toplam RAM:         12.67 GB
Kullanılan RAM:     3.77 GB
Boş RAM:            8.58 GB
RAM Kullanım Oranı: 32.3%
Koşum sırasında artan RAM: 0.70 GB

=== En İyi Model Bilgileri ===
En iyi model tipi: H2OXGBoostEstimator
Model dosyası: /content/XGBoost_2_AutoML_1_20260106_190909
Model boyutu: 0.12 MB

=== Leaderboard ===
                                            model_id      f1     auc  logloss  \
0                 XGBoost_2_AutoML_1_20260106_190909  0.7805  0.8383   0.5281
1        GBM_grid_1_AutoML_1_20260106_190909_model_1  0.7949  0.8444   0.5191
2       GBM_grid_1_AutoML_1_20260106_190909_model_30  0.8000  0.8519   0.4929
3       GBM_grid_1_AutoML_1_20260106_190909_model_17  0.8000  0.8602   0.4832
4                     GLM_1_AutoML_1_20260106_190909  0.8052  0.8910   0.4272
..                                               ...     ...     ...      ...
67  XGBoost_grid_1_AutoML_1_20260106_190909_model_11  0.8533  0.8647   0.4822
68      GBM_grid_1_AutoML_1_20260106_190909_model_19  0.8533  0.8737   0.4432
69       GBM_grid_1_AutoML_1_20260106_190909_model_3  0.8571  0.8947   0.4462
70                XGBoost_1_AutoML_1_20260106_190909  0.8571  0.9023   0.4144
71      GBM_grid_1_AutoML_1_20260106_190909_model_27  0.8649  0.8714   0.4506

     aucpr  mean_per_class_error    rmse     mse
0   0.7915                0.2402  0.4112  0.1691
1   0.7606                0.2150  0.4013  0.1610
2   0.8307                0.2030  0.4008  0.1607
3   0.8179                0.1921  0.3966  0.1573
4   0.8926                0.2019  0.3749  0.1405
..     ...                   ...     ...     ...
67  0.7963                0.1481  0.3792  0.1438
68  0.8375                0.1481  0.3711  0.1377
69  0.8421                0.1470  0.3670  0.1347
70  0.8589                0.1372  0.3571  0.1275
71  0.8280                0.1350  0.3721  0.1385

[72 rows x 8 columns]

/usr/local/lib/python3.12/dist-packages/h2o/frame.py:1983: H2ODependencyWarning: Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using multi-thread, install polars and pyarrow and use it as pandas_df = h2o_df.as_data_frame(use_multi_thread=True)

  warnings.warn("Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using"
/usr/local/lib/python3.12/dist-packages/h2o/frame.py:1983: H2ODependencyWarning: Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using multi-thread, install polars and pyarrow and use it as pandas_df = h2o_df.as_data_frame(use_multi_thread=True)

  warnings.warn("Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using"
/tmp/ipython-input-746543088.py:140: H2ODeprecationWarning: Deprecated, use ``h2o.cluster().shutdown()``.
  h2o.shutdown(prompt=False)

H2O session _sid_b6d7 closed.

**FLAML (Full)**

In [5]:
!pip install flaml

Collecting flaml
  Downloading flaml-2.6.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: NumPy>=1.17 in /usr/local/lib/python3.12/dist-packages (from flaml) (2.0.2)
Downloading flaml-2.6.0-py3-none-any.whl (349 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 349.7/349.7 kB 2.1 MB/s eta 0:00:00
Installing collected packages: flaml
Successfully installed flaml-2.6.0

In [ ]:
# @title
# -*- coding: utf-8 -*-
"""flaml_heart_full.py"""

import os
import time
import psutil
import joblib
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score, roc_auc_score, f1_score,
    precision_score, recall_score, log_loss, confusion_matrix
)

from flaml import AutoML


def get_system_ram():
    mem = psutil.virtual_memory()
    total = mem.total / (1024**3)
    used = mem.used / (1024**3)
    free = mem.available / (1024**3)
    percent = mem.percent
    return total, used, free, percent


def pick_pos_proba(proba: np.ndarray) -> np.ndarray:
    # Expected proba shape: (n, 2); fallback: last column
    if proba.ndim == 2 and proba.shape[1] >= 2:
        return proba[:, 1]
    if proba.ndim == 1:
        return proba
    return proba[:, -1]


# === Initial measurements ===
process = psutil.Process(os.getpid())
start_proc_mem = process.memory_info().rss / (1024 * 1024)  # MB
start_sys_total, start_sys_used, start_sys_free, start_sys_percent = get_system_ram()
start_time = time.time()

# 1) Data
data = pd.read_csv("heart_merged_clean.csv")
target_col = "target"
X = data.drop(columns=[target_col])
y = data[target_col].astype(int)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 2) FLAML configuration
# - time_budget: total time limit (seconds)
# - task/metric: classification objective and optimization metric
# - predict_proba and best estimator access via automl.model.estimator
# Source: FLAML classification example.
automl = AutoML()

automl_settings = {
    "time_budget": 180,
    "task": "classification",
    "metric": "f1",
    "seed": 42,
    "log_file_name": "flaml_heart_full.log",
    # 5-fold CV
    # "eval_method": "cv",
    "n_splits": 5,
    # Faster evaluation:
    "eval_method": "holdout",
    "split_ratio": 0.2,
    "n_jobs": -1,
}

automl.fit(X_train=X_train, y_train=y_train, **automl_settings)

# 3) Prediction
y_pred = automl.predict(X_test).astype(int)
y_pred_proba = pick_pos_proba(automl.predict_proba(X_test))

# 4) Metrics
acc = accuracy_score(y_test, y_pred)
auc = roc_auc_score(y_test, y_pred_proba)
f1 = f1_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
ll = log_loss(y_test, y_pred_proba)
cm = confusion_matrix(y_test, y_pred)

# 5) Save the best model
best_model = automl.model
best_model_file = "flaml_heart_full_best_model.pkl"
joblib.dump(best_model, best_model_file)
model_size_mb = os.path.getsize(best_model_file) / (1024 * 1024)

# === Final measurements ===
end_time = time.time()
end_proc_mem = process.memory_info().rss / (1024 * 1024)
end_sys_total, end_sys_used, end_sys_free, end_sys_percent = get_system_ram()

runtime = end_time - start_time
proc_mem_usage = end_proc_mem - start_proc_mem
sys_used_diff = end_sys_used - start_sys_used

print("\n=== FLAML Full Model Performance (Test) ===")
print(f"Accuracy:  {acc*100:.2f}%")
print(f"AUC:       {auc*100:.2f}%")
print(f"F1 Score:  {f1*100:.2f}%")
print(f"Precision: {precision*100:.2f}%")
print(f"Recall:    {recall*100:.2f}%")
print(f"LogLoss:   {ll:.2f}")

print("\nConfusion Matrix:")
print(cm)

print("\n=== Summary ===")
print(f"Runtime: {runtime:.2f} seconds")
print(f"Python process RAM usage: {proc_mem_usage:.2f} MB")

print("\n=== System RAM Usage ===")
print(f"Total RAM:         {end_sys_total:.2f} GB")
print(f"Used RAM:          {end_sys_used:.2f} GB")
print(f"Available RAM:     {end_sys_free:.2f} GB")
print(f"RAM utilization:   {end_sys_percent:.1f}%")
print(f"RAM increase during run: {sys_used_diff:.2f} GB")

print("\n=== Best Model Information ===")
print(f"Best model type: {type(best_model).__name__}")
print(f"Best estimator:  {getattr(best_model, 'estimator', 'N/A')}")
print(f"Model file: {best_model_file}")
print(f"Model size: {model_size_mb:.2f} MB")

[flaml.automl.logger: 01-06 19:20:11] {1752} INFO - task = classification
[flaml.automl.logger: 01-06 19:20:11] {1763} INFO - Evaluation method: holdout
[flaml.automl.logger: 01-06 19:20:11] {1862} INFO - Minimizing error metric: 1-f1
[flaml.automl.logger: 01-06 19:20:11] {1979} INFO - List of ML learners in AutoML Run: ['lgbm', 'rf', 'xgboost', 'extra_tree', 'xgb_limitdepth', 'sgd', 'catboost', 'lrl1']
[flaml.automl.logger: 01-06 19:20:11] {2282} INFO - iteration 0, current learner lgbm
[flaml.automl.logger: 01-06 19:20:11] {2417} INFO - Estimated sufficient time budget=312s. Estimated necessary time budget=8s.
[flaml.automl.logger: 01-06 19:20:11] {2466} INFO -  at 0.1s,	estimator lgbm's best error=0.1792,	best estimator lgbm's best error=0.1792
[flaml.automl.logger: 01-06 19:20:11] {2282} INFO - iteration 1, current learner lgbm
[flaml.automl.logger: 01-06 19:20:11] {2466} INFO -  at 0.1s,	estimator lgbm's best error=0.1792,	best estimator lgbm's best error=0.1792
[flaml.automl.logger: 01-06 19:20:11] {2282} INFO - iteration 2, current learner lgbm
[flaml.automl.logger: 01-06 19:20:11] {2466} INFO -  at 0.1s,	estimator lgbm's best error=0.1792,	best estimator lgbm's best error=0.1792
[flaml.automl.logger: 01-06 19:20:11] {2282} INFO - iteration 3, current learner sgd

INFO:flaml.tune.searcher.blendsearch:No low-cost partial config given to the search algorithm. For cost-frugal search, consider providing low-cost values for cost-related hps via 'low_cost_partial_config'. More info can be found at https://microsoft.github.io/FLAML/docs/FAQ#about-low_cost_partial_config-in-tune

[flaml.automl.logger: 01-06 19:20:11] {2466} INFO -  at 0.2s,	estimator sgd's best error=0.2900,	best estimator lgbm's best error=0.1792
[flaml.automl.logger: 01-06 19:20:11] {2282} INFO - iteration 4, current learner lgbm
[flaml.automl.logger: 01-06 19:20:11] {2466} INFO -  at 0.2s,	estimator lgbm's best error=0.1598,	best estimator lgbm's best error=0.1598
[flaml.automl.logger: 01-06 19:20:11] {2282} INFO - iteration 5, current learner lgbm
[flaml.automl.logger: 01-06 19:20:11] {2466} INFO -  at 0.2s,	estimator lgbm's best error=0.1598,	best estimator lgbm's best error=0.1598
[flaml.automl.logger: 01-06 19:20:11] {2282} INFO - iteration 6, current learner lgbm
[flaml.automl.logger: 01-06 19:20:11] {2466} INFO -  at 0.2s,	estimator lgbm's best error=0.1529,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:20:11] {2282} INFO - iteration 7, current learner lgbm
[flaml.automl.logger: 01-06 19:20:11] {2466} INFO -  at 0.3s,	estimator lgbm's best error=0.1529,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:20:11] {2282} INFO - iteration 8, current learner lgbm
[flaml.automl.logger: 01-06 19:20:11] {2466} INFO -  at 0.3s,	estimator lgbm's best error=0.1529,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:20:11] {2282} INFO - iteration 9, current learner lgbm
[flaml.automl.logger: 01-06 19:20:11] {2466} INFO -  at 0.3s,	estimator lgbm's best error=0.1529,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:20:11] {2282} INFO - iteration 10, current learner sgd
[flaml.automl.logger: 01-06 19:20:11] {2466} INFO -  at 0.3s,	estimator sgd's best error=0.2900,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:20:11] {2282} INFO - iteration 11, current learner xgboost
[flaml.automl.logger: 01-06 19:20:11] {2466} INFO -  at 0.4s,	estimator xgboost's best error=0.1792,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:20:11] {2282} INFO - iteration 12, current learner xgboost
[flaml.automl.logger: 01-06 19:20:11] {2466} INFO -  at 0.4s,	estimator xgboost's best error=0.1792,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:20:11] {2282} INFO - iteration 13, current learner xgboost
[flaml.automl.logger: 01-06 19:20:11] {2466} INFO -  at 0.5s,	estimator xgboost's best error=0.1792,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:20:11] {2282} INFO - iteration 14, current learner sgd
[flaml.automl.logger: 01-06 19:20:11] {2466} INFO -  at 0.5s,	estimator sgd's best error=0.2716,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:20:11] {2282} INFO - iteration 15, current learner lgbm
[flaml.automl.logger: 01-06 19:20:11] {2466} INFO -  at 0.5s,	estimator lgbm's best error=0.1529,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:20:11] {2282} INFO - iteration 16, current learner xgboost
[flaml.automl.logger: 01-06 19:20:11] {2466} INFO -  at 0.6s,	estimator xgboost's best error=0.1792,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:20:11] {2282} INFO - iteration 17, current learner extra_tree
[flaml.automl.logger: 01-06 19:20:11] {2466} INFO -  at 0.6s,	estimator extra_tree's best error=0.2308,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:20:11] {2282} INFO - iteration 18, current learner lgbm
[flaml.automl.logger: 01-06 19:20:11] {2466} INFO -  at 0.6s,	estimator lgbm's best error=0.1529,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:20:11] {2282} INFO - iteration 19, current learner extra_tree
[flaml.automl.logger: 01-06 19:20:12] {2466} INFO -  at 0.7s,	estimator extra_tree's best error=0.1882,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:20:12] {2282} INFO - iteration 20, current learner rf
[flaml.automl.logger: 01-06 19:20:12] {2466} INFO -  at 0.8s,	estimator rf's best error=0.2025,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:20:12] {2282} INFO - iteration 21, current learner rf
[flaml.automl.logger: 01-06 19:20:12] {2466} INFO -  at 0.9s,	estimator rf's best error=0.1765,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:20:12] {2282} INFO - iteration 22, current learner xgboost
[flaml.automl.logger: 01-06 19:20:12] {2466} INFO -  at 0.9s,	estimator xgboost's best error=0.1792,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:20:12] {2282} INFO - iteration 23, current learner lgbm
[flaml.automl.logger: 01-06 19:20:12] {2466} INFO -  at 1.0s,	estimator lgbm's best error=0.1529,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:20:12] {2282} INFO - iteration 24, current learner lgbm
[flaml.automl.logger: 01-06 19:20:12] {2466} INFO -  at 1.4s,	estimator lgbm's best error=0.1529,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:20:12] {2282} INFO - iteration 25, current learner extra_tree
[flaml.automl.logger: 01-06 19:20:12] {2466} INFO -  at 1.5s,	estimator extra_tree's best error=0.1882,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:20:12] {2282} INFO - iteration 26, current learner sgd
[flaml.automl.logger: 01-06 19:20:12] {2466} INFO -  at 1.5s,	estimator sgd's best error=0.2716,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:20:12] {2282} INFO - iteration 27, current learner rf
[flaml.automl.logger: 01-06 19:20:12] {2466} INFO -  at 1.6s,	estimator rf's best error=0.1687,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:20:12] {2282} INFO - iteration 28, current learner xgboost
[flaml.automl.logger: 01-06 19:20:12] {2466} INFO -  at 1.7s,	estimator xgboost's best error=0.1667,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:20:12] {2282} INFO - iteration 29, current learner extra_tree
[flaml.automl.logger: 01-06 19:20:13] {2466} INFO -  at 1.8s,	estimator extra_tree's best error=0.1676,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:20:13] {2282} INFO - iteration 30, current learner extra_tree
[flaml.automl.logger: 01-06 19:20:13] {2466} INFO -  at 1.9s,	estimator extra_tree's best error=0.1676,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:20:13] {2282} INFO - iteration 31, current learner lgbm
[flaml.automl.logger: 01-06 19:20:13] {2466} INFO -  at 1.9s,	estimator lgbm's best error=0.1529,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:20:13] {2282} INFO - iteration 32, current learner lgbm
[flaml.automl.logger: 01-06 19:20:13] {2466} INFO -  at 2.0s,	estimator lgbm's best error=0.1500,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:20:13] {2282} INFO - iteration 33, current learner rf
[flaml.automl.logger: 01-06 19:20:13] {2466} INFO -  at 2.1s,	estimator rf's best error=0.1687,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:20:13] {2282} INFO - iteration 34, current learner extra_tree
[flaml.automl.logger: 01-06 19:20:13] {2466} INFO -  at 2.2s,	estimator extra_tree's best error=0.1676,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:20:13] {2282} INFO - iteration 35, current learner lgbm
[flaml.automl.logger: 01-06 19:20:14] {2466} INFO -  at 2.7s,	estimator lgbm's best error=0.1500,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:20:14] {2282} INFO - iteration 36, current learner xgboost
[flaml.automl.logger: 01-06 19:20:14] {2466} INFO -  at 2.7s,	estimator xgboost's best error=0.1667,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:20:14] {2282} INFO - iteration 37, current learner sgd
[flaml.automl.logger: 01-06 19:20:14] {2466} INFO -  at 2.8s,	estimator sgd's best error=0.2716,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:20:14] {2282} INFO - iteration 38, current learner xgboost
[flaml.automl.logger: 01-06 19:20:14] {2466} INFO -  at 2.8s,	estimator xgboost's best error=0.1667,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:20:14] {2282} INFO - iteration 39, current learner catboost
[flaml.automl.logger: 01-06 19:20:14] {2466} INFO -  at 3.1s,	estimator catboost's best error=0.1646,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:20:14] {2282} INFO - iteration 40, current learner catboost
[flaml.automl.logger: 01-06 19:20:14] {2466} INFO -  at 3.3s,	estimator catboost's best error=0.1572,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:20:14] {2282} INFO - iteration 41, current learner xgboost
[flaml.automl.logger: 01-06 19:20:14] {2466} INFO -  at 3.4s,	estimator xgboost's best error=0.1667,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:20:14] {2282} INFO - iteration 42, current learner extra_tree
[flaml.automl.logger: 01-06 19:20:14] {2466} INFO -  at 3.5s,	estimator extra_tree's best error=0.1676,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:20:14] {2282} INFO - iteration 43, current learner catboost
[flaml.automl.logger: 01-06 19:20:15] {2466} INFO -  at 3.8s,	estimator catboost's best error=0.1572,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:20:15] {2282} INFO - iteration 44, current learner lgbm
[flaml.automl.logger: 01-06 19:20:15] {2466} INFO -  at 4.1s,	estimator lgbm's best error=0.1500,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:20:15] {2282} INFO - iteration 45, current learner extra_tree
[flaml.automl.logger: 01-06 19:20:15] {2466} INFO -  at 4.3s,	estimator extra_tree's best error=0.1676,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:20:15] {2282} INFO - iteration 46, current learner catboost
[flaml.automl.logger: 01-06 19:20:16] {2466} INFO -  at 5.1s,	estimator catboost's best error=0.1572,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:20:16] {2282} INFO - iteration 47, current learner extra_tree
[flaml.automl.logger: 01-06 19:20:16] {2466} INFO -  at 5.6s,	estimator extra_tree's best error=0.1676,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:20:16] {2282} INFO - iteration 48, current learner rf
[flaml.automl.logger: 01-06 19:20:17] {2466} INFO -  at 5.9s,	estimator rf's best error=0.1687,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:20:17] {2282} INFO - iteration 49, current learner extra_tree
[flaml.automl.logger: 01-06 19:20:17] {2466} INFO -  at 6.3s,	estimator extra_tree's best error=0.1676,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:20:17] {2282} INFO - iteration 50, current learner lgbm
[flaml.automl.logger: 01-06 19:20:18] {2466} INFO -  at 6.9s,	estimator lgbm's best error=0.1500,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:20:18] {2282} INFO - iteration 51, current learner xgboost
[flaml.automl.logger: 01-06 19:20:18] {2466} INFO -  at 7.1s,	estimator xgboost's best error=0.1667,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:20:18] {2282} INFO - iteration 52, current learner catboost
[flaml.automl.logger: 01-06 19:20:18] {2466} INFO -  at 7.4s,	estimator catboost's best error=0.1553,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:20:18] {2282} INFO - iteration 53, current learner rf
[flaml.automl.logger: 01-06 19:20:18] {2466} INFO -  at 7.6s,	estimator rf's best error=0.1617,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:20:18] {2282} INFO - iteration 54, current learner rf
[flaml.automl.logger: 01-06 19:20:18] {2466} INFO -  at 7.6s,	estimator rf's best error=0.1617,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:20:18] {2282} INFO - iteration 55, current learner lgbm
[flaml.automl.logger: 01-06 19:20:19] {2466} INFO -  at 7.7s,	estimator lgbm's best error=0.1500,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:20:19] {2282} INFO - iteration 56, current learner lgbm
[flaml.automl.logger: 01-06 19:20:19] {2466} INFO -  at 7.7s,	estimator lgbm's best error=0.1481,	best estimator lgbm's best error=0.1481
[flaml.automl.logger: 01-06 19:20:19] {2282} INFO - iteration 57, current learner xgboost
[flaml.automl.logger: 01-06 19:20:19] {2466} INFO -  at 7.8s,	estimator xgboost's best error=0.1667,	best estimator lgbm's best error=0.1481
[flaml.automl.logger: 01-06 19:20:19] {2282} INFO - iteration 58, current learner lgbm
[flaml.automl.logger: 01-06 19:20:19] {2466} INFO -  at 7.8s,	estimator lgbm's best error=0.1481,	best estimator lgbm's best error=0.1481
[flaml.automl.logger: 01-06 19:20:19] {2282} INFO - iteration 59, current learner rf
[flaml.automl.logger: 01-06 19:20:19] {2466} INFO -  at 7.9s,	estimator rf's best error=0.1617,	best estimator lgbm's best error=0.1481
[flaml.automl.logger: 01-06 19:20:19] {2282} INFO - iteration 60, current learner xgboost
[flaml.automl.logger: 01-06 19:20:19] {2466} INFO -  at 7.9s,	estimator xgboost's best error=0.1667,	best estimator lgbm's best error=0.1481
[flaml.automl.logger: 01-06 19:20:19] {2282} INFO - iteration 61, current learner lgbm
[flaml.automl.logger: 01-06 19:20:19] {2466} INFO -  at 8.0s,	estimator lgbm's best error=0.1481,	best estimator lgbm's best error=0.1481
[flaml.automl.logger: 01-06 19:20:19] {2282} INFO - iteration 62, current learner xgboost
[flaml.automl.logger: 01-06 19:20:19] {2466} INFO -  at 8.0s,	estimator xgboost's best error=0.1667,	best estimator lgbm's best error=0.1481
[flaml.automl.logger: 01-06 19:20:19] {2282} INFO - iteration 63, current learner lgbm
[flaml.automl.logger: 01-06 19:20:19] {2466} INFO -  at 8.1s,	estimator lgbm's best error=0.1481,	best estimator lgbm's best error=0.1481
[flaml.automl.logger: 01-06 19:20:19] {2282} INFO - iteration 64, current learner xgboost
[flaml.automl.logger: 01-06 19:20:19] {2466} INFO -  at 8.1s,	estimator xgboost's best error=0.1667,	best estimator lgbm's best error=0.1481
[flaml.automl.logger: 01-06 19:20:19] {2282} INFO - iteration 65, current learner extra_tree
[flaml.automl.logger: 01-06 19:20:19] {2466} INFO -  at 8.2s,	estimator extra_tree's best error=0.1676,	best estimator lgbm's best error=0.1481
[flaml.automl.logger: 01-06 19:20:19] {2282} INFO - iteration 66, current learner lgbm
[flaml.automl.logger: 01-06 19:20:19] {2466} INFO -  at 8.2s,	estimator lgbm's best error=0.1481,	best estimator lgbm's best error=0.1481
[flaml.automl.logger: 01-06 19:20:19] {2282} INFO - iteration 67, current learner xgboost
[flaml.automl.logger: 01-06 19:20:19] {2466} INFO -  at 8.2s,	estimator xgboost's best error=0.1667,	best estimator lgbm's best error=0.1481
[flaml.automl.logger: 01-06 19:20:19] {2282} INFO - iteration 68, current learner extra_tree
[flaml.automl.logger: 01-06 19:20:19] {2466} INFO -  at 8.4s,	estimator extra_tree's best error=0.1676,	best estimator lgbm's best error=0.1481
[flaml.automl.logger: 01-06 19:20:19] {2282} INFO - iteration 69, current learner xgboost
[flaml.automl.logger: 01-06 19:20:19] {2466} INFO -  at 8.4s,	estimator xgboost's best error=0.1667,	best estimator lgbm's best error=0.1481
[flaml.automl.logger: 01-06 19:20:19] {2282} INFO - iteration 70, current learner lgbm
[flaml.automl.logger: 01-06 19:20:19] {2466} INFO -  at 8.5s,	estimator lgbm's best error=0.1411,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:20:19] {2282} INFO - iteration 71, current learner lgbm
[flaml.automl.logger: 01-06 19:20:19] {2466} INFO -  at 8.6s,	estimator lgbm's best error=0.1411,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:20:19] {2282} INFO - iteration 72, current learner lgbm
[flaml.automl.logger: 01-06 19:20:19] {2466} INFO -  at 8.6s,	estimator lgbm's best error=0.1411,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:20:19] {2282} INFO - iteration 73, current learner lgbm
[flaml.automl.logger: 01-06 19:20:20] {2466} INFO -  at 8.7s,	estimator lgbm's best error=0.1411,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:20:20] {2282} INFO - iteration 74, current learner sgd
[flaml.automl.logger: 01-06 19:20:20] {2466} INFO -  at 8.8s,	estimator sgd's best error=0.2716,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:20:20] {2282} INFO - iteration 75, current learner lgbm
[flaml.automl.logger: 01-06 19:20:20] {2466} INFO -  at 8.9s,	estimator lgbm's best error=0.1411,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:20:20] {2282} INFO - iteration 76, current learner sgd
[flaml.automl.logger: 01-06 19:20:20] {2466} INFO -  at 8.9s,	estimator sgd's best error=0.2716,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:20:20] {2282} INFO - iteration 77, current learner lgbm
[flaml.automl.logger: 01-06 19:20:20] {2466} INFO -  at 9.0s,	estimator lgbm's best error=0.1411,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:20:20] {2282} INFO - iteration 78, current learner lgbm
[flaml.automl.logger: 01-06 19:20:20] {2466} INFO -  at 9.1s,	estimator lgbm's best error=0.1411,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:20:20] {2282} INFO - iteration 79, current learner extra_tree
[flaml.automl.logger: 01-06 19:20:20] {2466} INFO -  at 9.2s,	estimator extra_tree's best error=0.1676,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:20:20] {2282} INFO - iteration 80, current learner lgbm
[flaml.automl.logger: 01-06 19:20:20] {2466} INFO -  at 9.3s,	estimator lgbm's best error=0.1411,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:20:20] {2282} INFO - iteration 81, current learner lgbm
[flaml.automl.logger: 01-06 19:20:20] {2466} INFO -  at 9.4s,	estimator lgbm's best error=0.1411,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:20:20] {2282} INFO - iteration 82, current learner sgd
[flaml.automl.logger: 01-06 19:20:20] {2466} INFO -  at 9.5s,	estimator sgd's best error=0.2716,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:20:20] {2282} INFO - iteration 83, current learner lgbm
[flaml.automl.logger: 01-06 19:20:20] {2466} INFO -  at 9.6s,	estimator lgbm's best error=0.1411,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:20:20] {2282} INFO - iteration 84, current learner xgboost
[flaml.automl.logger: 01-06 19:20:20] {2466} INFO -  at 9.7s,	estimator xgboost's best error=0.1667,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:20:20] {2282} INFO - iteration 85, current learner xgboost
[flaml.automl.logger: 01-06 19:20:21] {2466} INFO -  at 9.7s,	estimator xgboost's best error=0.1667,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:20:21] {2282} INFO - iteration 86, current learner sgd
[flaml.automl.logger: 01-06 19:20:21] {2466} INFO -  at 9.7s,	estimator sgd's best error=0.2326,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:20:21] {2282} INFO - iteration 87, current learner sgd
[flaml.automl.logger: 01-06 19:20:21] {2466} INFO -  at 9.8s,	estimator sgd's best error=0.2151,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:20:21] {2282} INFO - iteration 88, current learner sgd
[flaml.automl.logger: 01-06 19:20:21] {2466} INFO -  at 9.8s,	estimator sgd's best error=0.2151,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:20:21] {2282} INFO - iteration 89, current learner xgboost
[flaml.automl.logger: 01-06 19:20:21] {2466} INFO -  at 9.8s,	estimator xgboost's best error=0.1667,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:20:21] {2282} INFO - iteration 90, current learner rf
[flaml.automl.logger: 01-06 19:20:21] {2466} INFO -  at 10.0s,	estimator rf's best error=0.1585,	best estimator lgbm's best error=0.1411

INFO:flaml.tune.searcher.blendsearch:No low-cost partial config given to the search algorithm. For cost-frugal search, consider providing low-cost values for cost-related hps via 'low_cost_partial_config'. More info can be found at https://microsoft.github.io/FLAML/docs/FAQ#about-low_cost_partial_config-in-tune

[flaml.automl.logger: 01-06 19:20:57] {2466} INFO -  at 46.4s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:20:57] {2282} INFO - iteration 323, current learner lrl1
[flaml.automl.logger: 01-06 19:20:57] {2466} INFO -  at 46.4s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:20:57] {2282} INFO - iteration 324, current learner lrl1
[flaml.automl.logger: 01-06 19:20:57] {2466} INFO -  at 46.5s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:20:57] {2282} INFO - iteration 325, current learner lrl1
[flaml.automl.logger: 01-06 19:20:57] {2466} INFO -  at 46.5s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:20:57] {2282} INFO - iteration 326, current learner lrl1
[flaml.automl.logger: 01-06 19:20:57] {2466} INFO -  at 46.6s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:20:57] {2282} INFO - iteration 327, current learner lrl1
[flaml.automl.logger: 01-06 19:20:57] {2466} INFO -  at 46.6s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:20:57] {2282} INFO - iteration 328, current learner lrl1
[flaml.automl.logger: 01-06 19:20:58] {2466} INFO -  at 46.7s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:20:58] {2282} INFO - iteration 329, current learner lrl1
[flaml.automl.logger: 01-06 19:20:58] {2466} INFO -  at 46.8s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:20:58] {2282} INFO - iteration 330, current learner lrl1
[flaml.automl.logger: 01-06 19:20:58] {2466} INFO -  at 46.8s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:20:58] {2282} INFO - iteration 331, current learner xgboost
[flaml.automl.logger: 01-06 19:20:58] {2466} INFO -  at 46.9s,	estimator xgboost's best error=0.1220,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:20:58] {2282} INFO - iteration 332, current learner lrl1
[flaml.automl.logger: 01-06 19:20:58] {2466} INFO -  at 46.9s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:20:58] {2282} INFO - iteration 333, current learner lrl1
[flaml.automl.logger: 01-06 19:20:58] {2466} INFO -  at 47.0s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:20:58] {2282} INFO - iteration 334, current learner catboost
[flaml.automl.logger: 01-06 19:20:58] {2466} INFO -  at 47.1s,	estimator catboost's best error=0.1500,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:20:58] {2282} INFO - iteration 335, current learner lrl1
[flaml.automl.logger: 01-06 19:20:58] {2466} INFO -  at 47.2s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:20:58] {2282} INFO - iteration 336, current learner lrl1
[flaml.automl.logger: 01-06 19:20:58] {2466} INFO -  at 47.2s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:20:58] {2282} INFO - iteration 337, current learner lrl1
[flaml.automl.logger: 01-06 19:20:58] {2466} INFO -  at 47.3s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:20:58] {2282} INFO - iteration 338, current learner xgboost
[flaml.automl.logger: 01-06 19:20:58] {2466} INFO -  at 47.3s,	estimator xgboost's best error=0.1220,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:20:58] {2282} INFO - iteration 339, current learner lrl1
[flaml.automl.logger: 01-06 19:20:58] {2466} INFO -  at 47.4s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:20:58] {2282} INFO - iteration 340, current learner lrl1
[flaml.automl.logger: 01-06 19:20:58] {2466} INFO -  at 47.4s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:20:58] {2282} INFO - iteration 341, current learner lrl1
[flaml.automl.logger: 01-06 19:20:58] {2466} INFO -  at 47.5s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:20:58] {2282} INFO - iteration 342, current learner lrl1
[flaml.automl.logger: 01-06 19:20:58] {2466} INFO -  at 47.5s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:20:58] {2282} INFO - iteration 343, current learner rf
[flaml.automl.logger: 01-06 19:20:58] {2466} INFO -  at 47.6s,	estimator rf's best error=0.1463,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:20:58] {2282} INFO - iteration 344, current learner lrl1
[flaml.automl.logger: 01-06 19:20:59] {2466} INFO -  at 47.7s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:20:59] {2282} INFO - iteration 345, current learner lrl1
[flaml.automl.logger: 01-06 19:20:59] {2466} INFO -  at 47.7s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:20:59] {2282} INFO - iteration 346, current learner lrl1
[flaml.automl.logger: 01-06 19:20:59] {2466} INFO -  at 47.8s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:20:59] {2282} INFO - iteration 347, current learner lrl1
[flaml.automl.logger: 01-06 19:20:59] {2466} INFO -  at 47.8s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:20:59] {2282} INFO - iteration 348, current learner lrl1
[flaml.automl.logger: 01-06 19:20:59] {2466} INFO -  at 47.9s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:20:59] {2282} INFO - iteration 349, current learner lrl1
[flaml.automl.logger: 01-06 19:20:59] {2466} INFO -  at 48.0s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:20:59] {2282} INFO - iteration 350, current learner lrl1
[flaml.automl.logger: 01-06 19:20:59] {2466} INFO -  at 48.1s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:20:59] {2282} INFO - iteration 351, current learner lrl1
[flaml.automl.logger: 01-06 19:20:59] {2466} INFO -  at 48.1s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:20:59] {2282} INFO - iteration 352, current learner xgboost
[flaml.automl.logger: 01-06 19:20:59] {2466} INFO -  at 48.3s,	estimator xgboost's best error=0.1220,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:20:59] {2282} INFO - iteration 353, current learner lrl1
[flaml.automl.logger: 01-06 19:20:59] {2466} INFO -  at 48.4s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:20:59] {2282} INFO - iteration 354, current learner lrl1
[flaml.automl.logger: 01-06 19:20:59] {2466} INFO -  at 48.5s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:20:59] {2282} INFO - iteration 355, current learner lrl1
[flaml.automl.logger: 01-06 19:20:59] {2466} INFO -  at 48.5s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:20:59] {2282} INFO - iteration 356, current learner lrl1
[flaml.automl.logger: 01-06 19:20:59] {2466} INFO -  at 48.6s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:20:59] {2282} INFO - iteration 357, current learner rf
[flaml.automl.logger: 01-06 19:21:00] {2466} INFO -  at 48.8s,	estimator rf's best error=0.1463,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:00] {2282} INFO - iteration 358, current learner lrl1
[flaml.automl.logger: 01-06 19:21:00] {2466} INFO -  at 48.8s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:00] {2282} INFO - iteration 359, current learner lrl1
[flaml.automl.logger: 01-06 19:21:00] {2466} INFO -  at 48.9s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:00] {2282} INFO - iteration 360, current learner xgboost
[flaml.automl.logger: 01-06 19:21:00] {2466} INFO -  at 49.1s,	estimator xgboost's best error=0.1220,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:00] {2282} INFO - iteration 361, current learner xgboost
[flaml.automl.logger: 01-06 19:21:00] {2466} INFO -  at 49.3s,	estimator xgboost's best error=0.1220,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:00] {2282} INFO - iteration 362, current learner lrl1
[flaml.automl.logger: 01-06 19:21:00] {2466} INFO -  at 49.4s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:00] {2282} INFO - iteration 363, current learner catboost
[flaml.automl.logger: 01-06 19:21:01] {2466} INFO -  at 49.7s,	estimator catboost's best error=0.1500,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:01] {2282} INFO - iteration 364, current learner lrl1
[flaml.automl.logger: 01-06 19:21:01] {2466} INFO -  at 49.8s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:01] {2282} INFO - iteration 365, current learner lrl1
[flaml.automl.logger: 01-06 19:21:01] {2466} INFO -  at 49.9s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:01] {2282} INFO - iteration 366, current learner lrl1
[flaml.automl.logger: 01-06 19:21:01] {2466} INFO -  at 50.0s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:01] {2282} INFO - iteration 367, current learner lrl1
[flaml.automl.logger: 01-06 19:21:01] {2466} INFO -  at 50.1s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:01] {2282} INFO - iteration 368, current learner xgboost
[flaml.automl.logger: 01-06 19:21:01] {2466} INFO -  at 50.2s,	estimator xgboost's best error=0.1220,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:01] {2282} INFO - iteration 369, current learner xgboost
[flaml.automl.logger: 01-06 19:21:01] {2466} INFO -  at 50.3s,	estimator xgboost's best error=0.1220,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:01] {2282} INFO - iteration 370, current learner lrl1
[flaml.automl.logger: 01-06 19:21:01] {2466} INFO -  at 50.4s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:01] {2282} INFO - iteration 371, current learner lrl1
[flaml.automl.logger: 01-06 19:21:01] {2466} INFO -  at 50.5s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:01] {2282} INFO - iteration 372, current learner lrl1
[flaml.automl.logger: 01-06 19:21:01] {2466} INFO -  at 50.6s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:01] {2282} INFO - iteration 373, current learner lrl1
[flaml.automl.logger: 01-06 19:21:02] {2466} INFO -  at 50.7s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:02] {2282} INFO - iteration 374, current learner lrl1
[flaml.automl.logger: 01-06 19:21:02] {2466} INFO -  at 50.8s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:02] {2282} INFO - iteration 375, current learner lrl1
[flaml.automl.logger: 01-06 19:21:02] {2466} INFO -  at 50.9s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:02] {2282} INFO - iteration 376, current learner lrl1
[flaml.automl.logger: 01-06 19:21:02] {2466} INFO -  at 51.0s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:02] {2282} INFO - iteration 377, current learner xgboost
[flaml.automl.logger: 01-06 19:21:02] {2466} INFO -  at 51.1s,	estimator xgboost's best error=0.1220,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:02] {2282} INFO - iteration 378, current learner extra_tree
[flaml.automl.logger: 01-06 19:21:02] {2466} INFO -  at 51.1s,	estimator extra_tree's best error=0.1617,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:02] {2282} INFO - iteration 379, current learner rf
[flaml.automl.logger: 01-06 19:21:02] {2466} INFO -  at 51.3s,	estimator rf's best error=0.1463,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:02] {2282} INFO - iteration 380, current learner xgboost
[flaml.automl.logger: 01-06 19:21:02] {2466} INFO -  at 51.5s,	estimator xgboost's best error=0.1220,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:02] {2282} INFO - iteration 381, current learner lrl1
[flaml.automl.logger: 01-06 19:21:02] {2466} INFO -  at 51.5s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:02] {2282} INFO - iteration 382, current learner rf
[flaml.automl.logger: 01-06 19:21:03] {2466} INFO -  at 51.7s,	estimator rf's best error=0.1463,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:03] {2282} INFO - iteration 383, current learner extra_tree
[flaml.automl.logger: 01-06 19:21:03] {2466} INFO -  at 51.8s,	estimator extra_tree's best error=0.1617,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:03] {2282} INFO - iteration 384, current learner lrl1
[flaml.automl.logger: 01-06 19:21:03] {2466} INFO -  at 51.9s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:03] {2282} INFO - iteration 385, current learner lrl1
[flaml.automl.logger: 01-06 19:21:03] {2466} INFO -  at 52.0s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:03] {2282} INFO - iteration 386, current learner lrl1
[flaml.automl.logger: 01-06 19:21:03] {2466} INFO -  at 52.1s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:03] {2282} INFO - iteration 387, current learner xgboost
[flaml.automl.logger: 01-06 19:21:03] {2466} INFO -  at 52.2s,	estimator xgboost's best error=0.1220,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:03] {2282} INFO - iteration 388, current learner catboost
[flaml.automl.logger: 01-06 19:21:03] {2466} INFO -  at 52.4s,	estimator catboost's best error=0.1447,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:03] {2282} INFO - iteration 389, current learner lrl1
[flaml.automl.logger: 01-06 19:21:03] {2466} INFO -  at 52.4s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:03] {2282} INFO - iteration 390, current learner lrl1
[flaml.automl.logger: 01-06 19:21:03] {2466} INFO -  at 52.5s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:03] {2282} INFO - iteration 391, current learner xgboost
[flaml.automl.logger: 01-06 19:21:03] {2466} INFO -  at 52.7s,	estimator xgboost's best error=0.1220,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:03] {2282} INFO - iteration 392, current learner xgboost
[flaml.automl.logger: 01-06 19:21:04] {2466} INFO -  at 52.8s,	estimator xgboost's best error=0.1220,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:04] {2282} INFO - iteration 393, current learner xgboost
[flaml.automl.logger: 01-06 19:21:04] {2466} INFO -  at 52.9s,	estimator xgboost's best error=0.1220,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:04] {2282} INFO - iteration 394, current learner lrl1
[flaml.automl.logger: 01-06 19:21:04] {2466} INFO -  at 52.9s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:04] {2282} INFO - iteration 395, current learner catboost
[flaml.automl.logger: 01-06 19:21:04] {2466} INFO -  at 53.0s,	estimator catboost's best error=0.1447,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:04] {2282} INFO - iteration 396, current learner rf
[flaml.automl.logger: 01-06 19:21:04] {2466} INFO -  at 53.2s,	estimator rf's best error=0.1463,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:04] {2282} INFO - iteration 397, current learner catboost
[flaml.automl.logger: 01-06 19:21:04] {2466} INFO -  at 53.3s,	estimator catboost's best error=0.1447,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:04] {2282} INFO - iteration 398, current learner xgboost
[flaml.automl.logger: 01-06 19:21:04] {2466} INFO -  at 53.3s,	estimator xgboost's best error=0.1220,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:04] {2282} INFO - iteration 399, current learner lrl1
[flaml.automl.logger: 01-06 19:21:04] {2466} INFO -  at 53.4s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:04] {2282} INFO - iteration 400, current learner xgboost
[flaml.automl.logger: 01-06 19:21:04] {2466} INFO -  at 53.5s,	estimator xgboost's best error=0.1220,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:04] {2282} INFO - iteration 401, current learner rf
[flaml.automl.logger: 01-06 19:21:04] {2466} INFO -  at 53.6s,	estimator rf's best error=0.1463,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:04] {2282} INFO - iteration 402, current learner lrl1
[flaml.automl.logger: 01-06 19:21:04] {2466} INFO -  at 53.6s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:04] {2282} INFO - iteration 403, current learner lrl1
[flaml.automl.logger: 01-06 19:21:05] {2466} INFO -  at 53.7s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:05] {2282} INFO - iteration 404, current learner sgd
[flaml.automl.logger: 01-06 19:21:05] {2466} INFO -  at 53.7s,	estimator sgd's best error=0.2128,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:05] {2282} INFO - iteration 405, current learner lrl1
[flaml.automl.logger: 01-06 19:21:05] {2466} INFO -  at 53.7s,	estimator lrl1's best error=0.2663,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:05] {2282} INFO - iteration 406, current learner catboost
[flaml.automl.logger: 01-06 19:21:05] {2466} INFO -  at 53.8s,	estimator catboost's best error=0.1447,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:05] {2282} INFO - iteration 407, current learner catboost
[flaml.automl.logger: 01-06 19:21:05] {2466} INFO -  at 54.0s,	estimator catboost's best error=0.1447,	best estimator xgboost's best error=0.1220
[flaml.automl.logger: 01-06 19:21:05] {2282} INFO - iteration 408, current learner lrl1

**LIGHT FLAML**

In [ ]:
# -*- coding: utf-8 -*-
"""flaml_heart_light.py"""

import os
import time
import psutil
import joblib
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score, roc_auc_score, f1_score,
    precision_score, recall_score, log_loss, confusion_matrix
)

from flaml import AutoML


def get_system_ram():
    mem = psutil.virtual_memory()
    total = mem.total / (1024**3)
    used = mem.used / (1024**3)
    free = mem.available / (1024**3)
    percent = mem.percent
    return total, used, free, percent


def pick_pos_proba(proba: np.ndarray) -> np.ndarray:
    # Expected proba shape: (n, 2); fallback: last column
    if proba.ndim == 2 and proba.shape[1] >= 2:
        return proba[:, 1]
    if proba.ndim == 1:
        return proba
    return proba[:, -1]


# === Initial measurements ===
process = psutil.Process(os.getpid())
start_proc_mem = process.memory_info().rss / (1024 * 1024)  # MB
start_sys_total, start_sys_used, start_sys_free, start_sys_percent = get_system_ram()
start_time = time.time()

# 1) Data
data = pd.read_csv("heart_merged_clean.csv")
target_col = "target"
X = data.drop(columns=[target_col])
y = data[target_col].astype(int)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 2) FLAML Light configuration
# - time_budget: total time limit (seconds)
# - task/metric: classification objective and optimization metric
# - predict_proba and best estimator access via automl.model.estimator
# Source: FLAML classification example.
automl = AutoML()

automl_settings = {
    "time_budget": 60,
    "task": "classification",
    "metric": "f1",
    "seed": 42,
    "log_file_name": "flaml_heart_light.log",
    # (Optional) Narrow down estimator list for a lighter/faster run:
    "estimator_list": ["lgbm", "rf", "extra_tree", "lrl1"],
    # Faster evaluation:
    "eval_method": "holdout",
    "split_ratio": 0.2,
    "n_jobs": -1,
}

automl.fit(X_train=X_train, y_train=y_train, **automl_settings)

# 3) Prediction
y_pred = automl.predict(X_test).astype(int)
y_pred_proba = pick_pos_proba(automl.predict_proba(X_test))

# 4) Metrics
acc = accuracy_score(y_test, y_pred)
auc = roc_auc_score(y_test, y_pred_proba)
f1 = f1_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
ll = log_loss(y_test, y_pred_proba)
cm = confusion_matrix(y_test, y_pred)

# 5) Save the best model
best_model = automl.model
best_model_file = "flaml_heart_light_best_model.pkl"
joblib.dump(best_model, best_model_file)
model_size_mb = os.path.getsize(best_model_file) / (1024 * 1024)

# === Final measurements ===
end_time = time.time()
end_proc_mem = process.memory_info().rss / (1024 * 1024)
end_sys_total, end_sys_used, end_sys_free, end_sys_percent = get_system_ram()

runtime = end_time - start_time
proc_mem_usage = end_proc_mem - start_proc_mem
sys_used_diff = end_sys_used - start_sys_used

print("\n=== FLAML Light Model Performance (Test) ===")
print(f"Accuracy:  {acc*100:.2f}%")
print(f"AUC:       {auc*100:.2f}%")
print(f"F1 Score:  {f1*100:.2f}%")
print(f"Precision: {precision*100:.2f}%")
print(f"Recall:    {recall*100:.2f}%")
print(f"LogLoss:   {ll:.2f}")

print("\nConfusion Matrix:")
print(cm)

print("\n=== Summary ===")
print(f"Runtime: {runtime:.2f} seconds")
print(f"Python process RAM usage: {proc_mem_usage:.2f} MB")

print("\n=== System RAM Usage ===")
print(f"Total RAM:         {end_sys_total:.2f} GB")
print(f"Used RAM:          {end_sys_used:.2f} GB")
print(f"Available RAM:     {end_sys_free:.2f} GB")
print(f"RAM utilization:   {end_sys_percent:.1f}%")
print(f"RAM increase during run: {sys_used_diff:.2f} GB")

print("\n=== Best Model Information ===")
print(f"Best model type: {type(best_model).__name__}")
print(f"Best estimator:  {getattr(best_model, 'estimator', 'N/A')}")
print(f"Model file: {best_model_file}")
print(f"Model size: {model_size_mb:.2f} MB")

[flaml.automl.logger: 01-06 19:27:31] {1752} INFO - task = classification
[flaml.automl.logger: 01-06 19:27:31] {1763} INFO - Evaluation method: holdout
[flaml.automl.logger: 01-06 19:27:31] {1862} INFO - Minimizing error metric: 1-f1
[flaml.automl.logger: 01-06 19:27:31] {1979} INFO - List of ML learners in AutoML Run: ['lgbm', 'rf', 'extra_tree', 'lrl1']
[flaml.automl.logger: 01-06 19:27:31] {2282} INFO - iteration 0, current learner lgbm
[flaml.automl.logger: 01-06 19:27:31] {2417} INFO - Estimated sufficient time budget=186s. Estimated necessary time budget=3s.
[flaml.automl.logger: 01-06 19:27:31] {2466} INFO -  at 0.1s,	estimator lgbm's best error=0.1792,	best estimator lgbm's best error=0.1792
[flaml.automl.logger: 01-06 19:27:31] {2282} INFO - iteration 1, current learner lgbm
[flaml.automl.logger: 01-06 19:27:31] {2466} INFO -  at 0.1s,	estimator lgbm's best error=0.1792,	best estimator lgbm's best error=0.1792
[flaml.automl.logger: 01-06 19:27:31] {2282} INFO - iteration 2, current learner lgbm
[flaml.automl.logger: 01-06 19:27:31] {2466} INFO -  at 0.1s,	estimator lgbm's best error=0.1792,	best estimator lgbm's best error=0.1792
[flaml.automl.logger: 01-06 19:27:31] {2282} INFO - iteration 3, current learner extra_tree
[flaml.automl.logger: 01-06 19:27:31] {2466} INFO -  at 0.2s,	estimator extra_tree's best error=0.2308,	best estimator lgbm's best error=0.1792
[flaml.automl.logger: 01-06 19:27:31] {2282} INFO - iteration 4, current learner rf
[flaml.automl.logger: 01-06 19:27:31] {2466} INFO -  at 0.2s,	estimator rf's best error=0.2025,	best estimator lgbm's best error=0.1792
[flaml.automl.logger: 01-06 19:27:31] {2282} INFO - iteration 5, current learner lgbm
[flaml.automl.logger: 01-06 19:27:31] {2466} INFO -  at 0.3s,	estimator lgbm's best error=0.1598,	best estimator lgbm's best error=0.1598
[flaml.automl.logger: 01-06 19:27:31] {2282} INFO - iteration 6, current learner lgbm
[flaml.automl.logger: 01-06 19:27:31] {2466} INFO -  at 0.3s,	estimator lgbm's best error=0.1598,	best estimator lgbm's best error=0.1598
[flaml.automl.logger: 01-06 19:27:31] {2282} INFO - iteration 7, current learner lgbm
[flaml.automl.logger: 01-06 19:27:31] {2466} INFO -  at 0.3s,	estimator lgbm's best error=0.1529,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:27:31] {2282} INFO - iteration 8, current learner lgbm
[flaml.automl.logger: 01-06 19:27:31] {2466} INFO -  at 0.3s,	estimator lgbm's best error=0.1529,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:27:31] {2282} INFO - iteration 9, current learner lgbm
[flaml.automl.logger: 01-06 19:27:31] {2466} INFO -  at 0.4s,	estimator lgbm's best error=0.1529,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:27:31] {2282} INFO - iteration 10, current learner lgbm
[flaml.automl.logger: 01-06 19:27:31] {2466} INFO -  at 0.4s,	estimator lgbm's best error=0.1529,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:27:31] {2282} INFO - iteration 11, current learner rf
[flaml.automl.logger: 01-06 19:27:31] {2466} INFO -  at 0.5s,	estimator rf's best error=0.1765,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:27:31] {2282} INFO - iteration 12, current learner rf
[flaml.automl.logger: 01-06 19:27:31] {2466} INFO -  at 0.5s,	estimator rf's best error=0.1687,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:27:31] {2282} INFO - iteration 13, current learner rf
[flaml.automl.logger: 01-06 19:27:31] {2466} INFO -  at 0.6s,	estimator rf's best error=0.1687,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:27:31] {2282} INFO - iteration 14, current learner extra_tree
[flaml.automl.logger: 01-06 19:27:32] {2466} INFO -  at 0.7s,	estimator extra_tree's best error=0.1882,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:27:32] {2282} INFO - iteration 15, current learner lgbm
[flaml.automl.logger: 01-06 19:27:32] {2466} INFO -  at 0.8s,	estimator lgbm's best error=0.1529,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:27:32] {2282} INFO - iteration 16, current learner extra_tree
[flaml.automl.logger: 01-06 19:27:32] {2466} INFO -  at 0.9s,	estimator extra_tree's best error=0.1882,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:27:32] {2282} INFO - iteration 17, current learner lgbm
[flaml.automl.logger: 01-06 19:27:32] {2466} INFO -  at 1.0s,	estimator lgbm's best error=0.1529,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:27:32] {2282} INFO - iteration 18, current learner extra_tree
[flaml.automl.logger: 01-06 19:27:32] {2466} INFO -  at 1.1s,	estimator extra_tree's best error=0.1676,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:27:32] {2282} INFO - iteration 19, current learner rf
[flaml.automl.logger: 01-06 19:27:32] {2466} INFO -  at 1.2s,	estimator rf's best error=0.1687,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:27:32] {2282} INFO - iteration 20, current learner extra_tree
[flaml.automl.logger: 01-06 19:27:32] {2466} INFO -  at 1.3s,	estimator extra_tree's best error=0.1676,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:27:32] {2282} INFO - iteration 21, current learner lgbm
[flaml.automl.logger: 01-06 19:27:32] {2466} INFO -  at 1.3s,	estimator lgbm's best error=0.1529,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:27:32] {2282} INFO - iteration 22, current learner lgbm
[flaml.automl.logger: 01-06 19:27:32] {2466} INFO -  at 1.5s,	estimator lgbm's best error=0.1529,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:27:32] {2282} INFO - iteration 23, current learner extra_tree
[flaml.automl.logger: 01-06 19:27:32] {2466} INFO -  at 1.6s,	estimator extra_tree's best error=0.1676,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:27:32] {2282} INFO - iteration 24, current learner extra_tree
[flaml.automl.logger: 01-06 19:27:33] {2466} INFO -  at 1.7s,	estimator extra_tree's best error=0.1676,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:27:33] {2282} INFO - iteration 25, current learner lgbm
[flaml.automl.logger: 01-06 19:27:33] {2466} INFO -  at 2.1s,	estimator lgbm's best error=0.1529,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:27:33] {2282} INFO - iteration 26, current learner extra_tree
[flaml.automl.logger: 01-06 19:27:33] {2466} INFO -  at 2.1s,	estimator extra_tree's best error=0.1676,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:27:33] {2282} INFO - iteration 27, current learner extra_tree
[flaml.automl.logger: 01-06 19:27:33] {2466} INFO -  at 2.3s,	estimator extra_tree's best error=0.1676,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:27:33] {2282} INFO - iteration 28, current learner extra_tree
[flaml.automl.logger: 01-06 19:27:33] {2466} INFO -  at 2.4s,	estimator extra_tree's best error=0.1676,	best estimator lgbm's best error=0.1529
[flaml.automl.logger: 01-06 19:27:33] {2282} INFO - iteration 29, current learner lgbm
[flaml.automl.logger: 01-06 19:27:33] {2466} INFO -  at 2.4s,	estimator lgbm's best error=0.1500,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:27:33] {2282} INFO - iteration 30, current learner lgbm
[flaml.automl.logger: 01-06 19:27:33] {2466} INFO -  at 2.5s,	estimator lgbm's best error=0.1500,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:27:33] {2282} INFO - iteration 31, current learner lgbm
[flaml.automl.logger: 01-06 19:27:33] {2466} INFO -  at 2.6s,	estimator lgbm's best error=0.1500,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:27:33] {2282} INFO - iteration 32, current learner extra_tree
[flaml.automl.logger: 01-06 19:27:33] {2466} INFO -  at 2.7s,	estimator extra_tree's best error=0.1676,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:27:33] {2282} INFO - iteration 33, current learner lgbm
[flaml.automl.logger: 01-06 19:27:34] {2466} INFO -  at 3.0s,	estimator lgbm's best error=0.1500,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:27:34] {2282} INFO - iteration 34, current learner rf
[flaml.automl.logger: 01-06 19:27:34] {2466} INFO -  at 3.1s,	estimator rf's best error=0.1617,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:27:34] {2282} INFO - iteration 35, current learner extra_tree
[flaml.automl.logger: 01-06 19:27:34] {2466} INFO -  at 3.2s,	estimator extra_tree's best error=0.1676,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:27:34] {2282} INFO - iteration 36, current learner rf
[flaml.automl.logger: 01-06 19:27:34] {2466} INFO -  at 3.3s,	estimator rf's best error=0.1617,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:27:34] {2282} INFO - iteration 37, current learner rf
[flaml.automl.logger: 01-06 19:27:34] {2466} INFO -  at 3.4s,	estimator rf's best error=0.1617,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:27:34] {2282} INFO - iteration 38, current learner lgbm
[flaml.automl.logger: 01-06 19:27:35] {2466} INFO -  at 3.8s,	estimator lgbm's best error=0.1500,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:27:35] {2282} INFO - iteration 39, current learner rf
[flaml.automl.logger: 01-06 19:27:35] {2466} INFO -  at 3.9s,	estimator rf's best error=0.1585,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:27:35] {2282} INFO - iteration 40, current learner extra_tree
[flaml.automl.logger: 01-06 19:27:35] {2466} INFO -  at 4.0s,	estimator extra_tree's best error=0.1676,	best estimator lgbm's best error=0.1500
[flaml.automl.logger: 01-06 19:27:35] {2282} INFO - iteration 41, current learner lgbm
[flaml.automl.logger: 01-06 19:27:35] {2466} INFO -  at 4.2s,	estimator lgbm's best error=0.1481,	best estimator lgbm's best error=0.1481
[flaml.automl.logger: 01-06 19:27:35] {2282} INFO - iteration 42, current learner extra_tree
[flaml.automl.logger: 01-06 19:27:35] {2466} INFO -  at 4.3s,	estimator extra_tree's best error=0.1676,	best estimator lgbm's best error=0.1481
[flaml.automl.logger: 01-06 19:27:35] {2282} INFO - iteration 43, current learner extra_tree
[flaml.automl.logger: 01-06 19:27:35] {2466} INFO -  at 4.4s,	estimator extra_tree's best error=0.1676,	best estimator lgbm's best error=0.1481
[flaml.automl.logger: 01-06 19:27:35] {2282} INFO - iteration 44, current learner rf
[flaml.automl.logger: 01-06 19:27:36] {2466} INFO -  at 4.7s,	estimator rf's best error=0.1585,	best estimator lgbm's best error=0.1481
[flaml.automl.logger: 01-06 19:27:36] {2282} INFO - iteration 45, current learner lgbm
[flaml.automl.logger: 01-06 19:27:36] {2466} INFO -  at 4.8s,	estimator lgbm's best error=0.1481,	best estimator lgbm's best error=0.1481
[flaml.automl.logger: 01-06 19:27:36] {2282} INFO - iteration 46, current learner extra_tree
[flaml.automl.logger: 01-06 19:27:36] {2466} INFO -  at 4.9s,	estimator extra_tree's best error=0.1676,	best estimator lgbm's best error=0.1481
[flaml.automl.logger: 01-06 19:27:36] {2282} INFO - iteration 47, current learner lgbm
[flaml.automl.logger: 01-06 19:27:36] {2466} INFO -  at 4.9s,	estimator lgbm's best error=0.1481,	best estimator lgbm's best error=0.1481
[flaml.automl.logger: 01-06 19:27:36] {2282} INFO - iteration 48, current learner lgbm
[flaml.automl.logger: 01-06 19:27:36] {2466} INFO -  at 5.0s,	estimator lgbm's best error=0.1481,	best estimator lgbm's best error=0.1481
[flaml.automl.logger: 01-06 19:27:36] {2282} INFO - iteration 49, current learner extra_tree
[flaml.automl.logger: 01-06 19:27:36] {2466} INFO -  at 5.0s,	estimator extra_tree's best error=0.1676,	best estimator lgbm's best error=0.1481
[flaml.automl.logger: 01-06 19:27:36] {2282} INFO - iteration 50, current learner lgbm
[flaml.automl.logger: 01-06 19:27:36] {2466} INFO -  at 5.1s,	estimator lgbm's best error=0.1481,	best estimator lgbm's best error=0.1481
[flaml.automl.logger: 01-06 19:27:36] {2282} INFO - iteration 51, current learner lgbm
[flaml.automl.logger: 01-06 19:27:36] {2466} INFO -  at 5.2s,	estimator lgbm's best error=0.1411,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:27:36] {2282} INFO - iteration 52, current learner lgbm
[flaml.automl.logger: 01-06 19:27:36] {2466} INFO -  at 5.2s,	estimator lgbm's best error=0.1411,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:27:36] {2282} INFO - iteration 53, current learner lgbm
[flaml.automl.logger: 01-06 19:27:36] {2466} INFO -  at 5.3s,	estimator lgbm's best error=0.1411,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:27:36] {2282} INFO - iteration 54, current learner lgbm
[flaml.automl.logger: 01-06 19:27:36] {2466} INFO -  at 5.4s,	estimator lgbm's best error=0.1411,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:27:36] {2282} INFO - iteration 55, current learner lgbm
[flaml.automl.logger: 01-06 19:27:36] {2466} INFO -  at 5.4s,	estimator lgbm's best error=0.1411,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:27:36] {2282} INFO - iteration 56, current learner lgbm
[flaml.automl.logger: 01-06 19:27:36] {2466} INFO -  at 5.5s,	estimator lgbm's best error=0.1411,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:27:36] {2282} INFO - iteration 57, current learner lgbm
[flaml.automl.logger: 01-06 19:27:36] {2466} INFO -  at 5.6s,	estimator lgbm's best error=0.1411,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:27:36] {2282} INFO - iteration 58, current learner lgbm
[flaml.automl.logger: 01-06 19:27:36] {2466} INFO -  at 5.7s,	estimator lgbm's best error=0.1411,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:27:36] {2282} INFO - iteration 59, current learner lgbm
[flaml.automl.logger: 01-06 19:27:37] {2466} INFO -  at 5.7s,	estimator lgbm's best error=0.1411,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:27:37] {2282} INFO - iteration 60, current learner lgbm
[flaml.automl.logger: 01-06 19:27:37] {2466} INFO -  at 5.9s,	estimator lgbm's best error=0.1411,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:27:37] {2282} INFO - iteration 61, current learner lgbm
[flaml.automl.logger: 01-06 19:27:37] {2466} INFO -  at 5.9s,	estimator lgbm's best error=0.1411,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:27:37] {2282} INFO - iteration 62, current learner lgbm
[flaml.automl.logger: 01-06 19:27:37] {2466} INFO -  at 6.0s,	estimator lgbm's best error=0.1411,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:27:37] {2282} INFO - iteration 63, current learner lgbm
[flaml.automl.logger: 01-06 19:27:37] {2466} INFO -  at 6.1s,	estimator lgbm's best error=0.1411,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:27:37] {2282} INFO - iteration 64, current learner lgbm
[flaml.automl.logger: 01-06 19:27:37] {2466} INFO -  at 6.2s,	estimator lgbm's best error=0.1411,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:27:37] {2282} INFO - iteration 65, current learner lgbm
[flaml.automl.logger: 01-06 19:27:37] {2466} INFO -  at 6.2s,	estimator lgbm's best error=0.1411,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:27:37] {2282} INFO - iteration 66, current learner lgbm
[flaml.automl.logger: 01-06 19:27:37] {2466} INFO -  at 6.3s,	estimator lgbm's best error=0.1411,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:27:37] {2282} INFO - iteration 67, current learner lgbm
[flaml.automl.logger: 01-06 19:27:37] {2466} INFO -  at 6.4s,	estimator lgbm's best error=0.1411,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:27:37] {2282} INFO - iteration 68, current learner lgbm
[flaml.automl.logger: 01-06 19:27:37] {2466} INFO -  at 6.4s,	estimator lgbm's best error=0.1411,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:27:37] {2282} INFO - iteration 69, current learner rf
[flaml.automl.logger: 01-06 19:27:37] {2466} INFO -  at 6.6s,	estimator rf's best error=0.1529,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:27:37] {2282} INFO - iteration 70, current learner rf
[flaml.automl.logger: 01-06 19:27:37] {2466} INFO -  at 6.7s,	estimator rf's best error=0.1529,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:27:37] {2282} INFO - iteration 71, current learner extra_tree
[flaml.automl.logger: 01-06 19:27:38] {2466} INFO -  at 6.7s,	estimator extra_tree's best error=0.1617,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:27:38] {2282} INFO - iteration 72, current learner rf
[flaml.automl.logger: 01-06 19:27:38] {2466} INFO -  at 6.9s,	estimator rf's best error=0.1529,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:27:38] {2282} INFO - iteration 73, current learner rf
[flaml.automl.logger: 01-06 19:27:38] {2466} INFO -  at 7.0s,	estimator rf's best error=0.1529,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:27:38] {2282} INFO - iteration 74, current learner lgbm
[flaml.automl.logger: 01-06 19:27:38] {2466} INFO -  at 7.1s,	estimator lgbm's best error=0.1411,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:27:38] {2282} INFO - iteration 75, current learner lgbm
[flaml.automl.logger: 01-06 19:27:38] {2466} INFO -  at 7.2s,	estimator lgbm's best error=0.1411,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:27:38] {2282} INFO - iteration 76, current learner rf
[flaml.automl.logger: 01-06 19:27:38] {2466} INFO -  at 7.3s,	estimator rf's best error=0.1529,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:27:38] {2282} INFO - iteration 77, current learner lgbm
[flaml.automl.logger: 01-06 19:27:38] {2466} INFO -  at 7.4s,	estimator lgbm's best error=0.1411,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:27:38] {2282} INFO - iteration 78, current learner lgbm
[flaml.automl.logger: 01-06 19:27:38] {2466} INFO -  at 7.4s,	estimator lgbm's best error=0.1411,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:27:38] {2282} INFO - iteration 79, current learner extra_tree
[flaml.automl.logger: 01-06 19:27:38] {2466} INFO -  at 7.5s,	estimator extra_tree's best error=0.1617,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:27:38] {2282} INFO - iteration 80, current learner lgbm
[flaml.automl.logger: 01-06 19:27:38] {2466} INFO -  at 7.6s,	estimator lgbm's best error=0.1411,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:27:38] {2282} INFO - iteration 81, current learner rf
[flaml.automl.logger: 01-06 19:27:39] {2466} INFO -  at 7.7s,	estimator rf's best error=0.1529,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:27:39] {2282} INFO - iteration 82, current learner rf
[flaml.automl.logger: 01-06 19:27:39] {2466} INFO -  at 7.8s,	estimator rf's best error=0.1529,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:27:39] {2282} INFO - iteration 83, current learner rf
[flaml.automl.logger: 01-06 19:27:39] {2466} INFO -  at 7.9s,	estimator rf's best error=0.1529,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:27:39] {2282} INFO - iteration 84, current learner lgbm
[flaml.automl.logger: 01-06 19:27:39] {2466} INFO -  at 8.0s,	estimator lgbm's best error=0.1411,	best estimator lgbm's best error=0.1411
[flaml.automl.logger: 01-06 19:27:39] {2282} INFO - iteration 85, current learner rf
[flaml.automl.logger: 01-06 19:27:39] {2466} INFO -  at 8.1s,	estimator rf's best error=0.1463,	best estimator lgbm's best error=0.1411

INFO:flaml.tune.searcher.blendsearch:No low-cost partial config given to the search algorithm. For cost-frugal search, consider providing low-cost values for cost-related hps via 'low_cost_partial_config'. More info can be found at https://microsoft.github.io/FLAML/docs/FAQ#about-low_cost_partial_config-in-tune

[flaml.automl.logger: 01-06 19:27:46] {2466} INFO -  at 15.1s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:46] {2282} INFO - iteration 154, current learner lrl1
[flaml.automl.logger: 01-06 19:27:46] {2466} INFO -  at 15.2s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:46] {2282} INFO - iteration 155, current learner lrl1
[flaml.automl.logger: 01-06 19:27:46] {2466} INFO -  at 15.2s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:46] {2282} INFO - iteration 156, current learner lrl1
[flaml.automl.logger: 01-06 19:27:46] {2466} INFO -  at 15.3s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:46] {2282} INFO - iteration 157, current learner lrl1
[flaml.automl.logger: 01-06 19:27:46] {2466} INFO -  at 15.4s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:46] {2282} INFO - iteration 158, current learner lrl1
[flaml.automl.logger: 01-06 19:27:46] {2466} INFO -  at 15.5s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:46] {2282} INFO - iteration 159, current learner lrl1
[flaml.automl.logger: 01-06 19:27:46] {2466} INFO -  at 15.5s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:46] {2282} INFO - iteration 160, current learner lrl1
[flaml.automl.logger: 01-06 19:27:46] {2466} INFO -  at 15.6s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:46] {2282} INFO - iteration 161, current learner lrl1
[flaml.automl.logger: 01-06 19:27:47] {2466} INFO -  at 15.7s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:47] {2282} INFO - iteration 162, current learner lrl1
[flaml.automl.logger: 01-06 19:27:47] {2466} INFO -  at 15.8s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:47] {2282} INFO - iteration 163, current learner lrl1
[flaml.automl.logger: 01-06 19:27:47] {2466} INFO -  at 15.8s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:47] {2282} INFO - iteration 164, current learner extra_tree
[flaml.automl.logger: 01-06 19:27:47] {2466} INFO -  at 16.0s,	estimator extra_tree's best error=0.1617,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:47] {2282} INFO - iteration 165, current learner lrl1
[flaml.automl.logger: 01-06 19:27:47] {2466} INFO -  at 16.0s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:47] {2282} INFO - iteration 166, current learner lrl1
[flaml.automl.logger: 01-06 19:27:47] {2466} INFO -  at 16.1s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:47] {2282} INFO - iteration 167, current learner lrl1
[flaml.automl.logger: 01-06 19:27:47] {2466} INFO -  at 16.2s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:47] {2282} INFO - iteration 168, current learner lgbm
[flaml.automl.logger: 01-06 19:27:47] {2466} INFO -  at 16.5s,	estimator lgbm's best error=0.1273,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:47] {2282} INFO - iteration 169, current learner lgbm
[flaml.automl.logger: 01-06 19:27:49] {2466} INFO -  at 17.9s,	estimator lgbm's best error=0.1273,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:49] {2282} INFO - iteration 170, current learner lgbm
[flaml.automl.logger: 01-06 19:27:49] {2466} INFO -  at 18.1s,	estimator lgbm's best error=0.1273,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:49] {2282} INFO - iteration 171, current learner lrl1
[flaml.automl.logger: 01-06 19:27:49] {2466} INFO -  at 18.1s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:49] {2282} INFO - iteration 172, current learner lrl1
[flaml.automl.logger: 01-06 19:27:49] {2466} INFO -  at 18.2s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:49] {2282} INFO - iteration 173, current learner lrl1
[flaml.automl.logger: 01-06 19:27:49] {2466} INFO -  at 18.3s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:49] {2282} INFO - iteration 174, current learner lrl1
[flaml.automl.logger: 01-06 19:27:49] {2466} INFO -  at 18.4s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:49] {2282} INFO - iteration 175, current learner lrl1
[flaml.automl.logger: 01-06 19:27:49] {2466} INFO -  at 18.5s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:49] {2282} INFO - iteration 176, current learner lrl1
[flaml.automl.logger: 01-06 19:27:49] {2466} INFO -  at 18.5s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:49] {2282} INFO - iteration 177, current learner lrl1
[flaml.automl.logger: 01-06 19:27:49] {2466} INFO -  at 18.6s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:49] {2282} INFO - iteration 178, current learner lrl1
[flaml.automl.logger: 01-06 19:27:50] {2466} INFO -  at 18.7s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:50] {2282} INFO - iteration 179, current learner lrl1
[flaml.automl.logger: 01-06 19:27:50] {2466} INFO -  at 18.8s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:50] {2282} INFO - iteration 180, current learner lrl1
[flaml.automl.logger: 01-06 19:27:50] {2466} INFO -  at 18.9s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:50] {2282} INFO - iteration 181, current learner rf
[flaml.automl.logger: 01-06 19:27:50] {2466} INFO -  at 19.1s,	estimator rf's best error=0.1463,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:50] {2282} INFO - iteration 182, current learner lgbm
[flaml.automl.logger: 01-06 19:27:50] {2466} INFO -  at 19.2s,	estimator lgbm's best error=0.1273,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:50] {2282} INFO - iteration 183, current learner lrl1
[flaml.automl.logger: 01-06 19:27:50] {2466} INFO -  at 19.2s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:50] {2282} INFO - iteration 184, current learner lrl1
[flaml.automl.logger: 01-06 19:27:50] {2466} INFO -  at 19.3s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:50] {2282} INFO - iteration 185, current learner lgbm
[flaml.automl.logger: 01-06 19:27:50] {2466} INFO -  at 19.3s,	estimator lgbm's best error=0.1273,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:50] {2282} INFO - iteration 186, current learner lrl1
[flaml.automl.logger: 01-06 19:27:50] {2466} INFO -  at 19.4s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:50] {2282} INFO - iteration 187, current learner lgbm
[flaml.automl.logger: 01-06 19:27:50] {2466} INFO -  at 19.5s,	estimator lgbm's best error=0.1273,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:50] {2282} INFO - iteration 188, current learner rf
[flaml.automl.logger: 01-06 19:27:50] {2466} INFO -  at 19.6s,	estimator rf's best error=0.1463,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:50] {2282} INFO - iteration 189, current learner lrl1
[flaml.automl.logger: 01-06 19:27:50] {2466} INFO -  at 19.7s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:50] {2282} INFO - iteration 190, current learner lgbm
[flaml.automl.logger: 01-06 19:27:51] {2466} INFO -  at 19.7s,	estimator lgbm's best error=0.1273,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:51] {2282} INFO - iteration 191, current learner lrl1
[flaml.automl.logger: 01-06 19:27:51] {2466} INFO -  at 19.8s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:51] {2282} INFO - iteration 192, current learner lrl1
[flaml.automl.logger: 01-06 19:27:51] {2466} INFO -  at 19.8s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:51] {2282} INFO - iteration 193, current learner lrl1
[flaml.automl.logger: 01-06 19:27:51] {2466} INFO -  at 19.9s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:51] {2282} INFO - iteration 194, current learner rf
[flaml.automl.logger: 01-06 19:27:51] {2466} INFO -  at 20.0s,	estimator rf's best error=0.1463,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:51] {2282} INFO - iteration 195, current learner lgbm
[flaml.automl.logger: 01-06 19:27:51] {2466} INFO -  at 20.1s,	estimator lgbm's best error=0.1273,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:51] {2282} INFO - iteration 196, current learner lrl1
[flaml.automl.logger: 01-06 19:27:51] {2466} INFO -  at 20.2s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:51] {2282} INFO - iteration 197, current learner lrl1
[flaml.automl.logger: 01-06 19:27:51] {2466} INFO -  at 20.2s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:51] {2282} INFO - iteration 198, current learner lrl1
[flaml.automl.logger: 01-06 19:27:51] {2466} INFO -  at 20.3s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:51] {2282} INFO - iteration 199, current learner lrl1
[flaml.automl.logger: 01-06 19:27:51] {2466} INFO -  at 20.3s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:51] {2282} INFO - iteration 200, current learner lgbm
[flaml.automl.logger: 01-06 19:27:51] {2466} INFO -  at 20.4s,	estimator lgbm's best error=0.1273,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:51] {2282} INFO - iteration 201, current learner lgbm
[flaml.automl.logger: 01-06 19:27:51] {2466} INFO -  at 20.5s,	estimator lgbm's best error=0.1273,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:51] {2282} INFO - iteration 202, current learner lrl1
[flaml.automl.logger: 01-06 19:27:51] {2466} INFO -  at 20.6s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:51] {2282} INFO - iteration 203, current learner lrl1
[flaml.automl.logger: 01-06 19:27:51] {2466} INFO -  at 20.6s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:51] {2282} INFO - iteration 204, current learner lrl1
[flaml.automl.logger: 01-06 19:27:52] {2466} INFO -  at 20.7s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:52] {2282} INFO - iteration 205, current learner lrl1
[flaml.automl.logger: 01-06 19:27:52] {2466} INFO -  at 20.7s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:52] {2282} INFO - iteration 206, current learner lrl1
[flaml.automl.logger: 01-06 19:27:52] {2466} INFO -  at 20.8s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:52] {2282} INFO - iteration 207, current learner lrl1
[flaml.automl.logger: 01-06 19:27:52] {2466} INFO -  at 20.8s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:52] {2282} INFO - iteration 208, current learner extra_tree
[flaml.automl.logger: 01-06 19:27:52] {2466} INFO -  at 20.9s,	estimator extra_tree's best error=0.1617,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:52] {2282} INFO - iteration 209, current learner lrl1
[flaml.automl.logger: 01-06 19:27:52] {2466} INFO -  at 21.0s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:52] {2282} INFO - iteration 210, current learner lrl1
[flaml.automl.logger: 01-06 19:27:52] {2466} INFO -  at 21.0s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:52] {2282} INFO - iteration 211, current learner lrl1
[flaml.automl.logger: 01-06 19:27:52] {2466} INFO -  at 21.1s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:52] {2282} INFO - iteration 212, current learner lrl1
[flaml.automl.logger: 01-06 19:27:52] {2466} INFO -  at 21.1s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:52] {2282} INFO - iteration 213, current learner lrl1
[flaml.automl.logger: 01-06 19:27:52] {2466} INFO -  at 21.2s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:52] {2282} INFO - iteration 214, current learner extra_tree
[flaml.automl.logger: 01-06 19:27:52] {2466} INFO -  at 21.3s,	estimator extra_tree's best error=0.1617,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:52] {2282} INFO - iteration 215, current learner lrl1
[flaml.automl.logger: 01-06 19:27:52] {2466} INFO -  at 21.3s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:52] {2282} INFO - iteration 216, current learner lgbm
[flaml.automl.logger: 01-06 19:27:52] {2466} INFO -  at 21.4s,	estimator lgbm's best error=0.1273,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:52] {2282} INFO - iteration 217, current learner lgbm
[flaml.automl.logger: 01-06 19:27:52] {2466} INFO -  at 21.5s,	estimator lgbm's best error=0.1273,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:52] {2282} INFO - iteration 218, current learner lgbm
[flaml.automl.logger: 01-06 19:27:52] {2466} INFO -  at 21.6s,	estimator lgbm's best error=0.1273,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:52] {2282} INFO - iteration 219, current learner lrl1
[flaml.automl.logger: 01-06 19:27:52] {2466} INFO -  at 21.6s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:52] {2282} INFO - iteration 220, current learner lgbm
[flaml.automl.logger: 01-06 19:27:53] {2466} INFO -  at 21.7s,	estimator lgbm's best error=0.1273,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:53] {2282} INFO - iteration 221, current learner lrl1
[flaml.automl.logger: 01-06 19:27:53] {2466} INFO -  at 21.8s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:53] {2282} INFO - iteration 222, current learner lrl1
[flaml.automl.logger: 01-06 19:27:53] {2466} INFO -  at 21.8s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:53] {2282} INFO - iteration 223, current learner lgbm
[flaml.automl.logger: 01-06 19:27:53] {2466} INFO -  at 21.9s,	estimator lgbm's best error=0.1273,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:53] {2282} INFO - iteration 224, current learner lgbm
[flaml.automl.logger: 01-06 19:27:53] {2466} INFO -  at 22.0s,	estimator lgbm's best error=0.1273,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:53] {2282} INFO - iteration 225, current learner rf
[flaml.automl.logger: 01-06 19:27:53] {2466} INFO -  at 22.2s,	estimator rf's best error=0.1463,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:53] {2282} INFO - iteration 226, current learner lgbm
[flaml.automl.logger: 01-06 19:27:53] {2466} INFO -  at 22.2s,	estimator lgbm's best error=0.1273,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:53] {2282} INFO - iteration 227, current learner lrl1
[flaml.automl.logger: 01-06 19:27:53] {2466} INFO -  at 22.3s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:53] {2282} INFO - iteration 228, current learner rf
[flaml.automl.logger: 01-06 19:27:53] {2466} INFO -  at 22.4s,	estimator rf's best error=0.1429,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:53] {2282} INFO - iteration 229, current learner lrl1
[flaml.automl.logger: 01-06 19:27:53] {2466} INFO -  at 22.4s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:53] {2282} INFO - iteration 230, current learner lrl1
[flaml.automl.logger: 01-06 19:27:53] {2466} INFO -  at 22.5s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:53] {2282} INFO - iteration 231, current learner lrl1
[flaml.automl.logger: 01-06 19:27:53] {2466} INFO -  at 22.5s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:53] {2282} INFO - iteration 232, current learner lrl1
[flaml.automl.logger: 01-06 19:27:53] {2466} INFO -  at 22.6s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:53] {2282} INFO - iteration 233, current learner lrl1
[flaml.automl.logger: 01-06 19:27:53] {2466} INFO -  at 22.6s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:53] {2282} INFO - iteration 234, current learner lrl1
[flaml.automl.logger: 01-06 19:27:54] {2466} INFO -  at 22.7s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:54] {2282} INFO - iteration 235, current learner lrl1
[flaml.automl.logger: 01-06 19:27:54] {2466} INFO -  at 22.7s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:54] {2282} INFO - iteration 236, current learner lrl1
[flaml.automl.logger: 01-06 19:27:54] {2466} INFO -  at 22.8s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:54] {2282} INFO - iteration 237, current learner lgbm
[flaml.automl.logger: 01-06 19:27:54] {2466} INFO -  at 22.9s,	estimator lgbm's best error=0.1273,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:54] {2282} INFO - iteration 238, current learner lrl1
[flaml.automl.logger: 01-06 19:27:54] {2466} INFO -  at 23.0s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:54] {2282} INFO - iteration 239, current learner lrl1
[flaml.automl.logger: 01-06 19:27:54] {2466} INFO -  at 23.0s,	estimator lrl1's best error=0.2663,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:54] {2282} INFO - iteration 240, current learner lgbm
[flaml.automl.logger: 01-06 19:27:54] {2466} INFO -  at 23.1s,	estimator lgbm's best error=0.1273,	best estimator lgbm's best error=0.1273
[flaml.automl.logger: 01-06 19:27:54] {2282} INFO - iteration 241, current learner lrl1

**1) Classic ML Full vs Light (with Time-budget)**

In [ ]:
# @title
import os, time, psutil, joblib, warnings, random
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split, ParameterSampler
from sklearn.metrics import (
    accuracy_score, roc_auc_score, f1_score, precision_score,
    recall_score, log_loss, confusion_matrix, classification_report
)
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.base import clone  # ADDED THIS LINE

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.neural_network import MLPClassifier

# Optional libs
XGB_AVAILABLE = False
LGB_AVAILABLE = False
CAT_AVAILABLE = False

try:
    from xgboost import XGBClassifier
    XGB_AVAILABLE = True
except Exception:
    pass

try:
    import lightgbm as lgb
    LGB_AVAILABLE = True
except Exception:
    pass

try:
    from catboost import CatBoostClassifier
    CAT_AVAILABLE = True
except Exception:
    pass


def set_seed(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)


def get_system_ram():
    mem = psutil.virtual_memory()
    total = mem.total / (1024**3)
    used = mem.used / (1024**3)
    free = mem.available / (1024**3)
    percent = mem.percent
    return total, used, free, percent


def compute_metrics(y_true, y_pred, y_proba):
    acc = accuracy_score(y_true, y_pred)
    auc = roc_auc_score(y_true, y_proba)
    f1 = f1_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred)
    recall = recall_score(y_true, y_pred)
    ll = log_loss(y_true, np.vstack([1 - y_proba, y_proba]).T)
    cm = confusion_matrix(y_true, y_pred)
    return acc, auc, f1, precision, recall, ll, cm


def predict_proba_safe(model, X):
    if hasattr(model, "predict_proba"):
        return model.predict_proba(X)[:, 1]
    if hasattr(model, "decision_function"):
        s = model.decision_function(X)
        return 1 / (1 + np.exp(-s))
    # fallback: hard predictions -> pseudo probabilities
    p = model.predict(X)
    return p.astype(float)


def print_block(title, acc, auc, f1, precision, recall, ll, cm, y_true=None, y_pred=None):
    print(f"\n=== {title} (Test) ===")
    print(f"Accuracy:  {acc*100:.2f}%")
    print(f"AUC:       {auc*100:.2f}%")
    print(f"F1 Score:  {f1*100:.2f}%")
    print(f"Precision: {precision*100:.2f}%")
    print(f"Recall:    {recall*100:.2f}%")
    print(f"LogLoss:   {ll:.2f}")
    print("\nConfusion Matrix:")
    print(cm)
    if y_true is not None and y_pred is not None:
        print("\nClassification Report:")
        print(classification_report(y_true, y_pred))


# -------------------------
# Model factory + search spaces
# -------------------------
def build_ml_candidates(seed=42, mode="full"):
    """
    mode="light": fixed, fast settings
    mode="full" : timed random search will be used for hyperparameter tuning
    """
    candidates = {}

    # Logistic Regression (with scaling)
    candidates["LogReg"] = {
        "base": Pipeline([("scaler", StandardScaler()),
                          ("clf", LogisticRegression(max_iter=2000, n_jobs=-1))]),
        "space": {
            "clf__C": np.logspace(-2, 2, 30),
            "clf__penalty": ["l2"],  # l1 via liblinear is possible, but keep it stable
            "clf__solver": ["lbfgs", "liblinear"]
        }
    }

    # RandomForest
    rf_base = RandomForestClassifier(random_state=seed, n_jobs=-1)
    candidates["RF"] = {
        "base": rf_base,
        "space": {
            "n_estimators": [200, 400, 800, 1200] if mode == "full" else [300],
            "max_depth": [None, 3, 5, 7, 10],
            "max_features": ["sqrt", "log2", None],
            "min_samples_split": [2, 5, 10],
            "min_samples_leaf": [1, 2, 4],
            "bootstrap": [True, False]
        }
    }

    # ExtraTrees
    et_base = ExtraTreesClassifier(random_state=seed, n_jobs=-1)
    candidates["ExtraTrees"] = {
        "base": et_base,
        "space": {
            "n_estimators": [300, 600, 1000, 1500] if mode == "full" else [600],
            "max_depth": [None, 3, 5, 7, 10],
            "max_features": ["sqrt", "log2", None],
            "min_samples_split": [2, 5, 10],
            "min_samples_leaf": [1, 2, 4]
        }
    }

    # MLP (with scaling)
    candidates["MLP_sklearn"] = {
        "base": Pipeline([
            ("scaler", StandardScaler()),
            ("clf", MLPClassifier(
                activation="relu",
                alpha=1e-4,
                max_iter=300 if mode == "full" else 150,
                random_state=seed
            ))
        ]),
        "space": {
            "clf__hidden_layer_sizes": [(32,), (64,), (64, 32), (128, 64)],
            "clf__alpha": [1e-5, 1e-4, 1e-3, 1e-2],
            "clf__learning_rate_init": [1e-4, 3e-4, 1e-3, 3e-3]
        }
    }

    # XGBoost
    if XGB_AVAILABLE:
        candidates["XGBoost"] = {
            "base": XGBClassifier(
                eval_metric="logloss",
                n_jobs=-1,
                random_state=seed,
                tree_method="hist"
            ),
            "space": {
                "n_estimators": [150, 300, 600, 1000] if mode == "full" else [300],
                "max_depth": [2, 3, 4, 5, 6],
                "learning_rate": [0.01, 0.03, 0.05, 0.1, 0.2],
                "subsample": [0.7, 0.85, 1.0],
                "colsample_bytree": [0.7, 0.85, 1.0],
                "min_child_weight": [1, 3, 5, 10],
                "reg_lambda": [0.5, 1.0, 2.0, 5.0]
            }
        }

    # LightGBM
    if LGB_AVAILABLE:
        candidates["LightGBM"] = {
            "base": lgb.LGBMClassifier(
                random_state=seed,
                n_jobs=-1,
                verbose=-1
            ),
            "space": {
                "n_estimators": [200, 500, 900, 1500] if mode == "full" else [400],
                "learning_rate": [0.01, 0.03, 0.05, 0.1, 0.2],
                "num_leaves": [7, 15, 31, 63],
                "min_child_samples": [5, 10, 20, 40],
                "subsample": [0.7, 0.85, 1.0],
                "colsample_bytree": [0.7, 0.85, 1.0],
                "reg_lambda": [0.0, 1.0, 3.0, 10.0]
            }
        }

    # CatBoost
    if CAT_AVAILABLE:
        candidates["CatBoost"] = {
            "base": CatBoostClassifier(
                loss_function="Logloss",
                verbose=False,
                random_seed=seed,
                allow_writing_files=False
            ),
            "space": {
                "iterations": [300, 800, 1500, 2500] if mode == "full" else [600],
                "learning_rate": [0.01, 0.03, 0.05, 0.1, 0.2],
                "depth": [3, 4, 5, 6, 7, 8],
                "l2_leaf_reg": [1, 3, 5, 10]
            }
        }

    return candidates


def timed_random_search_one_model(
    name, base_model, param_space,
    X_train, y_train, X_val, y_val,
    time_left_s, seed=42, max_trials_cap=10_000
):
    """
    For a single model, try random parameter configurations for up to time_left_s seconds.
    Returns the best validation F1.
    """
    t_start = time.time()
    best = {"f1": -1, "params": None, "fit_time": 0.0}

    # Parameter samples (with a very large upper cap)
    sampler = ParameterSampler(param_space, n_iter=max_trials_cap, random_state=seed)

    tried = 0
    for params in sampler:
        if time.time() - t_start >= time_left_s:
            break

        model = clone(base_model)
        try:
            model.set_params(**params)
        except Exception:
            continue

        t0 = time.time()
        try:
            model.fit(X_train, y_train)
            fit_t = time.time() - t0

            proba = predict_proba_safe(model, X_val)
            pred = (proba >= 0.5).astype(int)
            f1 = f1_score(y_val, pred)

            tried += 1
            if f1 > best["f1"]:
                best = {"f1": f1, "params": params, "fit_time": fit_t}
        except Exception:
            continue

    return best, tried


def run_classic_ml_full_light(
    clean_csv_path="heart_merged_clean.csv",
    target_col="target",
    test_size=0.2,
    seed=42,
    time_budget_full=180,
    time_budget_light=60,
    holdout_frac_for_tuning=0.2
):
    set_seed(seed)

    # load
    df = pd.read_csv(clean_csv_path)
    X = df.drop(columns=[target_col])
    y = df[target_col].astype(int).values

    # outer split (train/test)
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=test_size, random_state=seed, stratify=y
    )

    # inner split (train/val) for fair tuning, without touching test
    X_tr, X_val, y_tr, y_val = train_test_split(
        X_train, y_train,
        test_size=holdout_frac_for_tuning,
        random_state=seed,
        stratify=y_train
    )

    def run_mode(mode_name, time_budget_s):
        # RAM + time start
        process = psutil.Process(os.getpid())
        start_proc_mem = process.memory_info().rss / (1024 * 1024)
        start_sys_total, start_sys_used, start_sys_free, start_sys_percent = get_system_ram()
        start_time = time.time()

        candidates = build_ml_candidates(seed=seed, mode=mode_name)
        results = []

        # 1) Baseline (fit each model once with default/fast settings, measure val F1)
        baseline_scores = []
        for name, item in candidates.items():
            model = clone(item["base"])

            # In light mode, the base is already constrained (fewer trees, etc.).
            # In full mode, base parameters remain default and will be improved by random search.
            t0 = time.time()
            try:
                model.fit(X_tr, y_tr)
                fit_t = time.time() - t0
                proba = predict_proba_safe(model, X_val)
                pred = (proba >= 0.5).astype(int)
                f1v = f1_score(y_val, pred)
            except Exception:
                fit_t = np.nan
                f1v = -1

            baseline_scores.append((name, f1v, fit_t))
            results.append({
                "model": name,
                "phase": "baseline",
                "val_f1": f1v,
                "params": None,
                "fit_time_s": fit_t
            })

        baseline_scores.sort(key=lambda x: x[1], reverse=True)

        # 2) Full mode: timed random search only on top-K models (fairness + speed)
        best_global = {"model": None, "val_f1": -1, "params": None}
        for name, f1v, _ in baseline_scores:
            if f1v > best_global["val_f1"]:
                best_global = {"model": name, "val_f1": f1v, "params": None}

        if mode_name == "full":
            # Split the budget across top-3 models (top3 is usually enough)
            topK = [x[0] for x in baseline_scores[:3]]
            remaining = time_budget_s - (time.time() - start_time)
            remaining = max(0.0, remaining)

            # Equal share per model + small buffer
            per_model_budget = max(5.0, remaining / max(1, len(topK)))

            for name in topK:
                remaining = time_budget_s - (time.time() - start_time)
                if remaining <= 3:
                    break

                item = candidates[name]
                budget = min(per_model_budget, remaining)

                best, tried = timed_random_search_one_model(
                    name=name,
                    base_model=item["base"],
                    param_space=item["space"],
                    X_train=X_tr, y_train=y_tr,
                    X_val=X_val, y_val=y_val,
                    time_left_s=budget,
                    seed=seed
                )

                results.append({
                    "model": name,
                    "phase": "timed_search",
                    "val_f1": best["f1"],
                    "params": best["params"],
                    "fit_time_s": best["fit_time"],
                    "trials": tried
                })

                if best["f1"] > best_global["val_f1"]:
                    best_global = {"model": name, "val_f1": best["f1"], "params": best["params"]}

        # 3) Retrain best config on full training set (X_train) and evaluate on test
        best_name = best_global["model"]
        best_params = best_global["params"]

        best_model = clone(candidates[best_name]["base"])
        if best_params is not None:
            try:
                best_model.set_params(**best_params)
            except Exception:
                pass

        # retrain on full training
        best_model.fit(X_train, y_train)

        test_proba = predict_proba_safe(best_model, X_test)
        test_pred = (test_proba >= 0.5).astype(int)
        acc, auc, f1, precision, recall, ll, cm = compute_metrics(y_test, test_pred, test_proba)

        # end measures
        end_time = time.time()
        end_proc_mem = process.memory_info().rss / (1024 * 1024)
        end_sys_total, end_sys_used, end_sys_free, end_sys_percent = get_system_ram()

        runtime = end_time - start_time
        proc_mem_usage = end_proc_mem - start_proc_mem
        sys_used_diff = end_sys_used - start_sys_used

        # save model
        out_file = f"classicML_{mode_name}_best_{best_name}.pkl"
        joblib.dump(best_model, out_file)
        model_size_mb = os.path.getsize(out_file) / (1024 * 1024)

        print_block(
            f"Classic ML {mode_name.upper()} Best = {best_name}",
            acc, auc, f1, precision, recall, ll, cm,
            y_true=y_test, y_pred=test_pred
        )

        print("\n=== Summary ===")
        print(f"Runtime: {runtime:.2f} seconds (Budget={time_budget_s}s)")
        print(f"Python process RAM usage: {proc_mem_usage:.2f} MB")

        print("\n=== System RAM Usage ===")
        print(f"Total RAM:         {end_sys_total:.2f} GB")
        print(f"Used RAM:          {end_sys_used:.2f} GB")
        print(f"Available RAM:     {end_sys_free:.2f} GB")
        print(f"RAM utilization:   {end_sys_percent:.1f}%")
        print(f"RAM increase during run: {sys_used_diff:.2f} GB")

        print("\n=== Best Model Artifact ===")
        print(f"Model: {best_name}")
        print(f"Model path: {out_file}")
        print(f"Model size: {model_size_mb:.4f} MB")
        if best_params is not None:
            print(f"Best params: {best_params}")

        results_df = pd.DataFrame(results).sort_values(["phase", "val_f1"], ascending=[True, False])
        return out_file, results_df

    # Run Light then Full
    light_file, light_df = run_mode("light", time_budget_light)
    full_file, full_df = run_mode("full", time_budget_full)

    print("\n=== (Val) Leaderboard Summary (LIGHT) ===")
    display(light_df.head(30))
    print("\n=== (Val) Leaderboard Summary (FULL) ===")
    display(full_df.head(30))

    return {
        "light_model": light_file,
        "full_model": full_file,
        "light_trials": light_df,
        "full_trials": full_df
    }

In [ ]:
# @title
# preprocess -> heart_merged_clean.csv ready
out = run_classic_ml_full_light(
    clean_csv_path="heart_merged_clean.csv",
    target_col="target",
    seed=42,
    time_budget_full=180,
    time_budget_light=60
)

=== Classic ML LIGHT Best = XGBoost (Test) ===
Accuracy:  80.43%
AUC:       87.86%
F1 Score:  83.02%
Precision: 80.00%
Recall:    86.27%
LogLoss:   0.53

Confusion Matrix:
[[60 22]
 [14 88]]

Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.73      0.77        82
           1       0.80      0.86      0.83       102

    accuracy                           0.80       184
   macro avg       0.81      0.80      0.80       184
weighted avg       0.80      0.80      0.80       184


=== Özet Bilgiler ===
Koşum Süresi: 8.60 saniye (Budget=60s)
Python İşlemi RAM Kullanımı: 14.63 MB

=== Sistem Genel RAM Kullanımı ===
Toplam RAM:         12.67 GB
Kullanılan RAM:     1.29 GB
Boş RAM:            11.06 GB
RAM Kullanım Oranı: 12.7%
Koşum sırasında artan RAM: 0.26 GB

=== En İyi Model Dosyası ===
Model: XGBoost
Model yolu: classicML_light_best_XGBoost.pkl
Model boyutu: 0.1840 MB

=== Classic ML FULL Best = XGBoost (Test) ===
Accuracy:  84.78%
AUC:       91.79%
F1 Score:  86.67%
Precision: 84.26%
Recall:    89.22%
LogLoss:   0.37

Confusion Matrix:
[[65 17]
 [11 91]]

Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.79      0.82        82
           1       0.84      0.89      0.87       102

    accuracy                           0.85       184
   macro avg       0.85      0.84      0.84       184
weighted avg       0.85      0.85      0.85       184


=== Özet Bilgiler ===
Koşum Süresi: 180.50 saniye (Budget=180s)
Python İşlemi RAM Kullanımı: 30.07 MB

=== Sistem Genel RAM Kullanımı ===
Toplam RAM:         12.67 GB
Kullanılan RAM:     1.39 GB
Boş RAM:            10.97 GB
RAM Kullanım Oranı: 13.4%
Koşum sırasında artan RAM: 0.09 GB

=== En İyi Model Dosyası ===
Model: XGBoost
Model yolu: classicML_full_best_XGBoost.pkl
Model boyutu: 0.1325 MB
Best params: {'subsample': 1.0, 'reg_lambda': 1.0, 'n_estimators': 150, 'min_child_weight': 1, 'max_depth': 2, 'learning_rate': 0.05, 'colsample_bytree': 1.0}

=== (Val) Leaderboard Summary (LIGHT) ===

         model     phase    val_f1 params  fit_time_s
4      XGBoost  baseline  0.823529   None    0.269163
3  MLP_sklearn  baseline  0.814371   None    0.857044
5     LightGBM  baseline  0.814371   None    0.307287
0       LogReg  baseline  0.812121   None    5.664263
1           RF  baseline  0.804734   None    0.552234
2   ExtraTrees  baseline  0.800000   None    0.433935

=== (Val) Leaderboard Summary (FULL) ===

,model,phase,val_f1,params,fit_time_s,trials
3,MLP_sklearn,baseline,0.826347,None,0.771859,NaN
4,XGBoost,baseline,0.823529,None,0.054166,NaN
5,LightGBM,baseline,0.814371,None,0.046419,NaN
0,LogReg,baseline,0.812121,None,2.775595,NaN
1,RF,baseline,0.804734,None,0.540757,NaN
2,ExtraTrees,baseline,0.800000,None,0.321580,NaN
7,XGBoost,timed_search,0.845238,"{'subsample': 1.0, 'reg_lambda': 1.0, 'n_estim...",0.043403,270.0
8,LightGBM,timed_search,0.838323,"{'subsample': 0.85, 'reg_lambda': 10.0, 'num_l...",0.039103,168.0
6,MLP_sklearn,timed_search,0.833333,"{'clf__learning_rate_init': 0.0001, 'clf__hidd...",0.838996,57.0

**2) DL Full vs Light ("CNN", "RNN", "GRU", "LSTM", "AE")**

In [ ]:
# @title
import os, time, random
import numpy as np
import pandas as pd
import psutil

import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score, roc_auc_score, f1_score,
    precision_score, recall_score, log_loss, confusion_matrix, classification_report
)

# -----------------------------
# Utils
# -----------------------------
def set_seed(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

def get_system_ram():
    mem = psutil.virtual_memory()
    total = mem.total / (1024**3)
    used = mem.used / (1024**3)
    free = mem.available / (1024**3)
    percent = mem.percent
    return total, used, free, percent

def compute_metrics(y_true, y_pred, y_proba):
    acc = accuracy_score(y_true, y_pred)
    auc = roc_auc_score(y_true, y_proba)
    f1  = f1_score(y_true, y_pred)
    pr  = precision_score(y_true, y_pred)
    rc  = recall_score(y_true, y_pred)
    ll  = log_loss(y_true, y_proba)
    cm  = confusion_matrix(y_true, y_pred)
    return acc, auc, f1, pr, rc, ll, cm

def print_block(title, acc, auc, f1, precision, recall, ll, cm, y_true=None, y_pred=None):
    print(f"\n=== {title} (Test) ===")
    print(f"Accuracy:  {acc*100:.2f}%")
    print(f"AUC:       {auc*100:.2f}%")
    print(f"F1 Score:  {f1*100:.2f}%")
    print(f"Precision: {precision*100:.2f}%")
    print(f"Recall:    {recall*100:.2f}%")
    print(f"LogLoss:   {ll:.2f}")
    print("\nConfusion Matrix:")
    print(cm)
    if y_true is not None and y_pred is not None:
        print("\nClassification Report:")
        print(classification_report(y_true, y_pred))

# -----------------------------
# Models
# -----------------------------
class TabularCNN1D(nn.Module):
    """
    Tabular -> 1D-CNN
    Input x: (B, F)  -> (B, 1, F)
    """
    def __init__(self, n_features: int, channels: int = 32, dropout: float = 0.15):
        super().__init__()
        self.conv = nn.Sequential(
            nn.Conv1d(1, channels, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.Conv1d(channels, channels, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.Dropout(dropout),
        )
        self.pool = nn.AdaptiveAvgPool1d(1)  # -> (B, C, 1)
        self.head = nn.Sequential(
            nn.Linear(channels, 32),
            nn.ReLU(),
            nn.Dropout(0.10),
            nn.Linear(32, 1)
        )

    def forward(self, x):
        # x: (B, F)
        x = x.unsqueeze(1)           # (B, 1, F)
        h = self.conv(x)             # (B, C, F)
        h = self.pool(h).squeeze(-1) # (B, C)
        logits = self.head(h).squeeze(1)
        return logits

class TabularRNNBinary(nn.Module):
    """
    Tabular -> sequence: (B, F) -> (B, F, 1)
    rnn_type: 'rnn' | 'gru' | 'lstm'
    """
    def __init__(self, n_features: int, rnn_type="gru", hidden_size=32, num_layers=1, dropout=0.0):
        super().__init__()
        self.n_features = n_features
        self.rnn_type = rnn_type.lower()

        if self.rnn_type == "rnn":
            self.rnn = nn.RNN(input_size=1, hidden_size=hidden_size, num_layers=num_layers,
                              batch_first=True, dropout=dropout if num_layers > 1 else 0.0)
        elif self.rnn_type == "lstm":
            self.rnn = nn.LSTM(input_size=1, hidden_size=hidden_size, num_layers=num_layers,
                               batch_first=True, dropout=dropout if num_layers > 1 else 0.0)
        else:
            self.rnn = nn.GRU(input_size=1, hidden_size=hidden_size, num_layers=num_layers,
                              batch_first=True, dropout=dropout if num_layers > 1 else 0.0)

        self.head = nn.Sequential(
            nn.Linear(hidden_size, 32),
            nn.ReLU(),
            nn.Dropout(0.10),
            nn.Linear(32, 1)
        )

    def forward(self, x):
        # x: (B, F)
        x = x.unsqueeze(-1)  # (B, F, 1)
        out = self.rnn(x)
        if self.rnn_type == "lstm":
            seq_out, (h, c) = out
        else:
            seq_out, h = out
        last_h = seq_out[:, -1, :]  # (B, hidden)
        logits = self.head(last_h).squeeze(1)
        return logits

class AutoEncoder(nn.Module):
    def __init__(self, in_dim: int, latent_dim: int = 8):
        super().__init__()
        self.encoder = nn.Sequential(
            nn.Linear(in_dim, 32),
            nn.ReLU(),
            nn.Linear(32, latent_dim)
        )
        self.decoder = nn.Sequential(
            nn.Linear(latent_dim, 32),
            nn.ReLU(),
            nn.Linear(32, in_dim)
        )
    def forward(self, x):
        z = self.encoder(x)
        xhat = self.decoder(z)
        return xhat

class AEClassifier(nn.Module):
    def __init__(self, encoder: nn.Module, latent_dim: int):
        super().__init__()
        self.encoder = encoder
        self.head = nn.Sequential(
            nn.Linear(latent_dim, 16),
            nn.ReLU(),
            nn.Dropout(0.10),
            nn.Linear(16, 1)
        )
    def forward(self, x):
        z = self.encoder(x)
        return self.head(z).squeeze(1)

# -----------------------------
# Core training (time-budget + early stopping)
# -----------------------------
def train_supervised_timebudget(
    model: nn.Module,
    X_tr, y_tr,
    X_val, y_val,
    X_train_full, y_train_full,
    X_test, y_test,
    mode_name: str,
    time_budget_s: int,
    batch_size: int,
    lr: float,
    max_epochs: int,
    patience: int,
    use_scheduler: bool,
    device,
    out_file: str,
):
    process = psutil.Process(os.getpid())
    start_proc_mem = process.memory_info().rss / (1024 * 1024)
    start_sys_total, start_sys_used, start_sys_free, start_sys_percent = get_system_ram()
    start_time = time.time()

    model = model.to(device)
    criterion = nn.BCEWithLogitsLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=max_epochs) if use_scheduler else None

    Xtr_t = torch.tensor(X_tr).to(device)
    ytr_t = torch.tensor(y_tr).float().to(device)
    Xva_t = torch.tensor(X_val).to(device)

    best_val_f1 = -1.0
    best_state = None
    bad = 0
    epochs_done = 0

    # --- Train on inner-train, select by validation F1 ---
    for epoch in range(1, max_epochs + 1):
        if time.time() - start_time >= time_budget_s:
            break

        model.train()
        perm = torch.randperm(Xtr_t.size(0), device=device)
        Xb = Xtr_t[perm]
        yb = ytr_t[perm]

        for i in range(0, Xb.size(0), batch_size):
            if time.time() - start_time >= time_budget_s:
                break
            xb = Xb[i:i+batch_size]
            ybb = yb[i:i+batch_size]
            optimizer.zero_grad()
            logits = model(xb)
            loss = criterion(logits, ybb)
            loss.backward()
            optimizer.step()

        if scheduler is not None:
            scheduler.step()

        model.eval()
        with torch.no_grad():
            va_logits = model(Xva_t)
            va_prob = torch.sigmoid(va_logits).detach().cpu().numpy()
            va_pred = (va_prob >= 0.5).astype(int)
            va_f1 = f1_score(y_val, va_pred)

        epochs_done = epoch
        if va_f1 > best_val_f1 + 1e-4:
            best_val_f1 = va_f1
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
            bad = 0
        else:
            bad += 1
            if bad >= patience:
                break

    if best_state is not None:
        model.load_state_dict(best_state)

    # --- Short fine-tuning on the full outer-train within remaining time ---
    Xtrain_t = torch.tensor(X_train_full).to(device)
    ytrain_t = torch.tensor(y_train_full).float().to(device)

    finetune_epochs = 20 if mode_name == "full" else 8
    finetuned = 0
    for _ in range(finetune_epochs):
        if time.time() - start_time >= time_budget_s:
            break
        model.train()
        perm = torch.randperm(Xtrain_t.size(0), device=device)
        Xb = Xtrain_t[perm]
        yb = ytrain_t[perm]
        for i in range(0, Xb.size(0), batch_size):
            if time.time() - start_time >= time_budget_s:
                break
            xb = Xb[i:i+batch_size]
            ybb = yb[i:i+batch_size]
            optimizer.zero_grad()
            logits = model(xb)
            loss = criterion(logits, ybb)
            loss.backward()
            optimizer.step()
        finetuned += 1

    # --- Test ---
    model.eval()
    with torch.no_grad():
        Xte_t = torch.tensor(X_test).to(device)
        te_logits = model(Xte_t)
        te_prob = torch.sigmoid(te_logits).detach().cpu().numpy()
        te_pred = (te_prob >= 0.5).astype(int)

    acc, auc, f1, precision, recall, ll, cm = compute_metrics(y_test, te_pred, te_prob)

    end_time = time.time()
    end_proc_mem = process.memory_info().rss / (1024 * 1024)
    end_sys_total, end_sys_used, end_sys_free, end_sys_percent = get_system_ram()

    runtime = end_time - start_time
    proc_mem_usage = end_proc_mem - start_proc_mem
    sys_used_diff = end_sys_used - start_sys_used

    torch.save({
        "model_state": model.state_dict(),
        "best_val_f1": best_val_f1,
        "epochs_done": epochs_done,
        "finetuned_epochs": finetuned
    }, out_file)
    model_size_mb = os.path.getsize(out_file) / (1024 * 1024)

    print_block(out_file.replace(".pt","").replace("_", " "),
                acc, auc, f1, precision, recall, ll, cm,
                y_true=y_test, y_pred=te_pred)

    print("\n=== Summary ===")
    print(f"Runtime: {runtime:.2f} seconds (Budget={time_budget_s}s)")
    print(f"Python process RAM usage: {proc_mem_usage:.2f} MB")

    print("\n=== System RAM Usage ===")
    print(f"Total RAM:         {end_sys_total:.2f} GB")
    print(f"Used RAM:          {end_sys_used:.2f} GB")
    print(f"Available RAM:     {end_sys_free:.2f} GB")
    print(f"RAM utilization:   {end_sys_percent:.1f}%")
    print(f"RAM increase during run: {sys_used_diff:.2f} GB")

    print("\n=== Model file ===")
    print(f"Model path: {out_file}")
    print(f"Model size: {model_size_mb:.4f} MB")
    print(f"epochs_done={epochs_done} | finetuned_epochs={finetuned} | best_val_f1={best_val_f1:.4f}")

    return out_file

def train_ae_then_clf_timebudget(
    in_dim,
    X_tr, X_val,
    X_train_full, y_train_full,
    X_test, y_test,
    mode_name: str,
    time_budget_s: int,
    batch_size: int,
    device,
    out_file: str,
):
    """
    AE: reconstruction pretraining (unsupervised) + classifier fine-tuning.
    To keep budgets fair: fewer AE epochs in light mode, more in full mode.
    """
    start_time = time.time()
    process = psutil.Process(os.getpid())
    start_proc_mem = process.memory_info().rss / (1024 * 1024)
    start_sys_total, start_sys_used, start_sys_free, start_sys_percent = get_system_ram()

    # configs
    if mode_name == "light":
        ae_epochs = 30
        clf_max_epochs = 60
        patience = 6
        lr_ae = 1e-3
        lr_clf = 1e-3
    else:
        ae_epochs = 80
        clf_max_epochs = 200
        patience = 15
        lr_ae = 8e-4
        lr_clf = 8e-4

    ae = AutoEncoder(in_dim=in_dim, latent_dim=8).to(device)
    opt_ae = torch.optim.Adam(ae.parameters(), lr=lr_ae)
    mse = nn.MSELoss()

    Xtr_t = torch.tensor(X_tr).to(device)
    Xva_t = torch.tensor(X_val).to(device)

    # --- AE pretraining (stop if out of time) ---
    ae.train()
    for epoch in range(1, ae_epochs + 1):
        if time.time() - start_time >= time_budget_s * 0.55:  # ~55% of budget goes to AE
            break
        perm = torch.randperm(Xtr_t.size(0), device=device)
        Xb = Xtr_t[perm]
        for i in range(0, Xb.size(0), batch_size):
            if time.time() - start_time >= time_budget_s * 0.55:
                break
            xb = Xb[i:i+batch_size]
            opt_ae.zero_grad()
            xhat = ae(xb)
            loss = mse(xhat, xb)
            loss.backward()
            opt_ae.step()

    # --- classifier on top of encoder ---
    clf = AEClassifier(encoder=ae.encoder, latent_dim=8).to(device)
    # Fine-tune the encoder as well (usually helps)
    criterion = nn.BCEWithLogitsLoss()
    opt = torch.optim.Adam(clf.parameters(), lr=lr_clf)

    y_train_full = y_train_full.astype(int)
    y_tr_full_t = torch.tensor(y_train_full).float().to(device)

    # Even if there is no inner split, use validation early-stopping for fairness.
    y_val_dummy = None
    if X_val is not None:
        # y_val is not provided here; supervised validation labels are needed.
        # Practical workaround: use a subset of the full train as a validation split.
        pass

    # NOTE: For simplicity, this function returns the initialized modules and timing info.
    # The actual supervised training loop is implemented in the runner below.
    return clf, ae, start_time, start_proc_mem, start_sys_used, start_sys_total, start_sys_free, start_sys_percent

# -----------------------------
# Main runner
# -----------------------------
def run_dl_full_light_multi(
    clean_csv_path="heart_merged_clean.csv",
    target_col="target",
    test_size=0.2,
    seed=42,
    time_budget_full=180,
    time_budget_light=60,
    holdout_frac_for_tuning=0.2,
    batch_size=64,
    models_to_run=("CNN", "RNN", "GRU", "LSTM", "AE")
):
    set_seed(seed)
    torch.manual_seed(seed)

    df = pd.read_csv(clean_csv_path)
    X = df.drop(columns=[target_col]).values.astype(np.float32)
    y = df[target_col].astype(int).values

    # outer split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=test_size, random_state=seed, stratify=y
    )
    # inner split
    X_tr, X_val, y_tr, y_val = train_test_split(
        X_train, y_train,
        test_size=holdout_frac_for_tuning,
        random_state=seed,
        stratify=y_train
    )

    # ✅ Correct scaling: fit ONLY on outer train
    scaler = StandardScaler()
    X_train_s = scaler.fit_transform(X_train).astype(np.float32)
    X_test_s  = scaler.transform(X_test).astype(np.float32)
    X_tr_s    = scaler.transform(X_tr).astype(np.float32)
    X_val_s   = scaler.transform(X_val).astype(np.float32)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    out_files = {}

    def get_mode_cfg(mode_name):
        if mode_name == "light":
            return dict(max_epochs=60, patience=6, lr=1e-3, use_scheduler=False)
        else:
            return dict(max_epochs=200, patience=15, lr=8e-4, use_scheduler=True)

    def run_one(model_name: str, mode_name: str, budget_s: int):
        cfg = get_mode_cfg(mode_name)
        in_dim = X_tr_s.shape[1]

        if model_name == "CNN":
            # Smaller channels for light; larger for full
            ch = 24 if mode_name == "light" else 32
            model = TabularCNN1D(n_features=in_dim, channels=ch, dropout=0.15)
            out_file = f"dl_cnn_{mode_name}_best.pt"
            return train_supervised_timebudget(
                model,
                X_tr_s, y_tr, X_val_s, y_val,
                X_train_s, y_train,
                X_test_s, y_test,
                mode_name=mode_name,
                time_budget_s=budget_s,
                batch_size=batch_size,
                lr=cfg["lr"],
                max_epochs=cfg["max_epochs"],
                patience=cfg["patience"],
                use_scheduler=cfg["use_scheduler"],
                device=device,
                out_file=out_file
            )

        elif model_name in ("RNN", "GRU", "LSTM"):
            rnn_type = "rnn" if model_name == "RNN" else model_name.lower()
            # Smaller capacity for light; slightly larger for full
            hidden = 24 if mode_name == "light" else 32
            model = TabularRNNBinary(n_features=in_dim, rnn_type=rnn_type, hidden_size=hidden, num_layers=1, dropout=0.0)
            out_file = f"dl_{model_name.lower()}_{mode_name}_best.pt"
            return train_supervised_timebudget(
                model,
                X_tr_s, y_tr, X_val_s, y_val,
                X_train_s, y_train,
                X_test_s, y_test,
                mode_name=mode_name,
                time_budget_s=budget_s,
                batch_size=batch_size,
                lr=cfg["lr"],
                max_epochs=cfg["max_epochs"],
                patience=cfg["patience"],
                use_scheduler=cfg["use_scheduler"],
                device=device,
                out_file=out_file
            )

        elif model_name == "AE":
            # 1) AE pretraining (unsupervised) uses a portion of the budget
            # 2) Supervised AEClassifier training uses the remaining time
            process = psutil.Process(os.getpid())
            start_proc_mem = process.memory_info().rss / (1024 * 1024)
            start_sys_total, start_sys_used, start_sys_free, start_sys_percent = get_system_ram()
            start_time = time.time()

            # config
            if mode_name == "light":
                ae_epochs = 25
                patience = 6
                lr_ae = 1e-3
                lr_clf = 1e-3
                clf_max_epochs = 60
            else:
                ae_epochs = 70
                patience = 15
                lr_ae = 8e-4
                lr_clf = 8e-4
                clf_max_epochs = 200

            ae = AutoEncoder(in_dim=in_dim, latent_dim=8).to(device)
            opt_ae = torch.optim.Adam(ae.parameters(), lr=lr_ae)
            mse = nn.MSELoss()

            Xtr_t = torch.tensor(X_tr_s).to(device)

            # AE pretraining: ~45% of the budget
            ae.train()
            for epoch in range(1, ae_epochs + 1):
                if time.time() - start_time >= budget_s * 0.45:
                    break
                perm = torch.randperm(Xtr_t.size(0), device=device)
                Xb = Xtr_t[perm]
                for i in range(0, Xb.size(0), batch_size):
                    if time.time() - start_time >= budget_s * 0.45:
                        break
                    xb = Xb[i:i+batch_size]
                    opt_ae.zero_grad()
                    xhat = ae(xb)
                    loss = mse(xhat, xb)
                    loss.backward()
                    opt_ae.step()

            clf = AEClassifier(encoder=ae.encoder, latent_dim=8).to(device)
            criterion = nn.BCEWithLogitsLoss()
            opt = torch.optim.Adam(clf.parameters(), lr=lr_clf)

            Xtr_t = torch.tensor(X_tr_s).to(device)
            ytr_t = torch.tensor(y_tr).float().to(device)
            Xva_t = torch.tensor(X_val_s).to(device)

            best_val_f1 = -1.0
            best_state = None
            bad = 0
            epochs_done = 0

            # supervised training with remaining time
            for epoch in range(1, clf_max_epochs + 1):
                if time.time() - start_time >= budget_s:
                    break
                clf.train()
                perm = torch.randperm(Xtr_t.size(0), device=device)
                Xb = Xtr_t[perm]
                yb = ytr_t[perm]
                for i in range(0, Xb.size(0), batch_size):
                    if time.time() - start_time >= budget_s:
                        break
                    xb = Xb[i:i+batch_size]
                    ybb = yb[i:i+batch_size]
                    opt.zero_grad()
                    logits = clf(xb)
                    loss = criterion(logits, ybb)
                    loss.backward()
                    opt.step()

                clf.eval()
                with torch.no_grad():
                    va_logits = clf(Xva_t)
                    va_prob = torch.sigmoid(va_logits).detach().cpu().numpy()
                    va_pred = (va_prob >= 0.5).astype(int)
                    va_f1 = f1_score(y_val, va_pred)

                epochs_done = epoch
                if va_f1 > best_val_f1 + 1e-4:
                    best_val_f1 = va_f1
                    best_state = {k: v.detach().cpu().clone() for k, v in clf.state_dict().items()}
                    bad = 0
                else:
                    bad += 1
                    if bad >= patience:
                        break

            if best_state is not None:
                clf.load_state_dict(best_state)

            # test
            clf.eval()
            with torch.no_grad():
                Xte_t = torch.tensor(X_test_s).to(device)
                te_logits = clf(Xte_t)
                te_prob = torch.sigmoid(te_logits).detach().cpu().numpy()
                te_pred = (te_prob >= 0.5).astype(int)

            acc, auc, f1, precision, recall, ll, cm = compute_metrics(y_test, te_pred, te_prob)

            end_time = time.time()
            end_proc_mem = process.memory_info().rss / (1024 * 1024)
            end_sys_total, end_sys_used, end_sys_free, end_sys_percent = get_system_ram()

            runtime = end_time - start_time
            proc_mem_usage = end_proc_mem - start_proc_mem
            sys_used_diff = end_sys_used - start_sys_used

            out_file = f"dl_ae_{mode_name}_best.pt"
            torch.save({
                "ae_state": ae.state_dict(),
                "clf_state": clf.state_dict(),
                "best_val_f1": best_val_f1,
                "epochs_done": epochs_done,
                "scaler": scaler,
                "seed": seed,
            }, out_file)
            model_size_mb = os.path.getsize(out_file) / (1024 * 1024)

            print_block(f"DL (PyTorch) AE+Head {mode_name.upper()}",
                        acc, auc, f1, precision, recall, ll, cm,
                        y_true=y_test, y_pred=te_pred)

            print("\n=== Summary ===")
            print(f"Runtime: {runtime:.2f} seconds (Budget={budget_s}s)")
            print(f"Python process RAM usage: {proc_mem_usage:.2f} MB")
            print(f"System RAM increase during run: {sys_used_diff:.2f} GB")

            print("\n=== Model file ===")
            print(f"Model path: {out_file}")
            print(f"Model size: {model_size_mb:.4f} MB")
            print(f"epochs_done={epochs_done} | best_val_f1={best_val_f1:.4f}")

            return out_file

        else:
            raise ValueError(f"Unknown model_name: {model_name}")

    # Run LIGHT then FULL for each model
    for m in models_to_run:
        out_files[f"{m.lower()}_light"] = run_one(m, "light", time_budget_light)
        out_files[f"{m.lower()}_full"]  = run_one(m, "full",  time_budget_full)

    return out_files

In [ ]:
# @title
dl_out = run_dl_full_light_multi(
    clean_csv_path="heart_merged_clean.csv",
    target_col="target",
    seed=42,
    time_budget_full=180,
    time_budget_light=60,
    models_to_run=("CNN", "RNN", "GRU", "LSTM", "AE")
)
print("\nSaved:", dl_out)

=== dl cnn light best (Test) ===
Accuracy:  71.20%
AUC:       76.53%
F1 Score:  74.40%
Precision: 73.33%
Recall:    75.49%
LogLoss:   0.57

Confusion Matrix:
[[54 28]
 [25 77]]

Classification Report:
              precision    recall  f1-score   support

           0       0.68      0.66      0.67        82
           1       0.73      0.75      0.74       102

    accuracy                           0.71       184
   macro avg       0.71      0.71      0.71       184
weighted avg       0.71      0.71      0.71       184


=== Özet Bilgiler ===
Koşum Süresi: 4.01 saniye (Budget=60s)
Python İşlemi RAM Kullanımı: 73.52 MB

=== Sistem Genel RAM Kullanımı ===
Toplam RAM:         12.67 GB
Kullanılan RAM:     1.22 GB
Boş RAM:            11.14 GB
RAM Kullanım Oranı: 12.1%
Koşum sırasında artan RAM: 0.11 GB

=== Model Dosyası ===
Model yolu: dl_cnn_light_best.pt
Model boyutu: 0.0139 MB
epochs_done=11 | finetuned_epochs=8 | best_val_f1=0.7461

=== dl cnn full best (Test) ===
Accuracy:  72.83%
AUC:       77.73%
F1 Score:  74.49%
Precision: 77.66%
Recall:    71.57%
LogLoss:   0.56

Confusion Matrix:
[[61 21]
 [29 73]]

Classification Report:
              precision    recall  f1-score   support

           0       0.68      0.74      0.71        82
           1       0.78      0.72      0.74       102

    accuracy                           0.73       184
   macro avg       0.73      0.73      0.73       184
weighted avg       0.73      0.73      0.73       184


=== Özet Bilgiler ===
Koşum Süresi: 5.58 saniye (Budget=180s)
Python İşlemi RAM Kullanımı: 1.95 MB

=== Sistem Genel RAM Kullanımı ===
Toplam RAM:         12.67 GB
Kullanılan RAM:     1.32 GB
Boş RAM:            11.04 GB
RAM Kullanım Oranı: 12.9%
Koşum sırasında artan RAM: 0.10 GB

=== Model Dosyası ===
Model yolu: dl_cnn_full_best.pt
Model boyutu: 0.0203 MB
epochs_done=20 | finetuned_epochs=20 | best_val_f1=0.7391

=== dl rnn light best (Test) ===
Accuracy:  78.26%
AUC:       86.32%
F1 Score:  80.20%
Precision: 81.00%
Recall:    79.41%
LogLoss:   0.47

Confusion Matrix:
[[63 19]
 [21 81]]

Classification Report:
              precision    recall  f1-score   support

           0       0.75      0.77      0.76        82
           1       0.81      0.79      0.80       102

    accuracy                           0.78       184
   macro avg       0.78      0.78      0.78       184
weighted avg       0.78      0.78      0.78       184


=== Özet Bilgiler ===
Koşum Süresi: 1.50 saniye (Budget=60s)
Python İşlemi RAM Kullanımı: 0.89 MB

=== Sistem Genel RAM Kullanımı ===
Toplam RAM:         12.67 GB
Kullanılan RAM:     1.32 GB
Boş RAM:            11.03 GB
RAM Kullanım Oranı: 12.9%
Koşum sırasında artan RAM: 0.00 GB

=== Model Dosyası ===
Model yolu: dl_rnn_light_best.pt
Model boyutu: 0.0092 MB
epochs_done=12 | finetuned_epochs=8 | best_val_f1=0.7978

=== dl rnn full best (Test) ===
Accuracy:  82.07%
AUC:       89.61%
F1 Score:  84.65%
Precision: 80.53%
Recall:    89.22%
LogLoss:   0.42

Confusion Matrix:
[[60 22]
 [11 91]]

Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.73      0.78        82
           1       0.81      0.89      0.85       102

    accuracy                           0.82       184
   macro avg       0.83      0.81      0.82       184
weighted avg       0.82      0.82      0.82       184


=== Özet Bilgiler ===
Koşum Süresi: 3.85 saniye (Budget=180s)
Python İşlemi RAM Kullanımı: 0.09 MB

=== Sistem Genel RAM Kullanımı ===
Toplam RAM:         12.67 GB
Kullanılan RAM:     1.34 GB
Boş RAM:            11.02 GB
RAM Kullanım Oranı: 13.0%
Koşum sırasında artan RAM: 0.01 GB

=== Model Dosyası ===
Model yolu: dl_rnn_full_best.pt
Model boyutu: 0.0121 MB
epochs_done=78 | finetuned_epochs=20 | best_val_f1=0.8447

=== dl gru light best (Test) ===
Accuracy:  75.00%
AUC:       79.47%
F1 Score:  76.77%
Precision: 79.17%
Recall:    74.51%
LogLoss:   0.54

Confusion Matrix:
[[62 20]
 [26 76]]

Classification Report:
              precision    recall  f1-score   support

           0       0.70      0.76      0.73        82
           1       0.79      0.75      0.77       102

    accuracy                           0.75       184
   macro avg       0.75      0.75      0.75       184
weighted avg       0.75      0.75      0.75       184


=== Özet Bilgiler ===
Koşum Süresi: 1.32 saniye (Budget=60s)
Python İşlemi RAM Kullanımı: 0.95 MB

=== Sistem Genel RAM Kullanımı ===
Toplam RAM:         12.67 GB
Kullanılan RAM:     1.34 GB
Boş RAM:            11.02 GB
RAM Kullanım Oranı: 13.0%
Koşum sırasında artan RAM: 0.00 GB

=== Model Dosyası ===
Model yolu: dl_gru_light_best.pt
Model boyutu: 0.0142 MB
epochs_done=13 | finetuned_epochs=8 | best_val_f1=0.7283

=== dl gru full best (Test) ===
Accuracy:  80.43%
AUC:       87.11%
F1 Score:  82.86%
Precision: 80.56%
Recall:    85.29%
LogLoss:   0.44

Confusion Matrix:
[[61 21]
 [15 87]]

Classification Report:
              precision    recall  f1-score   support

           0       0.80      0.74      0.77        82
           1       0.81      0.85      0.83       102

    accuracy                           0.80       184
   macro avg       0.80      0.80      0.80       184
weighted avg       0.80      0.80      0.80       184


=== Özet Bilgiler ===
Koşum Süresi: 8.72 saniye (Budget=180s)
Python İşlemi RAM Kullanımı: 0.87 MB

=== Sistem Genel RAM Kullanımı ===
Toplam RAM:         12.67 GB
Kullanılan RAM:     1.36 GB
Boş RAM:            11.00 GB
RAM Kullanım Oranı: 13.2%
Koşum sırasında artan RAM: 0.02 GB

=== Model Dosyası ===
Model yolu: dl_gru_full_best.pt
Model boyutu: 0.0206 MB
epochs_done=102 | finetuned_epochs=20 | best_val_f1=0.8276

=== dl lstm light best (Test) ===
Accuracy:  72.83%
AUC:       79.26%
F1 Score:  74.23%
Precision: 78.26%
Recall:    70.59%
LogLoss:   0.55

Confusion Matrix:
[[62 20]
 [30 72]]

Classification Report:
              precision    recall  f1-score   support

           0       0.67      0.76      0.71        82
           1       0.78      0.71      0.74       102

    accuracy                           0.73       184
   macro avg       0.73      0.73      0.73       184
weighted avg       0.73      0.73      0.73       184


=== Özet Bilgiler ===
Koşum Süresi: 0.96 saniye (Budget=60s)
Python İşlemi RAM Kullanımı: 8.52 MB

=== Sistem Genel RAM Kullanımı ===
Toplam RAM:         12.67 GB
Kullanılan RAM:     1.36 GB
Boş RAM:            11.00 GB
RAM Kullanım Oranı: 13.2%
Koşum sırasında artan RAM: 0.00 GB

=== Model Dosyası ===
Model yolu: dl_lstm_light_best.pt
Model boyutu: 0.0168 MB
epochs_done=14 | finetuned_epochs=8 | best_val_f1=0.7333

=== dl lstm full best (Test) ===
Accuracy:  73.91%
AUC:       79.93%
F1 Score:  76.00%
Precision: 77.55%
Recall:    74.51%
LogLoss:   0.54

Confusion Matrix:
[[60 22]
 [26 76]]

Classification Report:
              precision    recall  f1-score   support

           0       0.70      0.73      0.71        82
           1       0.78      0.75      0.76       102

    accuracy                           0.74       184
   macro avg       0.74      0.74      0.74       184
weighted avg       0.74      0.74      0.74       184


=== Özet Bilgiler ===
Koşum Süresi: 1.88 saniye (Budget=180s)
Python İşlemi RAM Kullanımı: 2.40 MB

=== Sistem Genel RAM Kullanımı ===
Toplam RAM:         12.67 GB
Kullanılan RAM:     1.36 GB
Boş RAM:            11.00 GB
RAM Kullanım Oranı: 13.2%
Koşum sırasında artan RAM: -0.00 GB

=== Model Dosyası ===
Model yolu: dl_lstm_full_best.pt
Model boyutu: 0.0249 MB
epochs_done=20 | finetuned_epochs=20 | best_val_f1=0.7619

=== DL (PyTorch) AE+Head LIGHT (Test) ===
Accuracy:  77.17%
AUC:       84.88%
F1 Score:  80.37%
Precision: 76.79%
Recall:    84.31%
LogLoss:   0.54

Confusion Matrix:
[[56 26]
 [16 86]]

Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.68      0.73        82
           1       0.77      0.84      0.80       102

    accuracy                           0.77       184
   macro avg       0.77      0.76      0.77       184
weighted avg       0.77      0.77      0.77       184


=== Özet Bilgiler ===
Koşum Süresi: 0.49 saniye (Budget=60s)
Python İşlemi RAM Kullanımı: 0.12 MB
Koşum sırasında artan RAM (sys): 0.00 GB

=== Model Dosyası ===
Model yolu: dl_ae_light_best.pt
Model boyutu: 0.0122 MB
epochs_done=11 | best_val_f1=0.8066

=== DL (PyTorch) AE+Head FULL (Test) ===
Accuracy:  82.61%
AUC:       89.37%
F1 Score:  84.62%
Precision: 83.02%
Recall:    86.27%
LogLoss:   0.41

Confusion Matrix:
[[64 18]
 [14 88]]

Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.78      0.80        82
           1       0.83      0.86      0.85       102

    accuracy                           0.83       184
   macro avg       0.83      0.82      0.82       184
weighted avg       0.83      0.83      0.83       184


=== Özet Bilgiler ===
Koşum Süresi: 1.31 saniye (Budget=180s)
Python İşlemi RAM Kullanımı: 0.00 MB
Koşum sırasında artan RAM (sys): 0.00 GB

=== Model Dosyası ===
Model yolu: dl_ae_full_best.pt
Model boyutu: 0.0122 MB
epochs_done=28 | best_val_f1=0.8293

Saved: {'cnn_light': 'dl_cnn_light_best.pt', 'cnn_full': 'dl_cnn_full_best.pt', 'rnn_light': 'dl_rnn_light_best.pt', 'rnn_full': 'dl_rnn_full_best.pt', 'gru_light': 'dl_gru_light_best.pt', 'gru_full': 'dl_gru_full_best.pt', 'lstm_light': 'dl_lstm_light_best.pt', 'lstm_full': 'dl_lstm_full_best.pt', 'ae_light': 'dl_ae_light_best.pt', 'ae_full': 'dl_ae_full_best.pt'}

## Repeated Stratified Holdout Evaluation (Reviewer Revision)

This section adds repeated stratified 80/20 holdout evaluation using multiple random seeds. It is intended to address reviewer concerns about relying on a single train/test split. The block saves raw per-seed results, mean ± standard deviation summaries, and budget-compliance statistics for the lightweight regime.

Default seeds: `42, 7, 21, 84, 123`.

Generated outputs:
- `repeated_holdout_light_results.csv`
- `repeated_holdout_light_summary.csv`
- `repeated_holdout_light_summary_formatted.csv`
- `repeated_holdout_light_budget_compliance.csv`

In [6]:
# @title
# ============================================================
# REPEATED STRATIFIED HOLDOUT EVALUATION
# Purpose: address reviewer concern about single 80/20 split
# Output files:
#   - repeated_holdout_light_results.csv
#   - repeated_holdout_light_summary.csv
#   - repeated_holdout_light_summary_formatted.csv
#   - repeated_holdout_light_budget_compliance.csv
# ============================================================

import os
import gc
import time
import json
import shutil
import random
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import psutil
import joblib

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score, roc_auc_score, f1_score,
    precision_score, recall_score, log_loss, confusion_matrix
)
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier

warnings.filterwarnings("ignore")

# -----------------------------
# Global repeated-holdout config
# -----------------------------
SEEDS = [42, 7, 21, 84, 123]
TEST_SIZE = 0.20
INNER_VAL_SIZE = 0.20
TARGET_COL = "target"
CLEAN_CSV_PATH = "heart_merged_clean.csv"

# Lightweight regime is the main target because the manuscript explicitly motivates
# repeated holdout for strict/lightweight time-budget settings.
LIGHT_BUDGET = 60

# To include/exclude frameworks, edit this list.
FRAMEWORKS_TO_RUN = [
    "classic_ml_light",
    "autogluon_light",
    "flaml_light",
    "mljar_light",
    "h2o_light",
]

ARTIFACT_DIR = Path("repeated_holdout_artifacts")
ARTIFACT_DIR.mkdir(exist_ok=True)

RESULTS_CSV = "repeated_holdout_light_results.csv"
SUMMARY_CSV = "repeated_holdout_light_summary.csv"
SUMMARY_FORMATTED_CSV = "repeated_holdout_light_summary_formatted.csv"
BUDGET_CSV = "repeated_holdout_light_budget_compliance.csv"


def set_all_seeds(seed: int) -> None:
    """Set common Python/NumPy seeds for more reproducible repeated runs."""
    random.seed(seed)
    np.random.seed(seed)
    try:
        import torch
        torch.manual_seed(seed)
        if torch.cuda.is_available():
            torch.cuda.manual_seed_all(seed)
    except Exception:
        pass


def get_system_ram():
    mem = psutil.virtual_memory()
    total = mem.total / (1024**3)
    used = mem.used / (1024**3)
    free = mem.available / (1024**3)
    percent = mem.percent
    return total, used, free, percent


def get_dir_size_mb(path: str) -> float:
    path = Path(path)
    if not path.exists():
        return np.nan
    if path.is_file():
        return path.stat().st_size / (1024 * 1024)
    total_bytes = 0
    for root, _, files in os.walk(path):
        for f in files:
            fp = Path(root) / f
            if fp.is_file():
                total_bytes += fp.stat().st_size
    return total_bytes / (1024 * 1024)


def pick_positive_proba_from_dataframe(proba_df: pd.DataFrame, pos_label=1) -> np.ndarray:
    """Return positive-class probabilities from AutoGluon-style DataFrame output."""
    if pos_label in proba_df.columns:
        return proba_df[pos_label].to_numpy()
    if str(pos_label) in proba_df.columns:
        return proba_df[str(pos_label)].to_numpy()
    return proba_df.iloc[:, -1].to_numpy()


def pick_positive_proba_from_array(proba) -> np.ndarray:
    """Return positive-class probabilities from sklearn/FLAML/H2O-like output."""
    proba = np.asarray(proba)
    if proba.ndim == 2 and proba.shape[1] >= 2:
        return proba[:, 1]
    if proba.ndim == 1:
        return proba
    return proba[:, -1]


def evaluate_binary(y_true, y_pred, y_proba=None) -> dict:
    """Compute binary classification metrics in the same style as the manuscript tables."""
    y_true = np.asarray(y_true).astype(int)
    y_pred = np.asarray(y_pred).astype(int)

    out = {
        "accuracy_pct": accuracy_score(y_true, y_pred) * 100,
        "f1_pct": f1_score(y_true, y_pred, zero_division=0) * 100,
        "precision_pct": precision_score(y_true, y_pred, zero_division=0) * 100,
        "recall_pct": recall_score(y_true, y_pred, zero_division=0) * 100,
    }

    if y_proba is not None:
        y_proba = np.asarray(y_proba, dtype=float)
        y_proba = np.clip(y_proba, 1e-7, 1 - 1e-7)
        out["auc_pct"] = roc_auc_score(y_true, y_proba) * 100
        out["logloss"] = log_loss(y_true, y_proba)
    else:
        out["auc_pct"] = np.nan
        out["logloss"] = np.nan

    tn, fp, fn, tp = confusion_matrix(y_true, y_pred, labels=[0, 1]).ravel()
    out.update({"tn": int(tn), "fp": int(fp), "fn": int(fn), "tp": int(tp)})
    return out


def monitor_start():
    process = psutil.Process(os.getpid())
    return {
        "process": process,
        "start_time": time.time(),
        "start_proc_mem": process.memory_info().rss / (1024 * 1024),
        "start_sys_used": get_system_ram()[1],
    }


def monitor_end(monitor: dict) -> dict:
    end_time = time.time()
    end_proc_mem = monitor["process"].memory_info().rss / (1024 * 1024)
    end_sys_used = get_system_ram()[1]
    return {
        "runtime_s": end_time - monitor["start_time"],
        "proc_ram_delta_mb": end_proc_mem - monitor["start_proc_mem"],
        "sys_ram_delta_gb": end_sys_used - monitor["start_sys_used"],
    }


def base_record(framework: str, seed: int, budget_s: int = LIGHT_BUDGET) -> dict:
    return {
        "framework": framework,
        "regime": "Lightweight",
        "seed": seed,
        "test_size": TEST_SIZE,
        "budget_s": budget_s,
        "status": "ok",
        "error": "",
    }


# ============================================================
# 1) Classical ML - lightweight repeated holdout
# ============================================================
def run_classic_ml_light_once(data: pd.DataFrame, seed: int) -> dict:
    """Fast classical ML pool with inner validation selection and held-out test evaluation."""
    set_all_seeds(seed)
    rec = base_record("ClassicML_Light", seed)
    mon = monitor_start()

    X = data.drop(columns=[TARGET_COL])
    y = data[TARGET_COL].astype(int)

    X_train_outer, X_test, y_train_outer, y_test = train_test_split(
        X, y, test_size=TEST_SIZE, random_state=seed, stratify=y
    )
    X_train, X_val, y_train, y_val = train_test_split(
        X_train_outer, y_train_outer,
        test_size=INNER_VAL_SIZE,
        random_state=seed,
        stratify=y_train_outer
    )

    candidates = {
        "LogisticRegression": Pipeline([
            ("scaler", StandardScaler()),
            ("model", LogisticRegression(max_iter=1000, random_state=seed))
        ]),
        "RandomForest": RandomForestClassifier(
            n_estimators=200, random_state=seed, n_jobs=-1, class_weight=None
        ),
        "ExtraTrees": ExtraTreesClassifier(
            n_estimators=300, random_state=seed, n_jobs=-1, class_weight=None
        ),
    }

    try:
        from xgboost import XGBClassifier
        candidates["XGBoost"] = XGBClassifier(
            n_estimators=120,
            max_depth=3,
            learning_rate=0.08,
            subsample=0.9,
            colsample_bytree=0.9,
            eval_metric="logloss",
            random_state=seed,
            n_jobs=-1,
        )
    except Exception as e:
        print(f"[ClassicML] XGBoost skipped: {e}")

    try:
        from lightgbm import LGBMClassifier
        candidates["LightGBM"] = LGBMClassifier(
            n_estimators=120,
            learning_rate=0.05,
            random_state=seed,
            n_jobs=-1,
            verbose=-1,
        )
    except Exception as e:
        print(f"[ClassicML] LightGBM skipped: {e}")

    best_name, best_model, best_val_f1 = None, None, -np.inf
    for name, model in candidates.items():
        model.fit(X_train, y_train)
        val_pred = model.predict(X_val)
        val_f1 = f1_score(y_val, val_pred, zero_division=0)
        if val_f1 > best_val_f1:
            best_name, best_model, best_val_f1 = name, model, val_f1

    y_pred = best_model.predict(X_test)
    y_proba = None
    if hasattr(best_model, "predict_proba"):
        y_proba = pick_positive_proba_from_array(best_model.predict_proba(X_test))

    model_path = ARTIFACT_DIR / f"classic_ml_light_seed_{seed}_{best_name}.pkl"
    joblib.dump(best_model, model_path)

    rec.update(evaluate_binary(y_test, y_pred, y_proba))
    rec.update(monitor_end(mon))
    rec.update({
        "best_model": best_name,
        "inner_val_f1_pct": best_val_f1 * 100,
        "model_size_mb": get_dir_size_mb(str(model_path)),
    })
    return rec


# ============================================================
# 2) AutoGluon - lightweight repeated holdout
# ============================================================
def run_autogluon_light_once(data: pd.DataFrame, seed: int) -> dict:
    set_all_seeds(seed)
    rec = base_record("AutoGluon_Light", seed)
    mon = monitor_start()

    from autogluon.tabular import TabularPredictor

    train_df, test_df = train_test_split(
        data, test_size=TEST_SIZE, random_state=seed, stratify=data[TARGET_COL]
    )

    predictor_path = ARTIFACT_DIR / f"autogluon_light_seed_{seed}"
    if predictor_path.exists():
        shutil.rmtree(predictor_path)

    predictor = TabularPredictor(
        label=TARGET_COL,
        eval_metric="f1",
        path=str(predictor_path),
        verbosity=0,
    )

    hyperparameters = {
        "GBM": {},
        "RF": {},
        "XT": {},
        "LR": {},
    }

    predictor.fit(
        train_data=train_df,
        presets="medium_quality_faster_train",
        time_limit=LIGHT_BUDGET,
        num_bag_folds=0,
        num_stack_levels=0,
        hyperparameters=hyperparameters,
    )

    y_test = test_df[TARGET_COL].astype(int).to_numpy()
    y_pred = predictor.predict(test_df).astype(int).to_numpy()
    proba_df = predictor.predict_proba(test_df)
    y_proba = pick_positive_proba_from_dataframe(proba_df, pos_label=1)

    leaderboard = predictor.leaderboard(test_df, silent=True)
    best_model = str(leaderboard.iloc[0]["model"]) if len(leaderboard) else "AutoGluon"

    rec.update(evaluate_binary(y_test, y_pred, y_proba))
    rec.update(monitor_end(mon))
    rec.update({
        "best_model": best_model,
        "inner_val_f1_pct": np.nan,
        "model_size_mb": get_dir_size_mb(str(predictor_path)),
    })

    del predictor
    gc.collect()
    return rec


# ============================================================
# 3) FLAML - lightweight repeated holdout
# ============================================================
def run_flaml_light_once(data: pd.DataFrame, seed: int) -> dict:
    set_all_seeds(seed)
    rec = base_record("FLAML_Light", seed)
    mon = monitor_start()

    from flaml import AutoML

    X = data.drop(columns=[TARGET_COL])
    y = data[TARGET_COL].astype(int)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=TEST_SIZE, random_state=seed, stratify=y
    )

    automl = AutoML()
    automl_settings = {
        "time_budget": LIGHT_BUDGET,
        "task": "classification",
        "metric": "f1",
        "seed": seed,
        "log_file_name": str(ARTIFACT_DIR / f"flaml_light_seed_{seed}.log"),
        "eval_method": "holdout",
        "split_ratio": INNER_VAL_SIZE,
        "n_jobs": -1,
        "estimator_list": ["lgbm", "rf", "extra_tree", "xgboost", "lrl1"],
        "verbose": 0,
    }

    automl.fit(X_train=X_train, y_train=y_train, **automl_settings)

    y_pred = automl.predict(X_test).astype(int)
    y_proba = None
    if hasattr(automl, "predict_proba"):
        y_proba = pick_positive_proba_from_array(automl.predict_proba(X_test))

    model_path = ARTIFACT_DIR / f"flaml_light_seed_{seed}.pkl"
    joblib.dump(automl.model.estimator, model_path)

    rec.update(evaluate_binary(y_test, y_pred, y_proba))
    rec.update(monitor_end(mon))
    rec.update({
        "best_model": str(automl.best_estimator),
        "inner_val_f1_pct": np.nan,
        "model_size_mb": get_dir_size_mb(str(model_path)),
    })

    del automl
    gc.collect()
    return rec


# ============================================================
# 4) MLJAR - lightweight repeated holdout
# ============================================================
def run_mljar_light_once(data: pd.DataFrame, seed: int) -> dict:
    set_all_seeds(seed)
    rec = base_record("MLJAR_Light", seed)
    mon = monitor_start()

    from supervised.automl import AutoML

    X = data.drop(columns=[TARGET_COL])
    y = data[TARGET_COL].astype(int)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=TEST_SIZE, random_state=seed, stratify=y
    )

    results_path = ARTIFACT_DIR / f"mljar_light_seed_{seed}"
    if results_path.exists():
        shutil.rmtree(results_path)

    automl = AutoML(
        mode="Explain",
        algorithms=["LightGBM", "Xgboost", "CatBoost", "Random Forest"],
        total_time_limit=LIGHT_BUDGET,
        explain_level=1,
        random_state=seed,
        start_random_models=2,
        hill_climbing_steps=0,
        results_path=str(results_path),
    )

    automl.fit(X_train, y_train)

    y_pred = automl.predict(X_test).astype(int)
    y_proba = pick_positive_proba_from_array(automl.predict_proba(X_test))

    best_model = getattr(automl, "_best_model", None)
    best_model_name = type(best_model).__name__ if best_model is not None else "MLJAR"
    model_path = ARTIFACT_DIR / f"mljar_light_seed_{seed}_best_model.pkl"
    try:
        joblib.dump(best_model, model_path)
        model_size_mb = get_dir_size_mb(str(model_path))
    except Exception:
        model_size_mb = get_dir_size_mb(str(results_path))

    rec.update(evaluate_binary(y_test, y_pred, y_proba))
    rec.update(monitor_end(mon))
    rec.update({
        "best_model": best_model_name,
        "inner_val_f1_pct": np.nan,
        "model_size_mb": model_size_mb,
    })

    del automl
    gc.collect()
    return rec


# ============================================================
# 5) H2O AutoML - lightweight repeated holdout
# ============================================================
def run_h2o_light_once(data: pd.DataFrame, seed: int) -> dict:
    set_all_seeds(seed)
    rec = base_record("H2O_Light", seed)
    mon = monitor_start()

    import h2o
    from h2o.automl import H2OAutoML

    X = data.drop(columns=[TARGET_COL])
    y = data[TARGET_COL].astype(int)

    X_train_outer, X_test, y_train_outer, y_test = train_test_split(
        X, y, test_size=TEST_SIZE, random_state=seed, stratify=y
    )
    X_train, X_val, y_train, y_val = train_test_split(
        X_train_outer, y_train_outer,
        test_size=INNER_VAL_SIZE,
        random_state=seed,
        stratify=y_train_outer
    )

    train_pd = X_train.copy(); train_pd[TARGET_COL] = y_train.values
    val_pd = X_val.copy(); val_pd[TARGET_COL] = y_val.values
    test_pd = X_test.copy(); test_pd[TARGET_COL] = y_test.values

    h2o.init(max_mem_size="4G", nthreads=-1)
    train_h2o = h2o.H2OFrame(train_pd)
    val_h2o = h2o.H2OFrame(val_pd)
    test_h2o = h2o.H2OFrame(test_pd)

    train_h2o[TARGET_COL] = train_h2o[TARGET_COL].asfactor()
    val_h2o[TARGET_COL] = val_h2o[TARGET_COL].asfactor()
    test_h2o[TARGET_COL] = test_h2o[TARGET_COL].asfactor()

    predictors = [c for c in train_h2o.columns if c != TARGET_COL]

    aml = H2OAutoML(
        max_runtime_secs=LIGHT_BUDGET,
        seed=seed,
        sort_metric="F1",
        nfolds=0,
        verbosity="warn",
    )
    aml.train(
        x=predictors,
        y=TARGET_COL,
        training_frame=train_h2o,
        validation_frame=val_h2o,
        leaderboard_frame=val_h2o,
    )

    pred_h2o = aml.leader.predict(test_h2o).as_data_frame()
    y_pred = pred_h2o["predict"].astype(int).to_numpy()
    if "p1" in pred_h2o.columns:
        y_proba = pred_h2o["p1"].astype(float).to_numpy()
    else:
        y_proba = None

    model_dir = ARTIFACT_DIR / f"h2o_light_seed_{seed}"
    model_dir.mkdir(exist_ok=True)
    model_path = h2o.save_model(model=aml.leader, path=str(model_dir), force=True)

    rec.update(evaluate_binary(y_test, y_pred, y_proba))
    rec.update(monitor_end(mon))
    rec.update({
        "best_model": type(aml.leader).__name__,
        "inner_val_f1_pct": np.nan,
        "model_size_mb": get_dir_size_mb(str(model_path)),
    })

    h2o.shutdown(prompt=False)
    gc.collect()
    return rec


RUNNERS = {
    "classic_ml_light": run_classic_ml_light_once,
    "autogluon_light": run_autogluon_light_once,
    "flaml_light": run_flaml_light_once,
    "mljar_light": run_mljar_light_once,
    "h2o_light": run_h2o_light_once,
}


def run_repeated_holdout_lightweight(
    clean_csv_path: str = CLEAN_CSV_PATH,
    seeds=None,
    frameworks=None,
    save_every_run: bool = True,
) -> pd.DataFrame:
    """Run repeated stratified holdout and save raw per-seed results."""
    if seeds is None:
        seeds = SEEDS
    if frameworks is None:
        frameworks = FRAMEWORKS_TO_RUN

    data = pd.read_csv(clean_csv_path)
    data[TARGET_COL] = data[TARGET_COL].astype(int)

    all_records = []

    for seed in seeds:
        print(f"\n===== Repeated holdout seed={seed} =====")
        for fw in frameworks:
            print(f"Running: {fw}")
            runner = RUNNERS[fw]
            try:
                rec = runner(data, seed)
            except Exception as e:
                rec = base_record(fw, seed)
                rec.update({
                    "status": "failed",
                    "error": repr(e),
                    "best_model": "",
                    "accuracy_pct": np.nan,
                    "auc_pct": np.nan,
                    "f1_pct": np.nan,
                    "precision_pct": np.nan,
                    "recall_pct": np.nan,
                    "logloss": np.nan,
                    "tn": np.nan,
                    "fp": np.nan,
                    "fn": np.nan,
                    "tp": np.nan,
                    "runtime_s": np.nan,
                    "proc_ram_delta_mb": np.nan,
                    "sys_ram_delta_gb": np.nan,
                    "model_size_mb": np.nan,
                    "inner_val_f1_pct": np.nan,
                })
                print(f"FAILED: {fw} | seed={seed} | {e}")
            all_records.append(rec)

            if save_every_run:
                pd.DataFrame(all_records).to_csv(RESULTS_CSV, index=False)

    results_df = pd.DataFrame(all_records)
    results_df.to_csv(RESULTS_CSV, index=False)
    print(f"\nSaved raw repeated-holdout results: {RESULTS_CSV}")
    return results_df


def summarize_repeated_holdout(results_df: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """Create mean±SD summary and budget-compliance table."""
    ok = results_df[results_df["status"] == "ok"].copy()

    metric_cols = [
        "accuracy_pct", "auc_pct", "f1_pct", "precision_pct", "recall_pct", "logloss",
        "runtime_s", "proc_ram_delta_mb", "sys_ram_delta_gb", "model_size_mb",
        "tn", "fp", "fn", "tp"
    ]

    summary = ok.groupby(["framework", "regime"], as_index=False).agg(
        n_runs=("seed", "count"),
        best_model_mode=("best_model", lambda x: x.mode().iloc[0] if len(x.mode()) else x.iloc[0]),
        **{f"{c}_mean": (c, "mean") for c in metric_cols},
        **{f"{c}_sd": (c, "std") for c in metric_cols},
    )
    summary.to_csv(SUMMARY_CSV, index=False)

    formatted_rows = []
    for _, row in summary.iterrows():
        item = {
            "Framework": row["framework"],
            "Regime": row["regime"],
            "n": int(row["n_runs"]),
            "Most frequent best model": row["best_model_mode"],
        }
        for c in ["accuracy_pct", "auc_pct", "f1_pct", "precision_pct", "recall_pct", "logloss", "runtime_s", "model_size_mb"]:
            mean = row[f"{c}_mean"]
            sd = row[f"{c}_sd"]
            item[c.replace("_pct", " (%)").replace("_s", " (s)").replace("_mb", " (MB)")] = f"{mean:.2f} ± {sd:.2f}" if pd.notna(sd) else f"{mean:.2f}"
        formatted_rows.append(item)

    formatted = pd.DataFrame(formatted_rows)
    formatted.to_csv(SUMMARY_FORMATTED_CSV, index=False)

    budget = ok.copy()
    budget["runtime_minus_budget_s"] = budget["runtime_s"] - budget["budget_s"]
    budget["budget_compliant"] = budget["runtime_s"] <= budget["budget_s"]
    budget["runtime_to_budget_ratio"] = budget["runtime_s"] / budget["budget_s"]
    budget_summary = budget.groupby(["framework", "regime"], as_index=False).agg(
        n_runs=("seed", "count"),
        compliant_runs=("budget_compliant", "sum"),
        runtime_mean_s=("runtime_s", "mean"),
        runtime_sd_s=("runtime_s", "std"),
        overhead_mean_s=("runtime_minus_budget_s", "mean"),
        max_overhead_s=("runtime_minus_budget_s", "max"),
        runtime_to_budget_ratio_mean=("runtime_to_budget_ratio", "mean"),
    )
    budget_summary["compliance_rate_pct"] = budget_summary["compliant_runs"] / budget_summary["n_runs"] * 100
    budget_summary.to_csv(BUDGET_CSV, index=False)

    print(f"Saved summary: {SUMMARY_CSV}")
    print(f"Saved formatted summary: {SUMMARY_FORMATTED_CSV}")
    print(f"Saved budget-compliance summary: {BUDGET_CSV}")

    return summary, formatted, budget_summary


# -----------------------------
# Run repeated holdout
# -----------------------------
# Not: Tüm framework'leri 5 seed ile çalıştırmak zaman alabilir.
# Hızlı ilk kontrol için önce şu satırı deneyebilirsiniz:
# FRAMEWORKS_TO_RUN = ["classic_ml_light", "flaml_light"]

results_repeated = run_repeated_holdout_lightweight(
    clean_csv_path=CLEAN_CSV_PATH,
    seeds=SEEDS,
    frameworks=FRAMEWORKS_TO_RUN,
)

summary_repeated, summary_repeated_formatted, budget_repeated = summarize_repeated_holdout(results_repeated)

print("\n=== Repeated Holdout Summary: mean ± SD ===")
display(summary_repeated_formatted)

print("\n=== Budget Compliance Summary ===")
display(budget_repeated)

===== Repeated holdout seed=42 =====
Running: classic_ml_light
Running: autogluon_light
Running: flaml_light

INFO:flaml.tune.searcher.blendsearch:No low-cost partial config given to the search algorithm. For cost-frugal search, consider providing low-cost values for cost-related hps via 'low_cost_partial_config'. More info can be found at https://microsoft.github.io/FLAML/docs/FAQ#about-low_cost_partial_config-in-tune

Running: mljar_light
AutoML directory: repeated_holdout_artifacts/mljar_light_seed_42
The task is binary_classification with evaluation metric logloss
AutoML will use algorithms: ['LightGBM', 'Xgboost', 'CatBoost', 'Random Forest']
AutoML will ensemble available models
AutoML steps: ['simple_algorithms', 'default_algorithms', 'not_so_random', 'ensemble']
Skip simple_algorithms because no parameters were generated.
* Step default_algorithms will try to check up to 4 models
1_Default_LightGBM logloss 0.437943 trained in 8.06 seconds
2_Default_Xgboost logloss 0.422242 trained in 3.11 seconds
3_Default_CatBoost logloss 0.379302 trained in 3.24 seconds
4_Default_RandomForest logloss 0.455071 trained in 5.4 seconds
* Step not_so_random will try to check up to 4 models
6_LightGBM logloss 0.4139 trained in 3.11 seconds
5_Xgboost logloss 0.414338 trained in 4.11 seconds
7_CatBoost logloss 0.402401 trained in 8.61 seconds
8_RandomForest logloss 0.444406 trained in 9.01 seconds
* Step ensemble will try to check up to 1 model
Ensemble logloss 0.379302 trained in 5.68 seconds
AutoML fit time: 75.68 seconds
AutoML best model: 3_Default_CatBoost
Running: h2o_light
Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "17.0.18" 2026-01-20; OpenJDK Runtime Environment (build 17.0.18+8-Ubuntu-122.04.1); OpenJDK 64-Bit Server VM (build 17.0.18+8-Ubuntu-122.04.1, mixed mode, sharing)
  Starting server from /usr/local/lib/python3.12/dist-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmpffombmrr
  JVM stdout: /tmp/tmpffombmrr/h2o_unknownUser_started_from_python.out
  JVM stderr: /tmp/tmpffombmrr/h2o_unknownUser_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  -----------------------------------------------------------------------------------------
H2O_cluster_uptime:         08 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.10
H2O_cluster_version_age:    1 month and 21 days
H2O_cluster_name:           H2O_from_python_unknownUser_71hfe8
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    3.979 Gb
H2O_cluster_total_cores:    2
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null, "colab_language_server": "/usr/colab/bin/language_service"}
H2O_internal_security:      False
Python_version:             3.12.13 final
--------------------------  -----------------------------------------------------------------------------------------

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
AutoML progress: |███████████████████████████████████████████████████████████████| (done) 100%
gbm prediction progress: |███████████████████████████████████████████████████████| (done) 100%

/usr/local/lib/python3.12/dist-packages/h2o/frame.py:1983: H2ODependencyWarning: Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using multi-thread, install polars and pyarrow and use it as pandas_df = h2o_df.as_data_frame(use_multi_thread=True)

/tmp/ipykernel_7251/3713488725.py:520: H2ODeprecationWarning: Deprecated, use ``h2o.cluster().shutdown()``.

H2O session _sid_a1e7 closed.

===== Repeated holdout seed=7 =====
Running: classic_ml_light
Running: autogluon_light
Running: flaml_light

INFO:flaml.tune.searcher.blendsearch:No low-cost partial config given to the search algorithm. For cost-frugal search, consider providing low-cost values for cost-related hps via 'low_cost_partial_config'. More info can be found at https://microsoft.github.io/FLAML/docs/FAQ#about-low_cost_partial_config-in-tune

Running: mljar_light
AutoML directory: repeated_holdout_artifacts/mljar_light_seed_7
The task is binary_classification with evaluation metric logloss
AutoML will use algorithms: ['LightGBM', 'Xgboost', 'CatBoost', 'Random Forest']
AutoML will ensemble available models
AutoML steps: ['simple_algorithms', 'default_algorithms', 'not_so_random', 'ensemble']
Skip simple_algorithms because no parameters were generated.
* Step default_algorithms will try to check up to 4 models
1_Default_LightGBM logloss 0.440735 trained in 3.14 seconds
2_Default_Xgboost logloss 0.436687 trained in 4.05 seconds
3_Default_CatBoost logloss 0.411448 trained in 3.21 seconds
4_Default_RandomForest logloss 0.408385 trained in 4.76 seconds
* Step not_so_random will try to check up to 4 models
6_LightGBM logloss 0.458135 trained in 3.14 seconds
5_Xgboost logloss 0.416567 trained in 4.55 seconds
7_CatBoost logloss 0.408554 trained in 3.89 seconds
8_RandomForest logloss 0.41147 trained in 5.66 seconds
* Step ensemble will try to check up to 1 model
Ensemble logloss 0.398833 trained in 3.93 seconds
AutoML fit time: 52.95 seconds
AutoML best model: Ensemble
Running: h2o_light
Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "17.0.18" 2026-01-20; OpenJDK Runtime Environment (build 17.0.18+8-Ubuntu-122.04.1); OpenJDK 64-Bit Server VM (build 17.0.18+8-Ubuntu-122.04.1, mixed mode, sharing)
  Starting server from /usr/local/lib/python3.12/dist-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmpohxyvg94
  JVM stdout: /tmp/tmpohxyvg94/h2o_unknownUser_started_from_python.out
  JVM stderr: /tmp/tmpohxyvg94/h2o_unknownUser_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  -----------------------------------------------------------------------------------------
H2O_cluster_uptime:         03 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.10
H2O_cluster_version_age:    1 month and 21 days
H2O_cluster_name:           H2O_from_python_unknownUser_k9p34y
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    4 Gb
H2O_cluster_total_cores:    2
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null, "colab_language_server": "/usr/colab/bin/language_service"}
H2O_internal_security:      False
Python_version:             3.12.13 final
--------------------------  -----------------------------------------------------------------------------------------

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
AutoML progress: |███████████████████████████████████████████████████████████████| (done) 100%
gbm prediction progress: |███████████████████████████████████████████████████████| (done) 100%

/usr/local/lib/python3.12/dist-packages/h2o/frame.py:1983: H2ODependencyWarning: Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using multi-thread, install polars and pyarrow and use it as pandas_df = h2o_df.as_data_frame(use_multi_thread=True)

/tmp/ipykernel_7251/3713488725.py:520: H2ODeprecationWarning: Deprecated, use ``h2o.cluster().shutdown()``.

H2O session _sid_83d0 closed.

===== Repeated holdout seed=21 =====
Running: classic_ml_light
Running: autogluon_light
Running: flaml_light

INFO:flaml.tune.searcher.blendsearch:No low-cost partial config given to the search algorithm. For cost-frugal search, consider providing low-cost values for cost-related hps via 'low_cost_partial_config'. More info can be found at https://microsoft.github.io/FLAML/docs/FAQ#about-low_cost_partial_config-in-tune

Running: mljar_light
AutoML directory: repeated_holdout_artifacts/mljar_light_seed_21
The task is binary_classification with evaluation metric logloss
AutoML will use algorithms: ['LightGBM', 'Xgboost', 'CatBoost', 'Random Forest']
AutoML will ensemble available models
AutoML steps: ['simple_algorithms', 'default_algorithms', 'not_so_random', 'ensemble']
Skip simple_algorithms because no parameters were generated.
* Step default_algorithms will try to check up to 4 models
1_Default_LightGBM logloss 0.447938 trained in 3.16 seconds
2_Default_Xgboost logloss 0.476771 trained in 3.44 seconds
3_Default_CatBoost logloss 0.420467 trained in 3.23 seconds
4_Default_RandomForest logloss 0.476498 trained in 5.44 seconds
* Step not_so_random will try to check up to 4 models
6_LightGBM logloss 0.441507 trained in 3.18 seconds
5_Xgboost logloss 0.438444 trained in 3.18 seconds
7_CatBoost logloss 0.432101 trained in 4.35 seconds
8_RandomForest logloss 0.46187 trained in 7.58 seconds
* Step ensemble will try to check up to 1 model
Ensemble logloss 0.418188 trained in 3.02 seconds
AutoML fit time: 53.27 seconds
AutoML best model: Ensemble
Running: h2o_light
Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "17.0.18" 2026-01-20; OpenJDK Runtime Environment (build 17.0.18+8-Ubuntu-122.04.1); OpenJDK 64-Bit Server VM (build 17.0.18+8-Ubuntu-122.04.1, mixed mode, sharing)
  Starting server from /usr/local/lib/python3.12/dist-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmplsnok79f
  JVM stdout: /tmp/tmplsnok79f/h2o_unknownUser_started_from_python.out
  JVM stderr: /tmp/tmplsnok79f/h2o_unknownUser_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  -----------------------------------------------------------------------------------------
H2O_cluster_uptime:         02 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.10
H2O_cluster_version_age:    1 month and 21 days
H2O_cluster_name:           H2O_from_python_unknownUser_aqqiud
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    4 Gb
H2O_cluster_total_cores:    2
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null, "colab_language_server": "/usr/colab/bin/language_service"}
H2O_internal_security:      False
Python_version:             3.12.13 final
--------------------------  -----------------------------------------------------------------------------------------

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
AutoML progress: |███████████████████████████████████████████████████████████████| (done) 100%
xgboost prediction progress: |███████████████████████████████████████████████████| (done) 100%

/usr/local/lib/python3.12/dist-packages/h2o/frame.py:1983: H2ODependencyWarning: Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using multi-thread, install polars and pyarrow and use it as pandas_df = h2o_df.as_data_frame(use_multi_thread=True)

/tmp/ipykernel_7251/3713488725.py:520: H2ODeprecationWarning: Deprecated, use ``h2o.cluster().shutdown()``.

H2O session _sid_8b63 closed.

===== Repeated holdout seed=84 =====
Running: classic_ml_light
Running: autogluon_light
Running: flaml_light

INFO:flaml.tune.searcher.blendsearch:No low-cost partial config given to the search algorithm. For cost-frugal search, consider providing low-cost values for cost-related hps via 'low_cost_partial_config'. More info can be found at https://microsoft.github.io/FLAML/docs/FAQ#about-low_cost_partial_config-in-tune

Running: mljar_light
AutoML directory: repeated_holdout_artifacts/mljar_light_seed_84
The task is binary_classification with evaluation metric logloss
AutoML will use algorithms: ['LightGBM', 'Xgboost', 'CatBoost', 'Random Forest']
AutoML will ensemble available models
AutoML steps: ['simple_algorithms', 'default_algorithms', 'not_so_random', 'ensemble']
Skip simple_algorithms because no parameters were generated.
* Step default_algorithms will try to check up to 4 models
1_Default_LightGBM logloss 0.465076 trained in 3.13 seconds
2_Default_Xgboost logloss 0.474711 trained in 3.22 seconds
3_Default_CatBoost logloss 0.42273 trained in 4.18 seconds
4_Default_RandomForest logloss 0.461584 trained in 10.8 seconds
* Step not_so_random will try to check up to 4 models
6_LightGBM logloss 0.457209 trained in 3.12 seconds
5_Xgboost logloss 0.687228 trained in 0.98 seconds
7_CatBoost logloss 0.449356 trained in 4.14 seconds
8_RandomForest logloss 0.463549 trained in 4.64 seconds
* Step ensemble will try to check up to 1 model
Ensemble logloss 0.422563 trained in 3.26 seconds
AutoML fit time: 52.46 seconds
AutoML best model: Ensemble
Running: h2o_light
Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "17.0.18" 2026-01-20; OpenJDK Runtime Environment (build 17.0.18+8-Ubuntu-122.04.1); OpenJDK 64-Bit Server VM (build 17.0.18+8-Ubuntu-122.04.1, mixed mode, sharing)
  Starting server from /usr/local/lib/python3.12/dist-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmpqav13vmy
  JVM stdout: /tmp/tmpqav13vmy/h2o_unknownUser_started_from_python.out
  JVM stderr: /tmp/tmpqav13vmy/h2o_unknownUser_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  -----------------------------------------------------------------------------------------
H2O_cluster_uptime:         02 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.10
H2O_cluster_version_age:    1 month and 21 days
H2O_cluster_name:           H2O_from_python_unknownUser_i2v0xk
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    4 Gb
H2O_cluster_total_cores:    2
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null, "colab_language_server": "/usr/colab/bin/language_service"}
H2O_internal_security:      False
Python_version:             3.12.13 final
--------------------------  -----------------------------------------------------------------------------------------

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
AutoML progress: |███████████████████████████████████████████████████████████████| (done) 100%
xgboost prediction progress: |███████████████████████████████████████████████████| (done) 100%

/usr/local/lib/python3.12/dist-packages/h2o/frame.py:1983: H2ODependencyWarning: Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using multi-thread, install polars and pyarrow and use it as pandas_df = h2o_df.as_data_frame(use_multi_thread=True)

/tmp/ipykernel_7251/3713488725.py:520: H2ODeprecationWarning: Deprecated, use ``h2o.cluster().shutdown()``.

H2O session _sid_a505 closed.

===== Repeated holdout seed=123 =====
Running: classic_ml_light
Running: autogluon_light
Running: flaml_light

INFO:flaml.tune.searcher.blendsearch:No low-cost partial config given to the search algorithm. For cost-frugal search, consider providing low-cost values for cost-related hps via 'low_cost_partial_config'. More info can be found at https://microsoft.github.io/FLAML/docs/FAQ#about-low_cost_partial_config-in-tune

Running: mljar_light
AutoML directory: repeated_holdout_artifacts/mljar_light_seed_123
The task is binary_classification with evaluation metric logloss
AutoML will use algorithms: ['LightGBM', 'Xgboost', 'CatBoost', 'Random Forest']
AutoML will ensemble available models
AutoML steps: ['simple_algorithms', 'default_algorithms', 'not_so_random', 'ensemble']
Skip simple_algorithms because no parameters were generated.
* Step default_algorithms will try to check up to 4 models
1_Default_LightGBM logloss 0.487264 trained in 4.01 seconds
2_Default_Xgboost logloss 0.489264 trained in 3.18 seconds
3_Default_CatBoost logloss 0.452073 trained in 3.34 seconds
4_Default_RandomForest logloss 0.465593 trained in 4.31 seconds
* Step not_so_random will try to check up to 4 models
6_LightGBM logloss 0.463509 trained in 3.16 seconds
5_Xgboost logloss 0.48825 trained in 3.88 seconds
7_CatBoost logloss 0.453174 trained in 3.38 seconds
8_RandomForest logloss 0.472068 trained in 5.68 seconds
* Step ensemble will try to check up to 1 model
Ensemble logloss 0.448501 trained in 2.77 seconds
AutoML fit time: 49.43 seconds
AutoML best model: Ensemble
Running: h2o_light
Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "17.0.18" 2026-01-20; OpenJDK Runtime Environment (build 17.0.18+8-Ubuntu-122.04.1); OpenJDK 64-Bit Server VM (build 17.0.18+8-Ubuntu-122.04.1, mixed mode, sharing)
  Starting server from /usr/local/lib/python3.12/dist-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmpc5tbh2et
  JVM stdout: /tmp/tmpc5tbh2et/h2o_unknownUser_started_from_python.out
  JVM stderr: /tmp/tmpc5tbh2et/h2o_unknownUser_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  -----------------------------------------------------------------------------------------
H2O_cluster_uptime:         04 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.10
H2O_cluster_version_age:    1 month and 21 days
H2O_cluster_name:           H2O_from_python_unknownUser_3h5qh6
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    4 Gb
H2O_cluster_total_cores:    2
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null, "colab_language_server": "/usr/colab/bin/language_service"}
H2O_internal_security:      False
Python_version:             3.12.13 final
--------------------------  -----------------------------------------------------------------------------------------

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
AutoML progress: |███████████████████████████████████████████████████████████████| (done) 100%
xgboost prediction progress: |███████████████████████████████████████████████████| (done) 100%

/usr/local/lib/python3.12/dist-packages/h2o/frame.py:1983: H2ODependencyWarning: Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using multi-thread, install polars and pyarrow and use it as pandas_df = h2o_df.as_data_frame(use_multi_thread=True)

/tmp/ipykernel_7251/3713488725.py:520: H2ODeprecationWarning: Deprecated, use ``h2o.cluster().shutdown()``.

H2O session _sid_9f46 closed.

Saved raw repeated-holdout results: repeated_holdout_light_results.csv
Saved summary: repeated_holdout_light_summary.csv
Saved formatted summary: repeated_holdout_light_summary_formatted.csv
Saved budget-compliance summary: repeated_holdout_light_budget_compliance.csv

=== Repeated Holdout Summary: mean ± SD ===

,Framework,Regime,n,Most frequent best model,accuracy (%),auc (%),f1 (%),precision (%),recall (%),logloss,runtime (s),model (s)ize (MB)
0,AutoGluon_Light,Lightweight,5,LightGBM,80.65 ± 3.11,89.16 ± 2.29,83.97 ± 1.95,78.16 ± 4.75,90.98 ± 2.44,0.42 ± 0.03,9.53 ± 7.43,13.04 ± 0.25
1,ClassicML_Light,Lightweight,5,ExtraTrees,80.65 ± 3.09,88.09 ± 2.29,82.86 ± 2.68,81.47 ± 3.03,84.31 ± 2.50,0.43 ± 0.04,3.41 ± 3.52,7.69 ± 5.58
2,FLAML_Light,Lightweight,5,lgbm,80.43 ± 3.99,88.17 ± 3.48,82.40 ± 3.68,82.15 ± 3.64,82.75 ± 4.88,0.44 ± 0.07,67.17 ± 15.96,0.02 ± 0.01
3,H2O_Light,Lightweight,5,H2OXGBoostEstimator,76.20 ± 1.78,84.83 ± 2.89,80.53 ± 1.13,73.89 ± 3.18,88.82 ± 5.03,0.51 ± 0.09,79.27 ± 6.63,0.23 ± 0.25
4,MLJAR_Light,Lightweight,5,Ensemble,79.67 ± 2.57,88.71 ± 2.16,82.69 ± 2.37,78.70 ± 5.71,88.04 ± 8.16,0.42 ± 0.04,65.72 ± 10.85,11.30 ± 5.50

=== Budget Compliance Summary ===

,framework,regime,n_runs,compliant_runs,runtime_mean_s,runtime_sd_s,overhead_mean_s,max_overhead_s,runtime_to_budget_ratio_mean,compliance_rate_pct
0,AutoGluon_Light,Lightweight,5,5,9.534471,7.427061,-50.465529,-37.202540,0.158908,100.0
1,ClassicML_Light,Lightweight,5,5,3.414881,3.516119,-56.585119,-50.308104,0.056915,100.0
2,FLAML_Light,Lightweight,5,0,67.172160,15.960701,7.172160,35.723528,1.119536,0.0
3,H2O_Light,Lightweight,5,0,79.267280,6.625973,19.267280,30.958422,1.321121,0.0
4,MLJAR_Light,Lightweight,5,1,65.719477,10.849212,5.719477,24.907514,1.095325,20.0

In [7]:
# @title
# ============================================================
# WILCOXON / FRIEDMAN STATISTICAL TESTS FOR REPEATED HOLDOUT
# Purpose: address reviewer concern about statistical validation
# Required input:
#   - repeated_holdout_light_results.csv  (preferred), or
#   - results_repeated.csv                (fallback)
# Outputs:
#   - statistical_tests_friedman.csv
#   - statistical_tests_wilcoxon_holm.csv
#   - statistical_tests_readme.csv
# ============================================================

import itertools
import math
from pathlib import Path

import numpy as np
import pandas as pd

try:
    from IPython.display import display
except Exception:
    def display(obj):
        print(obj)

try:
    from scipy.stats import friedmanchisquare, wilcoxon
except Exception as e:
    raise ImportError(
        "This block requires scipy. In Colab, run: !pip install scipy"
    ) from e

# -----------------------------
# Configuration
# -----------------------------
INPUT_CANDIDATES = [
    "repeated_holdout_light_results.csv",  # output from the repeated stratified holdout block
    "results_repeated.csv",                # fallback name used by some notebook versions
]

FRIEDMAN_OUT = "statistical_tests_friedman.csv"
WILCOXON_OUT = "statistical_tests_wilcoxon_holm.csv"
README_OUT = "statistical_tests_readme.csv"

# Metrics to test. The block automatically skips metrics not found in the result file.
METRICS_TO_TEST = [
    "f1_pct",
    "auc_pct",
    "accuracy_pct",
    "precision_pct",
    "recall_pct",
    "logloss",
    "runtime_s",
    "model_size_mb",
]

# Direction used only for the descriptive "better_method" column.
# Statistical p-values are two-sided.
METRIC_DIRECTION = {
    "f1_pct": "higher",
    "auc_pct": "higher",
    "accuracy_pct": "higher",
    "precision_pct": "higher",
    "recall_pct": "higher",
    "logloss": "lower",
    "runtime_s": "lower",
    "model_size_mb": "lower",
}

ALPHA = 0.05
MIN_PAIRED_RUNS = 3  # recommended minimum for reporting paired tests in this small benchmark


def _find_input_file(candidates):
    for file_name in candidates:
        if Path(file_name).exists():
            return file_name
    raise FileNotFoundError(
        "No repeated holdout result file was found. Run the repeated stratified holdout block first. "
        f"Expected one of: {candidates}"
    )


def _holm_adjust(p_values):
    """Holm-Bonferroni adjusted p-values. Returns adjusted p-values in original order."""
    p_values = np.asarray(p_values, dtype=float)
    n = len(p_values)
    if n == 0:
        return []

    order = np.argsort(p_values)
    sorted_p = p_values[order]
    adjusted_sorted = np.empty(n, dtype=float)

    # Holm adjusted p for ordered p_i: max_{j<=i} ((m-j+1) * p_j), capped at 1.
    running_max = 0.0
    for rank, p in enumerate(sorted_p, start=1):
        adjusted = (n - rank + 1) * p
        running_max = max(running_max, adjusted)
        adjusted_sorted[rank - 1] = min(running_max, 1.0)

    adjusted = np.empty(n, dtype=float)
    adjusted[order] = adjusted_sorted
    return adjusted.tolist()


def _safe_friedman(pivot_df):
    """Run Friedman test on a complete paired pivot table: rows=seeds, cols=methods."""
    if pivot_df.shape[0] < MIN_PAIRED_RUNS or pivot_df.shape[1] < 3:
        return np.nan, np.nan, "skipped: requires at least 3 paired runs and 3 methods"

    arrays = [pivot_df[col].to_numpy(dtype=float) for col in pivot_df.columns]

    try:
        stat, p = friedmanchisquare(*arrays)
        return float(stat), float(p), "ok"
    except Exception as e:
        return np.nan, np.nan, f"skipped/error: {type(e).__name__}: {e}"


def _safe_wilcoxon(x, y):
    """Run paired Wilcoxon signed-rank test safely for small repeated-holdout samples."""
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    mask = np.isfinite(x) & np.isfinite(y)
    x = x[mask]
    y = y[mask]

    if len(x) < MIN_PAIRED_RUNS:
        return np.nan, np.nan, "skipped: fewer than minimum paired runs"

    diff = x - y
    if np.allclose(diff, 0):
        return 0.0, 1.0, "ok: all paired differences are zero"

    try:
        stat, p = wilcoxon(x, y, zero_method="wilcox", alternative="two-sided", mode="auto")
        return float(stat), float(p), "ok"
    except TypeError:
        # Older SciPy versions may not support mode="auto".
        try:
            stat, p = wilcoxon(x, y, zero_method="wilcox", alternative="two-sided")
            return float(stat), float(p), "ok"
        except Exception as e:
            return np.nan, np.nan, f"skipped/error: {type(e).__name__}: {e}"
    except Exception as e:
        return np.nan, np.nan, f"skipped/error: {type(e).__name__}: {e}"


def _prepare_success_rows(df):
    df = df.copy()

    if "status" in df.columns:
        df = df[df["status"].astype(str).str.lower().eq("ok")].copy()

    # Ensure seed exists. If absent, create a dummy seed index, but paired tests are mainly meaningful with real seeds.
    if "seed" not in df.columns:
        df["seed"] = np.arange(len(df))

    # Coerce metric columns to numeric.
    for col in METRICS_TO_TEST:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    if "framework" not in df.columns:
        df["framework"] = "UnknownFramework"
    if "model" not in df.columns:
        df["model"] = df["framework"]
    if "selection_type" not in df.columns:
        df["selection_type"] = "framework_run"

    return df


def _make_analysis_sets(df):
    """
    Build paired comparison sets.
    1) Framework-level selected/framework runs: compares AutoML frameworks or selected classical ML wrapper if available.
    2) Candidate-model comparison within each framework: compares model candidates across the same repeated splits.
    3) All method-level rows: compares every unique framework/model combination when paired seeds exist.
    """
    sets = []

    # A) Framework-level selected/framework runs
    selected_labels = {
        "selected_by_inner_validation",
        "framework_run",
        "automl_framework",
        "automl_run",
        "selected_model",
    }
    selected_df = df[df["selection_type"].astype(str).isin(selected_labels)].copy()
    if not selected_df.empty:
        selected_df["method"] = selected_df["framework"].astype(str)
        sets.append(("framework_level_selected_runs", selected_df))

    # B) Candidate-model comparisons within each framework
    candidate_df = df[df["selection_type"].astype(str).eq("candidate_model")].copy()
    if not candidate_df.empty:
        for fw, g in candidate_df.groupby("framework"):
            g = g.copy()
            g["method"] = g["model"].astype(str)
            sets.append((f"candidate_models_within_{fw}", g))

    # C) Generic method-level comparison for all rows
    generic_df = df.copy()
    generic_df["method"] = np.where(
        generic_df["model"].astype(str).eq(generic_df["framework"].astype(str)),
        generic_df["framework"].astype(str),
        generic_df["framework"].astype(str) + " | " + generic_df["model"].astype(str),
    )
    sets.append(("all_available_method_rows", generic_df))

    return sets


def _paired_pivot(g, metric):
    """Return complete paired pivot with rows=seed, columns=method."""
    if metric not in g.columns:
        return pd.DataFrame()

    # Average duplicate seed/method rows if any exist.
    pivot = (
        g.pivot_table(index="seed", columns="method", values=metric, aggfunc="mean")
        .sort_index()
    )

    # Keep only methods with at least MIN_PAIRED_RUNS observations.
    valid_cols = [c for c in pivot.columns if pivot[c].notna().sum() >= MIN_PAIRED_RUNS]
    pivot = pivot[valid_cols]

    # Friedman/Wilcoxon should use matched seeds; drop incomplete rows.
    pivot = pivot.dropna(axis=0, how="any")
    return pivot


def _better_method(metric, method_a, mean_a, method_b, mean_b):
    direction = METRIC_DIRECTION.get(metric, "higher")
    if np.isclose(mean_a, mean_b, equal_nan=False):
        return "tie"
    if direction == "lower":
        return method_a if mean_a < mean_b else method_b
    return method_a if mean_a > mean_b else method_b


# -----------------------------
# Run tests
# -----------------------------
input_file = _find_input_file(INPUT_CANDIDATES)
results_df = pd.read_csv(input_file)
results_df = _prepare_success_rows(results_df)

available_metrics = [m for m in METRICS_TO_TEST if m in results_df.columns]
analysis_sets = _make_analysis_sets(results_df)

friedman_rows = []
wilcoxon_rows = []

for analysis_name, g in analysis_sets:
    if g.empty or "method" not in g.columns:
        continue

    for metric in available_metrics:
        pivot = _paired_pivot(g, metric)
        methods = list(pivot.columns)
        n_paired = int(pivot.shape[0])

        # Friedman: omnibus test for >=3 methods.
        stat, p, note = _safe_friedman(pivot)
        if len(methods) >= 3:
            friedman_rows.append({
                "analysis_set": analysis_name,
                "metric": metric,
                "n_paired_splits": n_paired,
                "n_methods": len(methods),
                "methods": "; ".join(map(str, methods)),
                "friedman_statistic": stat,
                "p_value": p,
                "significant_at_0_05": bool(pd.notna(p) and p < ALPHA),
                "note": note,
            })

        # Pairwise Wilcoxon: all pairs for >=2 methods.
        pair_rows_for_this_metric = []
        if len(methods) >= 2 and n_paired >= MIN_PAIRED_RUNS:
            for method_a, method_b in itertools.combinations(methods, 2):
                x = pivot[method_a].to_numpy(dtype=float)
                y = pivot[method_b].to_numpy(dtype=float)
                w_stat, w_p, w_note = _safe_wilcoxon(x, y)

                mean_a = float(np.mean(x))
                mean_b = float(np.mean(y))
                row = {
                    "analysis_set": analysis_name,
                    "metric": metric,
                    "n_paired_splits": n_paired,
                    "method_a": method_a,
                    "method_b": method_b,
                    "mean_a": mean_a,
                    "mean_b": mean_b,
                    "mean_diff_a_minus_b": mean_a - mean_b,
                    "better_method_descriptive": _better_method(metric, method_a, mean_a, method_b, mean_b),
                    "wilcoxon_statistic": w_stat,
                    "p_value_raw": w_p,
                    "p_value_holm": np.nan,  # filled below within each analysis_set + metric family
                    "significant_raw_0_05": bool(pd.notna(w_p) and w_p < ALPHA),
                    "significant_holm_0_05": False,
                    "note": w_note,
                }
                pair_rows_for_this_metric.append(row)

        # Holm correction is applied within each analysis set and metric.
        raw_ps = [r["p_value_raw"] for r in pair_rows_for_this_metric if pd.notna(r["p_value_raw"])]
        adjusted_ps = _holm_adjust(raw_ps)
        adj_iter = iter(adjusted_ps)
        for r in pair_rows_for_this_metric:
            if pd.notna(r["p_value_raw"]):
                r["p_value_holm"] = next(adj_iter)
                r["significant_holm_0_05"] = bool(r["p_value_holm"] < ALPHA)
            wilcoxon_rows.append(r)

friedman_df = pd.DataFrame(friedman_rows)
wilcoxon_df = pd.DataFrame(wilcoxon_rows)

# Round for readability while preserving enough precision for reporting.
for df_ in [friedman_df, wilcoxon_df]:
    for col in df_.select_dtypes(include=["float", "float64"]).columns:
        df_[col] = df_[col].round(6)

friedman_df.to_csv(FRIEDMAN_OUT, index=False)
wilcoxon_df.to_csv(WILCOXON_OUT, index=False)

readme_df = pd.DataFrame([
    {
        "item": "input_file",
        "value": input_file,
        "note": "Repeated holdout results used for paired statistical tests.",
    },
    {
        "item": "friedman_test",
        "value": FRIEDMAN_OUT,
        "note": "Omnibus non-parametric test across three or more paired methods. Rows with incomplete seed-method pairs are excluded per metric.",
    },
    {
        "item": "wilcoxon_holm_tests",
        "value": WILCOXON_OUT,
        "note": "Pairwise two-sided Wilcoxon signed-rank tests with Holm-Bonferroni correction applied within each analysis set and metric.",
    },
    {
        "item": "minimum_paired_runs",
        "value": str(MIN_PAIRED_RUNS),
        "note": "Tests with fewer paired repeated splits are skipped to avoid unstable reporting.",
    },
    {
        "item": "interpretation_warning",
        "value": "exploratory statistical validation",
        "note": "Because repeated holdout splits are not fully independent, p-values should be interpreted as robustness indicators rather than definitive clinical evidence.",
    },
])
readme_df.to_csv(README_OUT, index=False)

print("Statistical testing complete.")
print(f"Input file: {input_file}")
print(f"Saved: {FRIEDMAN_OUT} | shape={friedman_df.shape}")
print(f"Saved: {WILCOXON_OUT} | shape={wilcoxon_df.shape}")
print(f"Saved: {README_OUT}")

if not friedman_df.empty:
    display(friedman_df.head(20))
else:
    print("No Friedman tests were run. At least three methods with complete paired repeated splits are required.")

if not wilcoxon_df.empty:
    display(wilcoxon_df.head(20))
else:
    print("No Wilcoxon tests were run. At least two methods with complete paired repeated splits are required.")

Statistical testing complete.
Input file: repeated_holdout_light_results.csv
Saved: statistical_tests_friedman.csv | shape=(16, 9)
Saved: statistical_tests_wilcoxon_holm.csv | shape=(160, 15)
Saved: statistical_tests_readme.csv

,analysis_set,metric,n_paired_splits,n_methods,methods,friedman_statistic,p_value,significant_at_0_05,note
0,framework_level_selected_runs,f1_pct,5,5,AutoGluon_Light; ClassicML_Light; FLAML_Light;...,7.040000,0.133789,False,ok
1,framework_level_selected_runs,auc_pct,5,5,AutoGluon_Light; ClassicML_Light; FLAML_Light;...,13.280000,0.009986,True,ok
2,framework_level_selected_runs,accuracy_pct,5,5,AutoGluon_Light; ClassicML_Light; FLAML_Light;...,5.404255,0.248275,False,ok
3,framework_level_selected_runs,precision_pct,5,5,AutoGluon_Light; ClassicML_Light; FLAML_Light;...,6.560000,0.161049,False,ok
4,framework_level_selected_runs,recall_pct,5,5,AutoGluon_Light; ClassicML_Light; FLAML_Light;...,9.072165,0.059321,False,ok
5,framework_level_selected_runs,logloss,5,5,AutoGluon_Light; ClassicML_Light; FLAML_Light;...,12.320000,0.015124,True,ok
6,framework_level_selected_runs,runtime_s,5,5,AutoGluon_Light; ClassicML_Light; FLAML_Light;...,17.920000,0.001279,True,ok
7,framework_level_selected_runs,model_size_mb,5,5,AutoGluon_Light; ClassicML_Light; FLAML_Light;...,15.680000,0.003480,True,ok
8,all_available_method_rows,f1_pct,5,5,AutoGluon_Light; ClassicML_Light; FLAML_Light;...,7.040000,0.133789,False,ok
9,all_available_method_rows,auc_pct,5,5,AutoGluon_Light; ClassicML_Light; FLAML_Light;...,13.280000,0.009986,True,ok
10,all_available_method_rows,accuracy_pct,5,5,AutoGluon_Light; ClassicML_Light; FLAML_Light;...,5.404255,0.248275,False,ok
11,all_available_method_rows,precision_pct,5,5,AutoGluon_Light; ClassicML_Light; FLAML_Light;...,6.560000,0.161049,False,ok
12,all_available_method_rows,recall_pct,5,5,AutoGluon_Light; ClassicML_Light; FLAML_Light;...,9.072165,0.059321,False,ok
13,all_available_method_rows,logloss,5,5,AutoGluon_Light; ClassicML_Light; FLAML_Light;...,12.320000,0.015124,True,ok
14,all_available_method_rows,runtime_s,5,5,AutoGluon_Light; ClassicML_Light; FLAML_Light;...,17.920000,0.001279,True,ok
15,all_available_method_rows,model_size_mb,5,5,AutoGluon_Light; ClassicML_Light; FLAML_Light;...,15.680000,0.003480,True,ok

,analysis_set,metric,n_paired_splits,method_a,method_b,mean_a,mean_b,mean_diff_a_minus_b,better_method_descriptive,wilcoxon_statistic,p_value_raw,p_value_holm,significant_raw_0_05,significant_holm_0_05,note
0,framework_level_selected_runs,f1_pct,5,AutoGluon_Light,ClassicML_Light,83.968749,82.860053,1.108696,AutoGluon_Light,4.0,0.4375,1.0000,False,False,ok
1,framework_level_selected_runs,f1_pct,5,AutoGluon_Light,FLAML_Light,83.968749,82.397581,1.571168,AutoGluon_Light,5.0,0.6250,1.0000,False,False,ok
2,framework_level_selected_runs,f1_pct,5,AutoGluon_Light,H2O_Light,83.968749,80.529812,3.438937,AutoGluon_Light,0.0,0.0625,0.6250,False,False,ok
3,framework_level_selected_runs,f1_pct,5,AutoGluon_Light,MLJAR_Light,83.968749,82.694597,1.274152,AutoGluon_Light,0.0,0.0625,0.6250,False,False,ok
4,framework_level_selected_runs,f1_pct,5,ClassicML_Light,FLAML_Light,82.860053,82.397581,0.462472,ClassicML_Light,7.0,1.0000,1.0000,False,False,ok
5,framework_level_selected_runs,f1_pct,5,ClassicML_Light,H2O_Light,82.860053,80.529812,2.330241,ClassicML_Light,3.0,0.3125,1.0000,False,False,ok
6,framework_level_selected_runs,f1_pct,5,ClassicML_Light,MLJAR_Light,82.860053,82.694597,0.165456,ClassicML_Light,7.0,1.0000,1.0000,False,False,ok
7,framework_level_selected_runs,f1_pct,5,FLAML_Light,H2O_Light,82.397581,80.529812,1.867769,FLAML_Light,4.0,0.4375,1.0000,False,False,ok
8,framework_level_selected_runs,f1_pct,5,FLAML_Light,MLJAR_Light,82.397581,82.694597,-0.297017,MLJAR_Light,7.0,1.0000,1.0000,False,False,ok
9,framework_level_selected_runs,f1_pct,5,H2O_Light,MLJAR_Light,80.529812,82.694597,-2.164785,MLJAR_Light,1.0,0.1250,1.0000,False,False,ok
10,framework_level_selected_runs,auc_pct,5,AutoGluon_Light,ClassicML_Light,89.163080,88.091822,1.071258,AutoGluon_Light,0.0,0.0625,0.6250,False,False,ok
11,framework_level_selected_runs,auc_pct,5,AutoGluon_Light,FLAML_Light,89.163080,88.174319,0.988761,AutoGluon_Light,3.0,0.3125,1.0000,False,False,ok
12,framework_level_selected_runs,auc_pct,5,AutoGluon_Light,H2O_Light,89.163080,84.832616,4.330464,AutoGluon_Light,0.0,0.0625,0.6250,False,False,ok
13,framework_level_selected_runs,auc_pct,5,AutoGluon_Light,MLJAR_Light,89.163080,88.711143,0.451937,AutoGluon_Light,3.0,0.3125,1.0000,False,False,ok
14,framework_level_selected_runs,auc_pct,5,ClassicML_Light,FLAML_Light,88.091822,88.174319,-0.082496,FLAML_Light,7.0,1.0000,1.0000,False,False,ok
15,framework_level_selected_runs,auc_pct,5,ClassicML_Light,H2O_Light,88.091822,84.832616,3.259206,ClassicML_Light,0.0,0.0625,0.6250,False,False,ok
16,framework_level_selected_runs,auc_pct,5,ClassicML_Light,MLJAR_Light,88.091822,88.711143,-0.619321,MLJAR_Light,2.0,0.1875,0.9375,False,False,ok
17,framework_level_selected_runs,auc_pct,5,FLAML_Light,H2O_Light,88.174319,84.832616,3.341703,FLAML_Light,0.0,0.0625,0.6250,False,False,ok
18,framework_level_selected_runs,auc_pct,5,FLAML_Light,MLJAR_Light,88.174319,88.711143,-0.536824,MLJAR_Light,5.0,0.6250,1.0000,False,False,ok
19,framework_level_selected_runs,auc_pct,5,H2O_Light,MLJAR_Light,84.832616,88.711143,-3.878527,MLJAR_Light,0.0,0.0625,0.6250,False,False,ok

In [8]:
# @title
# ============================================================
# TARGET SENSITIVITY ANALYSIS
# Reviewer Revision Block
# ------------------------------------------------------------
# Purpose:
# - To address the reviewer concern that binarizing the original
#   0–4 heart disease target may collapse clinically meaningful
#   severity information.
#
# This block compares three target formulations:
#   1) Binary:       0 vs. 1–4
#   2) Ordinal-3:    0 vs. 1–2 vs. 3–4
#   3) Multiclass-5: 0 vs. 1 vs. 2 vs. 3 vs. 4
#
# Outputs:
#   target_sensitivity_outputs/
#       target_sensitivity_results.csv
#       target_sensitivity_summary.csv
#       target_sensitivity_summary_formatted.csv
#       target_sensitivity_class_distribution.csv
#       target_sensitivity_best_by_formulation.csv
#       target_sensitivity_confusion_matrices_long.csv
#       target_sensitivity_readme.csv
# ============================================================

import os
import time
import warnings
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
    log_loss,
    confusion_matrix
)

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier

warnings.filterwarnings("ignore")

# Optional models
try:
    from xgboost import XGBClassifier
    HAS_XGBOOST = True
except Exception:
    HAS_XGBOOST = False

try:
    from lightgbm import LGBMClassifier
    HAS_LIGHTGBM = True
except Exception:
    HAS_LIGHTGBM = False


# -----------------------------
# Configuration
# -----------------------------
RAW_CSV_PATH = "cleveland_hungarian_long-beach-va_switzerland.csv"
OUTPUT_DIR = "target_sensitivity_outputs"

SENSITIVITY_SEEDS = [42, 7, 21, 84, 123]
TEST_SIZE = 0.20

os.makedirs(OUTPUT_DIR, exist_ok=True)


# -----------------------------
# Data loading and preprocessing
# -----------------------------
def load_raw_heart_dataset(csv_path):
    """
    Loads the original merged UCI Heart Disease CSV.
    Keeps the original 0–4 target before creating alternative target formulations.
    """
    df = pd.read_csv(
        csv_path,
        na_values=["?", "??", "???", "????", " ?"],
        skipinitialspace=True,
        engine="python"
    )

    df.columns = [c.strip() for c in df.columns]

    expected_cols = [
        "age", "sex", "cp", "trestbps", "chol", "fbs", "restecg",
        "thalach", "exang", "oldpeak", "slope", "ca", "thal", "target"
    ]

    missing_cols = [c for c in expected_cols if c not in df.columns]
    if missing_cols:
        raise ValueError(
            f"Missing expected columns: {missing_cols}\n"
            f"Available columns: {list(df.columns)}"
        )

    df = df[expected_cols].copy()

    for col in expected_cols:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    # Drop rows with missing target
    df = df[df["target"].notna()].copy()

    # Keep only valid original target labels 0–4
    df = df[df["target"].isin([0, 1, 2, 3, 4])].copy()
    df["target"] = df["target"].astype(int)

    feature_cols = [c for c in expected_cols if c != "target"]

    # Median imputation using the whole dataset for sensitivity screening.
    # For final strict leakage-free protocol, this can be moved inside each split.
    medians = df[feature_cols].median(numeric_only=True)
    df[feature_cols] = df[feature_cols].fillna(medians)

    return df, feature_cols


def add_target_formulations(df):
    """
    Adds three alternative target formulations:
    - binary_0_vs_1_4
    - ordinal_3class_0_vs_1_2_vs_3_4
    - multiclass_5class_0_1_2_3_4
    """
    df = df.copy()

    # Main binary formulation: 0 vs. 1–4
    df["binary_0_vs_1_4"] = (df["target"] > 0).astype(int)

    # Ordinal grouped formulation:
    # 0 = no disease
    # 1 = mild/moderate disease: original target 1–2
    # 2 = severe disease: original target 3–4
    def map_ordinal_3class(x):
        if x == 0:
            return 0
        elif x in [1, 2]:
            return 1
        elif x in [3, 4]:
            return 2
        else:
            return np.nan

    df["ordinal_3class_0_vs_1_2_vs_3_4"] = df["target"].apply(map_ordinal_3class).astype(int)

    # Original 5-class target
    df["multiclass_5class_0_1_2_3_4"] = df["target"].astype(int)

    return df


# -----------------------------
# Model registry
# -----------------------------
def build_sensitivity_models(n_classes, seed):
    """
    Lightweight classical ML baselines for target sensitivity analysis.
    These models are intentionally used as a robustness/sensitivity check,
    not as a replacement for the full AutoML benchmark.
    """
    models = {}

    models["LogisticRegression_balanced"] = Pipeline([
        ("scaler", StandardScaler()),
        ("clf", LogisticRegression(
            max_iter=2000,
            class_weight="balanced",
            random_state=seed,
            multi_class="auto"
        ))
    ])

    models["RandomForest_balanced"] = RandomForestClassifier(
        n_estimators=300,
        max_depth=None,
        min_samples_leaf=2,
        class_weight="balanced",
        random_state=seed,
        n_jobs=-1
    )

    models["ExtraTrees_balanced"] = ExtraTreesClassifier(
        n_estimators=300,
        max_depth=None,
        min_samples_leaf=2,
        class_weight="balanced",
        random_state=seed,
        n_jobs=-1
    )

    if HAS_XGBOOST:
        if n_classes == 2:
            models["XGBoost_fixed"] = XGBClassifier(
                n_estimators=300,
                max_depth=3,
                learning_rate=0.05,
                subsample=0.9,
                colsample_bytree=0.9,
                objective="binary:logistic",
                eval_metric="logloss",
                random_state=seed,
                n_jobs=-1
            )
        else:
            models["XGBoost_fixed"] = XGBClassifier(
                n_estimators=300,
                max_depth=3,
                learning_rate=0.05,
                subsample=0.9,
                colsample_bytree=0.9,
                objective="multi:softprob",
                eval_metric="mlogloss",
                num_class=n_classes,
                random_state=seed,
                n_jobs=-1
            )

    if HAS_LIGHTGBM:
        if n_classes == 2:
            models["LightGBM_fixed"] = LGBMClassifier(
                n_estimators=300,
                max_depth=-1,
                learning_rate=0.05,
                class_weight="balanced",
                random_state=seed,
                n_jobs=-1,
                verbose=-1
            )
        else:
            models["LightGBM_fixed"] = LGBMClassifier(
                n_estimators=300,
                max_depth=-1,
                learning_rate=0.05,
                objective="multiclass",
                class_weight="balanced",
                random_state=seed,
                n_jobs=-1,
                verbose=-1
            )

    return models


# -----------------------------
# Metric computation
# -----------------------------
def safe_predict_proba(model, X_test):
    if hasattr(model, "predict_proba"):
        return model.predict_proba(X_test)
    return None


def compute_metrics(y_true, y_pred, y_proba, labels):
    """
    Computes binary or multiclass metrics.
    For multiclass tasks, macro-F1, weighted-F1, and balanced accuracy
    are especially important because the original 0–4 target is imbalanced.
    """
    n_classes = len(labels)

    result = {}

    result["accuracy"] = accuracy_score(y_true, y_pred)
    result["balanced_accuracy"] = balanced_accuracy_score(y_true, y_pred)

    if n_classes == 2:
        result["f1"] = f1_score(y_true, y_pred, average="binary", zero_division=0)
        result["f1_macro"] = f1_score(y_true, y_pred, average="macro", zero_division=0)
        result["f1_weighted"] = f1_score(y_true, y_pred, average="weighted", zero_division=0)
        result["precision_macro"] = precision_score(y_true, y_pred, average="macro", zero_division=0)
        result["recall_macro"] = recall_score(y_true, y_pred, average="macro", zero_division=0)

        if y_proba is not None:
            try:
                positive_proba = y_proba[:, 1]
                result["roc_auc"] = roc_auc_score(y_true, positive_proba)
                result["logloss"] = log_loss(y_true, y_proba, labels=labels)
            except Exception:
                result["roc_auc"] = np.nan
                result["logloss"] = np.nan
        else:
            result["roc_auc"] = np.nan
            result["logloss"] = np.nan

    else:
        result["f1"] = f1_score(y_true, y_pred, average="macro", zero_division=0)
        result["f1_macro"] = f1_score(y_true, y_pred, average="macro", zero_division=0)
        result["f1_weighted"] = f1_score(y_true, y_pred, average="weighted", zero_division=0)
        result["precision_macro"] = precision_score(y_true, y_pred, average="macro", zero_division=0)
        result["recall_macro"] = recall_score(y_true, y_pred, average="macro", zero_division=0)

        if y_proba is not None:
            try:
                result["roc_auc"] = roc_auc_score(
                    y_true,
                    y_proba,
                    labels=labels,
                    multi_class="ovr",
                    average="macro"
                )
                result["logloss"] = log_loss(y_true, y_proba, labels=labels)
            except Exception:
                result["roc_auc"] = np.nan
                result["logloss"] = np.nan
        else:
            result["roc_auc"] = np.nan
            result["logloss"] = np.nan

    return result


# -----------------------------
# Run target sensitivity analysis
# -----------------------------
df_raw, FEATURE_COLS = load_raw_heart_dataset(RAW_CSV_PATH)
df_targets = add_target_formulations(df_raw)

TARGET_FORMULATIONS = {
    "binary_0_vs_1_4": "binary_0_vs_1_4",
    "ordinal_3class_0_vs_1_2_vs_3_4": "ordinal_3class_0_vs_1_2_vs_3_4",
    "multiclass_5class_0_1_2_3_4": "multiclass_5class_0_1_2_3_4"
}

# Class distribution table
class_distribution_rows = []

for formulation_name, target_col in TARGET_FORMULATIONS.items():
    counts = df_targets[target_col].value_counts().sort_index()
    total = counts.sum()

    for cls, count in counts.items():
        class_distribution_rows.append({
            "formulation": formulation_name,
            "class": int(cls),
            "count": int(count),
            "percentage": 100 * count / total
        })

class_distribution_df = pd.DataFrame(class_distribution_rows)
class_distribution_path = os.path.join(OUTPUT_DIR, "target_sensitivity_class_distribution.csv")
class_distribution_df.to_csv(class_distribution_path, index=False)

print("Class distributions saved to:", class_distribution_path)
display(class_distribution_df)


all_results = []
all_confusions = []

for formulation_name, target_col in TARGET_FORMULATIONS.items():

    print("\n" + "=" * 80)
    print(f"Target formulation: {formulation_name}")
    print("=" * 80)

    X = df_targets[FEATURE_COLS].copy()
    y = df_targets[target_col].astype(int).copy()

    labels = sorted(y.unique())
    n_classes = len(labels)

    for seed in SENSITIVITY_SEEDS:

        print(f"\nSeed: {seed}")

        X_train, X_test, y_train, y_test = train_test_split(
            X,
            y,
            test_size=TEST_SIZE,
            random_state=seed,
            stratify=y
        )

        models = build_sensitivity_models(n_classes=n_classes, seed=seed)

        for model_name, model in models.items():

            print(f"  Training: {model_name}")

            start_time = time.time()

            try:
                model.fit(X_train, y_train)
                y_pred = model.predict(X_test)
                y_proba = safe_predict_proba(model, X_test)

                runtime = time.time() - start_time

                metrics = compute_metrics(
                    y_true=y_test,
                    y_pred=y_pred,
                    y_proba=y_proba,
                    labels=labels
                )

                cm = confusion_matrix(y_test, y_pred, labels=labels)

                row = {
                    "formulation": formulation_name,
                    "target_column": target_col,
                    "seed": seed,
                    "model": model_name,
                    "n_classes": n_classes,
                    "n_train": len(y_train),
                    "n_test": len(y_test),
                    "runtime_seconds": runtime,
                    **metrics
                }

                all_results.append(row)

                # Store confusion matrix in long format
                for i, true_label in enumerate(labels):
                    for j, pred_label in enumerate(labels):
                        all_confusions.append({
                            "formulation": formulation_name,
                            "seed": seed,
                            "model": model_name,
                            "true_label": int(true_label),
                            "predicted_label": int(pred_label),
                            "count": int(cm[i, j])
                        })

            except Exception as e:
                runtime = time.time() - start_time
                print(f"    ERROR in {model_name}: {e}")

                all_results.append({
                    "formulation": formulation_name,
                    "target_column": target_col,
                    "seed": seed,
                    "model": model_name,
                    "n_classes": n_classes,
                    "n_train": len(y_train),
                    "n_test": len(y_test),
                    "runtime_seconds": runtime,
                    "accuracy": np.nan,
                    "balanced_accuracy": np.nan,
                    "f1": np.nan,
                    "f1_macro": np.nan,
                    "f1_weighted": np.nan,
                    "precision_macro": np.nan,
                    "recall_macro": np.nan,
                    "roc_auc": np.nan,
                    "logloss": np.nan,
                    "error": str(e)
                })


# -----------------------------
# Save raw results
# -----------------------------
results_df = pd.DataFrame(all_results)
results_path = os.path.join(OUTPUT_DIR, "target_sensitivity_results.csv")
results_df.to_csv(results_path, index=False)

confusion_df = pd.DataFrame(all_confusions)
confusion_path = os.path.join(OUTPUT_DIR, "target_sensitivity_confusion_matrices_long.csv")
confusion_df.to_csv(confusion_path, index=False)

print("\nRaw target sensitivity results saved to:", results_path)
print("Confusion matrices saved to:", confusion_path)


# -----------------------------
# Summary: mean ± SD
# -----------------------------
metric_cols = [
    "accuracy",
    "balanced_accuracy",
    "f1",
    "f1_macro",
    "f1_weighted",
    "precision_macro",
    "recall_macro",
    "roc_auc",
    "logloss",
    "runtime_seconds"
]

summary_df = (
    results_df
    .groupby(["formulation", "model"], as_index=False)
    .agg(
        n_runs=("seed", "count"),
        accuracy_mean=("accuracy", "mean"),
        accuracy_std=("accuracy", "std"),
        balanced_accuracy_mean=("balanced_accuracy", "mean"),
        balanced_accuracy_std=("balanced_accuracy", "std"),
        f1_macro_mean=("f1_macro", "mean"),
        f1_macro_std=("f1_macro", "std"),
        f1_weighted_mean=("f1_weighted", "mean"),
        f1_weighted_std=("f1_weighted", "std"),
        roc_auc_mean=("roc_auc", "mean"),
        roc_auc_std=("roc_auc", "std"),
        logloss_mean=("logloss", "mean"),
        logloss_std=("logloss", "std"),
        runtime_seconds_mean=("runtime_seconds", "mean"),
        runtime_seconds_std=("runtime_seconds", "std"),
    )
)

summary_path = os.path.join(OUTPUT_DIR, "target_sensitivity_summary.csv")
summary_df.to_csv(summary_path, index=False)

print("Summary saved to:", summary_path)


def fmt_mean_sd(mean_val, std_val, percent=True):
    if pd.isna(mean_val):
        return "NA"

    if percent:
        mean_val = mean_val * 100
        std_val = std_val * 100

    if pd.isna(std_val):
        return f"{mean_val:.2f}"

    return f"{mean_val:.2f} ± {std_val:.2f}"


formatted_rows = []

for _, row in summary_df.iterrows():
    formatted_rows.append({
        "formulation": row["formulation"],
        "model": row["model"],
        "n_runs": int(row["n_runs"]),
        "Accuracy (%)": fmt_mean_sd(row["accuracy_mean"], row["accuracy_std"], percent=True),
        "Balanced Accuracy (%)": fmt_mean_sd(row["balanced_accuracy_mean"], row["balanced_accuracy_std"], percent=True),
        "Macro-F1 (%)": fmt_mean_sd(row["f1_macro_mean"], row["f1_macro_std"], percent=True),
        "Weighted-F1 (%)": fmt_mean_sd(row["f1_weighted_mean"], row["f1_weighted_std"], percent=True),
        "ROC-AUC (%)": fmt_mean_sd(row["roc_auc_mean"], row["roc_auc_std"], percent=True),
        "LogLoss": fmt_mean_sd(row["logloss_mean"], row["logloss_std"], percent=False),
        "Runtime (s)": fmt_mean_sd(row["runtime_seconds_mean"], row["runtime_seconds_std"], percent=False),
    })

summary_formatted_df = pd.DataFrame(formatted_rows)

summary_formatted_path = os.path.join(
    OUTPUT_DIR,
    "target_sensitivity_summary_formatted.csv"
)

summary_formatted_df.to_csv(summary_formatted_path, index=False)

print("Formatted summary saved to:", summary_formatted_path)
display(summary_formatted_df)


# -----------------------------
# Best model per formulation
# -----------------------------
# Primary ranking:
# - binary: ROC-AUC first, then F1
# - multiclass/ordinal: macro-F1 first, then balanced accuracy
# Here we use macro-F1 as a unified ranking criterion.
# -----------------------------
best_by_formulation = (
    summary_df
    .sort_values(
        by=["formulation", "f1_macro_mean", "balanced_accuracy_mean", "roc_auc_mean"],
        ascending=[True, False, False, False]
    )
    .groupby("formulation", as_index=False)
    .head(1)
)

best_path = os.path.join(OUTPUT_DIR, "target_sensitivity_best_by_formulation.csv")
best_by_formulation.to_csv(best_path, index=False)

print("Best model per formulation saved to:", best_path)
display(best_by_formulation)


# -----------------------------
# README file for interpretation
# -----------------------------
readme_text = [
    {
        "item": "Purpose",
        "description": (
            "This analysis evaluates whether the main binary target formulation "
            "0 vs. 1–4 changes the conclusions compared with the original severity labels."
        )
    },
    {
        "item": "Binary formulation",
        "description": "target=0 vs. target=1–4; this is the main disease absence/presence task."
    },
    {
        "item": "Ordinal three-class formulation",
        "description": "class 0 = no disease; class 1 = original targets 1–2; class 2 = original targets 3–4."
    },
    {
        "item": "Five-class formulation",
        "description": "original target values 0, 1, 2, 3, and 4 are preserved."
    },
    {
        "item": "Recommended metrics",
        "description": (
            "For binary classification, ROC-AUC and F1 are useful. "
            "For ordinal/multiclass formulations, macro-F1 and balanced accuracy "
            "are more informative because of class imbalance."
        )
    },
    {
        "item": "Manuscript use",
        "description": (
            "Report this analysis as a supplementary sensitivity analysis, not as the main benchmark. "
            "It directly addresses the reviewer concern about loss of ordinal disease-severity information."
        )
    }
]

readme_df = pd.DataFrame(readme_text)
readme_path = os.path.join(OUTPUT_DIR, "target_sensitivity_readme.csv")
readme_df.to_csv(readme_path, index=False)

print("README saved to:", readme_path)

print("\nTarget sensitivity analysis completed successfully.")

Class distributions saved to: target_sensitivity_outputs/target_sensitivity_class_distribution.csv

                      formulation  class  count  percentage
0                 binary_0_vs_1_4      0    411   44.673913
1                 binary_0_vs_1_4      1    509   55.326087
2  ordinal_3class_0_vs_1_2_vs_3_4      0    411   44.673913
3  ordinal_3class_0_vs_1_2_vs_3_4      1    374   40.652174
4  ordinal_3class_0_vs_1_2_vs_3_4      2    135   14.673913
5     multiclass_5class_0_1_2_3_4      0    411   44.673913
6     multiclass_5class_0_1_2_3_4      1    265   28.804348
7     multiclass_5class_0_1_2_3_4      2    109   11.847826
8     multiclass_5class_0_1_2_3_4      3    107   11.630435
9     multiclass_5class_0_1_2_3_4      4     28    3.043478

================================================================================
Target formulation: binary_0_vs_1_4
================================================================================

Seed: 42
  Training: LogisticRegression_balanced
  Training: RandomForest_balanced
  Training: ExtraTrees_balanced
  Training: XGBoost_fixed
  Training: LightGBM_fixed

Seed: 7
  Training: LogisticRegression_balanced
  Training: RandomForest_balanced
  Training: ExtraTrees_balanced
  Training: XGBoost_fixed
  Training: LightGBM_fixed

Seed: 21
  Training: LogisticRegression_balanced
  Training: RandomForest_balanced
  Training: ExtraTrees_balanced
  Training: XGBoost_fixed
  Training: LightGBM_fixed

Seed: 84
  Training: LogisticRegression_balanced
  Training: RandomForest_balanced
  Training: ExtraTrees_balanced
  Training: XGBoost_fixed
  Training: LightGBM_fixed

Seed: 123
  Training: LogisticRegression_balanced
  Training: RandomForest_balanced
  Training: ExtraTrees_balanced
  Training: XGBoost_fixed
  Training: LightGBM_fixed

================================================================================
Target formulation: ordinal_3class_0_vs_1_2_vs_3_4
================================================================================

Seed: 42
  Training: LogisticRegression_balanced
  Training: RandomForest_balanced
  Training: ExtraTrees_balanced
  Training: XGBoost_fixed
  Training: LightGBM_fixed

Seed: 7
  Training: LogisticRegression_balanced
  Training: RandomForest_balanced
  Training: ExtraTrees_balanced
  Training: XGBoost_fixed
  Training: LightGBM_fixed

Seed: 21
  Training: LogisticRegression_balanced
  Training: RandomForest_balanced
  Training: ExtraTrees_balanced
  Training: XGBoost_fixed
  Training: LightGBM_fixed

Seed: 84
  Training: LogisticRegression_balanced
  Training: RandomForest_balanced
  Training: ExtraTrees_balanced
  Training: XGBoost_fixed
  Training: LightGBM_fixed

Seed: 123
  Training: LogisticRegression_balanced
  Training: RandomForest_balanced
  Training: ExtraTrees_balanced
  Training: XGBoost_fixed
  Training: LightGBM_fixed

================================================================================
Target formulation: multiclass_5class_0_1_2_3_4
================================================================================

Seed: 42
  Training: LogisticRegression_balanced
  Training: RandomForest_balanced
  Training: ExtraTrees_balanced
  Training: XGBoost_fixed
  Training: LightGBM_fixed

Seed: 7
  Training: LogisticRegression_balanced
  Training: RandomForest_balanced
  Training: ExtraTrees_balanced
  Training: XGBoost_fixed
  Training: LightGBM_fixed

Seed: 21
  Training: LogisticRegression_balanced
  Training: RandomForest_balanced
  Training: ExtraTrees_balanced
  Training: XGBoost_fixed
  Training: LightGBM_fixed

Seed: 84
  Training: LogisticRegression_balanced
  Training: RandomForest_balanced
  Training: ExtraTrees_balanced
  Training: XGBoost_fixed
  Training: LightGBM_fixed

Seed: 123
  Training: LogisticRegression_balanced
  Training: RandomForest_balanced
  Training: ExtraTrees_balanced
  Training: XGBoost_fixed
  Training: LightGBM_fixed

Raw target sensitivity results saved to: target_sensitivity_outputs/target_sensitivity_results.csv
Confusion matrices saved to: target_sensitivity_outputs/target_sensitivity_confusion_matrices_long.csv
Summary saved to: target_sensitivity_outputs/target_sensitivity_summary.csv
Formatted summary saved to: target_sensitivity_outputs/target_sensitivity_summary_formatted.csv

,formulation,model,n_runs,Accuracy (%),Balanced Accuracy (%),Macro-F1 (%),Weighted-F1 (%),ROC-AUC (%),LogLoss,Runtime (s)
0,binary_0_vs_1_4,ExtraTrees_balanced,5,80.11 ± 3.45,79.95 ± 3.55,79.89 ± 3.52,80.11 ± 3.47,89.27 ± 2.63,0.41 ± 0.04,0.81 ± 0.06
1,binary_0_vs_1_4,LightGBM_fixed,5,78.91 ± 4.50,78.68 ± 4.25,78.66 ± 4.43,78.90 ± 4.46,86.06 ± 1.84,0.63 ± 0.08,0.30 ± 0.27
2,binary_0_vs_1_4,LogisticRegression_balanced,5,81.41 ± 2.08,81.32 ± 2.05,81.24 ± 2.09,81.43 ± 2.07,87.71 ± 1.93,0.44 ± 0.03,0.01 ± 0.00
3,binary_0_vs_1_4,RandomForest_balanced,5,81.20 ± 1.91,80.91 ± 1.98,80.94 ± 1.96,81.17 ± 1.93,88.84 ± 2.55,0.42 ± 0.04,1.00 ± 0.05
4,binary_0_vs_1_4,XGBoost_fixed,5,81.85 ± 3.70,81.50 ± 3.57,81.57 ± 3.69,81.81 ± 3.67,88.33 ± 2.30,0.43 ± 0.05,0.10 ± 0.03
5,multiclass_5class_0_1_2_3_4,ExtraTrees_balanced,5,54.89 ± 1.92,37.05 ± 2.82,37.23 ± 3.47,54.81 ± 2.12,79.42 ± 1.53,1.05 ± 0.03,0.85 ± 0.08
6,multiclass_5class_0_1_2_3_4,LightGBM_fixed,5,55.43 ± 3.71,37.08 ± 4.41,36.96 ± 4.58,54.88 ± 3.76,77.60 ± 1.64,1.82 ± 0.19,1.18 ± 0.73
7,multiclass_5class_0_1_2_3_4,LogisticRegression_balanced,5,51.41 ± 4.13,42.49 ± 5.72,38.15 ± 4.28,52.71 ± 4.04,76.55 ± 2.49,1.20 ± 0.05,0.03 ± 0.01
8,multiclass_5class_0_1_2_3_4,RandomForest_balanced,5,57.72 ± 2.91,39.22 ± 2.01,39.63 ± 2.19,56.96 ± 3.07,80.53 ± 1.47,1.02 ± 0.03,1.09 ± 0.08
9,multiclass_5class_0_1_2_3_4,XGBoost_fixed,5,57.61 ± 3.42,36.32 ± 3.87,36.28 ± 4.38,55.60 ± 3.71,79.31 ± 1.26,1.07 ± 0.05,0.41 ± 0.12
10,ordinal_3class_0_vs_1_2_vs_3_4,ExtraTrees_balanced,5,64.35 ± 3.68,58.52 ± 5.52,58.08 ± 5.07,64.34 ± 3.63,81.71 ± 2.83,0.74 ± 0.04,0.83 ± 0.08
11,ordinal_3class_0_vs_1_2_vs_3_4,LightGBM_fixed,5,65.22 ± 1.44,59.15 ± 1.43,59.33 ± 1.45,65.07 ± 1.53,79.80 ± 2.41,1.13 ± 0.18,0.73 ± 0.46
12,ordinal_3class_0_vs_1_2_vs_3_4,LogisticRegression_balanced,5,60.87 ± 2.52,59.39 ± 2.72,56.79 ± 1.90,61.26 ± 2.36,79.72 ± 2.60,0.81 ± 0.05,0.02 ± 0.00
13,ordinal_3class_0_vs_1_2_vs_3_4,RandomForest_balanced,5,65.76 ± 1.54,58.29 ± 1.25,59.00 ± 1.30,65.21 ± 1.38,81.38 ± 2.09,0.73 ± 0.04,1.00 ± 0.01
14,ordinal_3class_0_vs_1_2_vs_3_4,XGBoost_fixed,5,66.41 ± 2.67,57.71 ± 1.70,58.66 ± 1.77,65.31 ± 2.34,81.24 ± 2.66,0.75 ± 0.07,0.24 ± 0.06

Best model per formulation saved to: target_sensitivity_outputs/target_sensitivity_best_by_formulation.csv

,formulation,model,n_runs,accuracy_mean,accuracy_std,balanced_accuracy_mean,balanced_accuracy_std,f1_macro_mean,f1_macro_std,f1_weighted_mean,f1_weighted_std,roc_auc_mean,roc_auc_std,logloss_mean,logloss_std,runtime_seconds_mean,runtime_seconds_std
4,binary_0_vs_1_4,XGBoost_fixed,5,0.818478,0.036980,0.814993,0.035725,0.815713,0.036855,0.818080,0.036721,0.883286,0.022981,0.428943,0.046000,0.104417,0.027055
8,multiclass_5class_0_1_2_3_4,RandomForest_balanced,5,0.577174,0.029115,0.392208,0.020119,0.396321,0.021879,0.569627,0.030711,0.805294,0.014650,1.018649,0.029563,1.085530,0.083597
11,ordinal_3class_0_vs_1_2_vs_3_4,LightGBM_fixed,5,0.652174,0.014379,0.591452,0.014268,0.593283,0.014510,0.650691,0.015271,0.798041,0.024094,1.128837,0.175591,0.732668,0.464197

README saved to: target_sensitivity_outputs/target_sensitivity_readme.csv

Target sensitivity analysis completed successfully.